import type {OrderInventoryGateway,VerifiedSession} from '../supabase.js';
export type ServerCheckoutInput={departureId:string;seats:number;idempotencyKey:string;paymentMethod:'card'|'bank_transfer';draftId?:string;couponId?:string;quoteId?:string};
export type ServerQuoteInput={departureId:string;seats:number;couponId?:string};
export interface AccessTokenVerifier{verify(token:string):Promise<VerifiedSession|null>}
export interface CardPaymentSessionGateway{available:boolean;create(input:{orderId:string;amount:number;idempotencyKey:string}):Promise<{clientSecret:string}|null>}
export interface ManualPaymentGateway{markPending(orderId:string,amount:number):Promise<{dueAt:string}|null>}
export interface CheckoutAttemptGateway{
  begin(accountId:string,input:ServerCheckoutInput):Promise<{attemptId:string;status:string;orderId:string|null;response:Record<string,unknown>|null}|null>;
  record(accountId:string,attemptId:string,orderId:string|null,status:string,response:Record<string,unknown>|null,errorCode?:string):Promise<boolean>;
}
export interface ServerPricingGateway{quote(departureId:string,seats:number):Promise<{amount:number;unitPrice:number;currency:'JPY'}|null>;createQuote?(accountId:string,input:ServerQuoteInput):Promise<Record<string,unknown>|null>;applyQuote?(accountId:string,orderId:string,quoteId:string):Promise<{amount:number;grossAmount:number;discountAmount:number;discountPercent:number;discountedSeats:number;discountedUnitPrice:number;sourceType:string}|null>;applyCoupon?(accountId:string,orderId:string,couponId:string,grossAmount:number):Promise<{amount:number;grossAmount:number;discountAmount:number;discountPercent:number;discountedSeats:number;discountedUnitPrice:number;sourceType:string}|null>;confirmFree?(accountId:string,orderId:string):Promise<boolean>}
export class CheckoutEndpoint{
  constructor(private readonly auth:AccessTokenVerifier,private readonly inventory:OrderInventoryGateway,private readonly card:CardPaymentSessionGateway,private readonly manual:ManualPaymentGateway,private readonly pricing:ServerPricingGateway,private readonly now=()=>new Date(),private readonly attempts?:CheckoutAttemptGateway){}
  async quote(authorization:string|undefined,input:ServerQuoteInput){const token=authorization?.match(/^Bearer (.+)$/)?.[1];if(!token)return {status:401,body:{error:'unauthorized'}};const session=await this.auth.verify(token);if(!session)return {status:401,body:{error:'unauthorized'}};if(!input.departureId||!Number.isInteger(input.seats)||input.seats<1)return {status:400,body:{error:'invalid_request'}};const quote=await this.pricing.createQuote?.(session.accountId,input);return quote?{status:200,body:quote}:{status:409,body:{error:'quote_unavailable'}}}
  async post(authorization:string|undefined,input:ServerCheckoutInput){
    const token=authorization?.match(/^Bearer (.+)$/)?.[1];if(!token)return {status:401,body:{error:'unauthorized'}};
    const session=await this.auth.verify(token);if(!session)return {status:401,body:{error:'unauthorized'}};
    if(!input.departureId||input.seats<1||!Number.isInteger(input.seats)||!input.idempotencyKey||!['card','bank_transfer'].includes(input.paymentMethod))return {status:400,body:{error:'invalid_request'}};
    const attempt=await this.attempts?.begin(session.accountId,input);
    if(this.attempts&&!attempt)return {status:409,body:{error:'checkout_idempotency_conflict'}};
    if(attempt?.response&&['requires_payment_action','pending_manual_review','confirmed_no_payment','paid'].includes(attempt.status))return {status:200,body:{...attempt.response,replayed:true}};
    const remember=async(status:string,orderId:string|null,response:Record<string,unknown>|null,errorCode?:string)=>{if(!attempt||!this.attempts)return true;return this.attempts.record(session.accountId,attempt.attemptId,orderId,status,response,errorCode)};
    const quote=await this.pricing.quote(input.departureId,input.seats);if(!quote)return {status:409,body:{error:'price_unavailable'}};
    const expiresAt=new Date(this.now().getTime()+15*60*1000).toISOString();const reserved=await this.inventory.reserve(session,{departureId:input.departureId,seats:input.seats,idempotencyKey:input.idempotencyKey,expiresAt,draftId:input.draftId});if(!reserved)return {status:409,body:{error:'inventory_unavailable'}};
    await remember('reserved',reserved.orderId,null);
    const discount=input.quoteId?await this.pricing.applyQuote?.(session.accountId,reserved.orderId,input.quoteId):input.couponId?await this.pricing.applyCoupon?.(session.accountId,reserved.orderId,input.couponId,quote.amount):null;if((input.quoteId||input.couponId)&&!discount){await this.inventory.cancel(session,reserved.orderId);await remember('superseded',reserved.orderId,null,input.quoteId?'quote_changed':'coupon_unavailable');return {status:409,body:{error:input.quoteId?'quote_changed':'coupon_unavailable'}}}const payable=discount?.amount??quote.amount;const breakdown=discount?{grossAmount:discount.grossAmount,discountAmount:discount.discountAmount,discountPercent:discount.discountPercent,discountedSeats:discount.discountedSeats,discountedUnitPrice:discount.discountedUnitPrice,couponSource:discount.sourceType}:{grossAmount:quote.amount,discountAmount:0,discountPercent:0,discountedSeats:0,discountedUnitPrice:quote.unitPrice,couponSource:null};
    if(payable===0){const confirmed=await this.pricing.confirmFree?.(session.accountId,reserved.orderId);if(!confirmed){await this.inventory.cancel(session,reserved.orderId);await remember('failed',reserved.orderId,null,'free_confirmation_failed');return {status:409,body:{error:'free_confirmation_failed'}}}const body={...reserved,...breakdown,amount:0,status:'confirmed_no_payment' as const,paymentKind:'coupon_covered'};await remember('confirmed_no_payment',reserved.orderId,body);return {status:200,body}}
    if(input.paymentMethod==='bank_transfer'){const pending=await this.manual.markPending(reserved.orderId,payable);if(!pending){await this.inventory.cancel(session,reserved.orderId);await remember('failed',reserved.orderId,null,'manual_payment_unavailable');return {status:503,body:{error:'manual_payment_unavailable'}}}const body={...reserved,...breakdown,amount:payable,status:'pending_manual_review' as const,paymentDueAt:pending.dueAt};await remember('pending_manual_review',reserved.orderId,body);return {status:200,body}}
    if(!this.card.available){await this.inventory.cancel(session,reserved.orderId);return {status:503,body:{error:'card_payment_unavailable'}}}
    const payment=await this.card.create({orderId:reserved.orderId,amount:payable,idempotencyKey:input.idempotencyKey});if(!payment){await this.inventory.cancel(session,reserved.orderId);await remember('failed',reserved.orderId,null,'card_payment_unavailable');return {status:503,body:{error:'card_payment_unavailable'}}}const body={...reserved,...breakdown,amount:payable,status:'requires_payment_action' as const,clientSecret:payment.clientSecret};await remember('requires_payment_action',reserved.orderId,body);return {status:200,body}
  }
}
