import {describe,expect,it,vi} from 'vitest';import {CheckoutEndpoint,type AccessTokenVerifier,type CardPaymentSessionGateway,type ManualPaymentGateway,type ServerPricingGateway} from '../server/api/checkout';import type {OrderInventoryGateway,VerifiedSession} from '../server/supabase';import {TestBackendApi} from '../src/shared/backend/testApi';
const session:VerifiedSession={accountId:'verified-account',accessTokenHash:'hash'};
const auth:AccessTokenVerifier={verify:async token=>token==='valid'?session:null};
const inventory=()=>{const calls:Array<{session:VerifiedSession;input:unknown}>=[];const gateway:OrderInventoryGateway={reserve:async(s,input)=>{calls.push({session:s,input});return {orderId:'order-1',holdId:'hold-1'}},cancel:vi.fn(async()=>true)};return {gateway,calls}};
const base={departureId:'departure-1',seats:2,idempotencyKey:'checkout-1'} as const;const pricing:ServerPricingGateway={quote:async()=>({amount:12000,currency:'JPY'})};
describe('测试后端最小闭环',()=>{
  it('未认证请求拒绝，accountId 只来自已验证 session',async()=>{const inv=inventory();const endpoint=new CheckoutEndpoint(auth,inv.gateway,{available:false,create:async()=>null},{markPending:async()=>true},pricing);expect((await endpoint.post(undefined,{...base,paymentMethod:'bank_transfer'})).status).toBe(401);expect((await endpoint.post('Bearer valid',{...base,paymentMethod:'bank_transfer'})).status).toBe(200);expect(inv.calls[0].session.accountId).toBe('verified-account');expect(inv.calls[0].input).not.toHaveProperty('accountId')});
  it('银行转账进入人工审核且不调用卡支付',async()=>{const inv=inventory();const card:CardPaymentSessionGateway={available:true,create:vi.fn(async()=>({clientSecret:'test-secret'}))};const manual:ManualPaymentGateway={markPending:vi.fn(async()=>true)};const result=await new CheckoutEndpoint(auth,inv.gateway,card,manual,pricing).post('Bearer valid',{...base,paymentMethod:'bank_transfer'});expect(result.body).toMatchObject({status:'pending_manual_review'});expect(card.create).not.toHaveBeenCalled();expect(manual.markPending).toHaveBeenCalledWith('order-1')});
  it('卡支付缺少服务端测试配置时 fail closed',async()=>{const inv=inventory();const result=await new CheckoutEndpoint(auth,inv.gateway,{available:false,create:async()=>null},{markPending:async()=>true},pricing).post('Bearer valid',{...base,paymentMethod:'card'});expect(result.status).toBe(503);expect(result.body).toEqual({error:'card_payment_unavailable'});expect(inv.calls).toHaveLength(0)});
  it('卡支付金额只来自服务端报价且只返回 client secret',async()=>{const inv=inventory();const create=vi.fn(async()=>({clientSecret:'pi_client_secret_test'}));const result=await new CheckoutEndpoint(auth,inv.gateway,{available:true,create},{markPending:async()=>true},pricing).post('Bearer valid',{...base,paymentMethod:'card'});expect(create).toHaveBeenCalledWith(expect.objectContaining({amount:12000}));expect(result.body).toMatchObject({status:'requires_payment_action',clientSecret:'pi_client_secret_test'});expect(JSON.stringify(result)).not.toContain('sk_test_')});
  it('服务端价格缺失或支付会话失败时取消订单并释放 hold',async()=>{const noPrice=inventory();const unavailablePrice=new CheckoutEndpoint(auth,noPrice.gateway,{available:true,create:async()=>({clientSecret:'unused'})},{markPending:async()=>true},{quote:async()=>null});expect((await unavailablePrice.post('Bearer valid',{...base,paymentMethod:'card'})).body).toEqual({error:'price_unavailable'});expect(noPrice.gateway.cancel).toHaveBeenCalled();const failedPayment=inventory();const endpoint=new CheckoutEndpoint(auth,failedPayment.gateway,{available:true,create:async()=>null},{markPending:async()=>true},pricing);expect((await endpoint.post('Bearer valid',{...base,paymentMethod:'card'})).status).toBe(503);expect(failedPayment.gateway.cancel).toHaveBeenCalled()});
  it('浏览器 gateway 只向 HTTPS API 发送 Bearer token 和业务参数',async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({orderId:'o',holdId:'h',status:'pending_manual_review'}),{status:200,headers:{'content-type':'application/json'}}));const api=new TestBackendApi('https://api.example.test',async()=>'access-token',fetcher as typeof fetch);const result=await api.checkout({...base,paymentMethod:'bank_transfer'});expect(result?.status).toBe('pending_manual_review');expect(fetcher).toHaveBeenCalledWith('https://api.example.test/v1/checkout',expect.objectContaining({method:'POST',headers:expect.objectContaining({authorization:'Bearer access-token'})}))});
});
