import {describe,expect,it} from 'vitest';import {canReceiveVehicleGroup,canSendVehicleGroupChat,CommerceDomain,visibleAssistanceFields} from '../server/commerceDomain';
describe('订单库存领域事务模型',()=>{
  it('并发最后一席仅一个成功',async()=>{const d=new CommerceDomain(1);const results=await Promise.allSettled([d.reserve({accountId:'a',departureId:'d',seats:1,key:'k1',expiresAt:100},0),d.reserve({accountId:'b',departureId:'d',seats:1,key:'k2',expiresAt:100},0)]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(results.filter(x=>x.status==='rejected')).toHaveLength(1)});
  it('同一 key 同业务参数复用且不受重试时钟漂移影响，不同业务参数拒绝',async()=>{const d=new CommerceDomain(2);const first=await d.reserve({accountId:'a',departureId:'d',seats:1,key:'same',expiresAt:100},0);expect((await d.reserve({accountId:'a',departureId:'d',seats:1,key:'same',expiresAt:95},1)).id).toBe(first.id);await expect(d.reserve({accountId:'a',departureId:'d',seats:2,key:'same',expiresAt:100},0)).rejects.toThrow('mismatch')});
  it('已过期的相同 key 不会复活旧库存锁',async()=>{const d=new CommerceDomain(1);await d.reserve({accountId:'a',departureId:'d',seats:1,key:'same',expiresAt:10},0);await expect(d.reserve({accountId:'a',departureId:'d',seats:1,key:'same',expiresAt:30},11)).rejects.toThrow('no longer active')});
  it('hold 过期后迟到支付进入人工补偿，不静默标 paid',async()=>{const d=new CommerceDomain(1);const order=await d.reserve({accountId:'a',departureId:'d',seats:1,key:'k',expiresAt:10},0);expect(await d.payment({eventId:'e1',orderId:order.id,status:'succeeded',eventAt:11},11)).toBe('payment-review');expect(d.snapshot(order.id).order?.status).toBe('payment_review')});
  it('取消与支付竞态串行且不会已付款无席位',async()=>{const d=new CommerceDomain(1);const order=await d.reserve({accountId:'a',departureId:'d',seats:1,key:'k',expiresAt:100},0);await Promise.all([d.cancel(order.id,'a',2),d.payment({eventId:'e1',orderId:order.id,status:'succeeded',eventAt:2},2)]);expect(['paid','payment_review']).toContain(d.snapshot(order.id).order?.status)});
  it('Webhook 重复、乱序和退款保持单调状态',async()=>{const d=new CommerceDomain(1);const order=await d.reserve({accountId:'a',departureId:'d',seats:1,key:'k',expiresAt:100},0);expect(await d.payment({eventId:'success',orderId:order.id,status:'succeeded',eventAt:10},10)).toBe('paid');expect(await d.payment({eventId:'success',orderId:order.id,status:'succeeded',eventAt:10},10)).toBe('duplicate');expect(await d.payment({eventId:'old-fail',orderId:order.id,status:'failed',eventAt:9},11)).toBe('ignored-out-of-order');expect(await d.payment({eventId:'refund',orderId:order.id,status:'refunded',eventAt:12},12)).toBe('refunded')});
  it('隐私投影仅向本车工作人员提供最小字段',()=>{expect(visibleAssistanceFields('owner')).toContain('privatePayload');expect(visibleAssistanceFields('assigned_staff')).toEqual(['staffProjection']);expect(visibleAssistanceFields('group_passenger')).toEqual([])});
  it('同车乘客可只读进入群，只有开放后才能发送普通聊天',()=>{expect(canReceiveVehicleGroup('group_passenger')).toBe(true);expect(canSendVehicleGroupChat('group_passenger','frozen')).toBe(false);expect(canSendVehicleGroupChat('group_passenger','open')).toBe(true);expect(canSendVehicleGroupChat('group_passenger','closed')).toBe(false)});
  it('非成员不能收发，冻结时工作人员也不能发送普通聊天',()=>{expect(canReceiveVehicleGroup('anonymous')).toBe(false);expect(canSendVehicleGroupChat('anonymous','open')).toBe(false);expect(canSendVehicleGroupChat('assigned_staff','frozen')).toBe(false);expect(canSendVehicleGroupChat('assigned_staff','open')).toBe(true)});
});
