import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,describe,expect,it,vi} from 'vitest';
import {MemoryRouter} from 'react-router-dom';
import {AppProvider} from '../src/app/store';
import {GrowthEntry,ReferralGrowth,TravelMoments} from '../src/app/GrowthPages';
import {canonicalizeTravelMomentUrl} from '../src/shared/travelMoments';
afterEach(cleanup);
const summary={code:'FRIEND10',discountPercent:10,completedInvites:3,successfulInvites:3,coupons:[{id:'coupon-1',discountPercent:10,status:'pending_trip_completion',availableAt:'2026-10-18T00:40:00Z'}]};
function renderWith(node:React.ReactNode,overrides:Record<string,unknown>={}){const services={loadSellableDepartures:async()=>({data:[],error:null}),currentUser:async()=>null,onAuthStateChange:()=>()=>{},loadOwnReferralSummary:async()=>summary,loadOwnTravelMoments:async()=>({trips:[{order_id:'order',trip_title:'京都奈良一日游',departure_at:'2026-10-12T00:00:00Z'}],submissions:[],error:null}),createTravelMoment:vi.fn(async()=>({id:'abcdef12-0000-0000-0000-000000000000',duplicate:false,status:'checking',reasonCodes:[],error:null})),checkTravelMoment:vi.fn(async()=>({status:'eligible'})),requestTravelMomentRecheck:vi.fn(async()=>({ok:true,error:null})),...overrides};return {services,...render(<MemoryRouter><AppProvider services={services as never}>{node}</AppProvider></MemoryRouter>)} }
describe('M020 growth entry and Travel Moments',()=>{
 it('keeps the two growth destinations explicit',()=>{renderWith(<GrowthEntry/>);expect(screen.getByRole('link',{name:/邀请好友/})).toHaveAttribute('href','/app/referral');expect(screen.getByRole('link',{name:/Travel Moments/})).toHaveAttribute('href','/app/travel-moments')});
 it('shows actual referral configuration, progress, and a pending reward availability time',async()=>{renderWith(<ReferralGrowth/>);expect((await screen.findAllByText(/10%/)).length).toBeGreaterThan(0);expect(screen.getByText('已成功邀请 3 位朋友')).toBeVisible();expect(screen.getByText(/再邀请 7 位/)).toBeVisible();expect(screen.getByText(/待解锁/)).toBeVisible();expect(screen.getByText(/预计可用时间/)).toBeVisible()});
 it('canonicalizes post identities and distinguishes profile links',()=>{expect(canonicalizeTravelMomentUrl('https://www.tiktok.com/@jtw/video/123?share=1')).toMatchObject({platform:'tiktok',contentId:'tiktok:123'});expect(canonicalizeTravelMomentUrl('https://instagram.com/reel/abc')).toMatchObject({platform:'instagram',contentId:'instagram:abc'});expect(canonicalizeTravelMomentUrl('https://instagram.com/jtw')).toEqual({reason:'PROFILE_URL_NOT_POST'})});
 it('creates one submission then immediately starts its generation-bound eligibility check',async()=>{const {services,container}=renderWith(<TravelMoments/>);const select=await screen.findByLabelText('选择对应的 JTW 旅行');fireEvent.change(select,{target:{value:'order'}});fireEvent.change(screen.getByLabelText('帖子链接'),{target:{value:'https://www.tiktok.com/@jtw/video/123'}});fireEvent.change(screen.getByLabelText('社交账号名称'),{target:{value:'@jtw'}});await waitFor(()=>expect(screen.getByRole('button',{name:'提交投稿并开始核验'})).toBeEnabled());fireEvent.submit(container.querySelector('form')!);await waitFor(()=>expect(services.createTravelMoment).toHaveBeenCalledWith(expect.objectContaining({platform:'tiktok',orderId:'order'})));await waitFor(()=>expect(services.checkTravelMoment).toHaveBeenCalledWith({submissionId:'abcdef12-0000-0000-0000-000000000000',trigger:'initial_submit',expectedGeneration:1}))});
});
