import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,describe,expect,it,vi} from 'vitest';
import {MemoryRouter} from 'react-router-dom';
import {AppProvider} from '../src/app/store';
import {GrowthEntry,ReferralGrowth,TravelMoments} from '../src/app/GrowthPages';
import {detectBoostPlatform,validBoostPost} from '../src/app/boostPost';
afterEach(cleanup);
const summary={code:'FRIEND10',discountPercent:10,completedInvites:3,successfulInvites:3,coupons:[{id:'coupon-1',discountPercent:10,status:'pending_trip_completion',availableAt:'2026-10-18T00:40:00Z'}]};
function renderWith(node:React.ReactNode,overrides:Record<string,unknown>={}){const services={loadSellableDepartures:async()=>({data:[],error:null}),currentUser:async()=>null,onAuthStateChange:()=>()=>{},loadOwnReferralSummary:async()=>summary,loadOwnShareCampaign:async()=>({campaign:{id:'campaign',campaign_month:'2026-10-01'},orders:[{id:'order',tripTitle:'京都奈良一日游',departureAt:'2026-10-12T00:00:00Z'}],submissions:[],error:null}),submitShareLink:vi.fn(async()=>({ok:true,id:'abcdef12-0000-0000-0000-000000000000'})),...overrides};return {services,...render(<MemoryRouter><AppProvider services={services as never}>{node}</AppProvider></MemoryRouter>)} }
describe('M020 growth entry and Travel Moments',()=>{
 it('keeps the two growth destinations explicit',()=>{renderWith(<GrowthEntry/>);expect(screen.getByRole('link',{name:/邀请好友/})).toHaveAttribute('href','/app/referral');expect(screen.getByRole('link',{name:/Travel Moments/})).toHaveAttribute('href','/app/travel-moments')});
 it('shows actual referral configuration, progress, and a pending reward availability time',async()=>{renderWith(<ReferralGrowth/>);expect((await screen.findAllByText(/10%/)).length).toBeGreaterThan(0);expect(screen.getByText('已成功邀请 3 位朋友')).toBeVisible();expect(screen.getByText(/再邀请 7 位/)).toBeVisible();expect(screen.getByText(/待解锁/)).toBeVisible();expect(screen.getByText(/预计可用时间/)).toBeVisible()});
 it('recognises only TikTok and Instagram public links',()=>{expect(detectBoostPlatform('https://www.tiktok.com/@jtw/video/123')).toBe('tiktok');expect(detectBoostPlatform('https://instagram.com/reel/abc')).toBe('instagram');expect(detectBoostPlatform('https://facebook.com/x/posts/1')).toBeNull();expect(validBoostPost('instagram','https://instagram.com/reel/abc')).toBe(true)});
 it('submits one explicit authorization and renders a stable opaque display code',async()=>{const {services,container}=renderWith(<TravelMoments/>);const select=await screen.findByLabelText('选择本月参加过的 JTW 行程');fireEvent.change(select,{target:{value:'order'}});fireEvent.change(screen.getByLabelText('TikTok / Instagram 作品链接'),{target:{value:'https://www.tiktok.com/@jtw/video/123'}});fireEvent.change(screen.getByLabelText('我的社媒账号'),{target:{value:'@jtw'}});fireEvent.click(screen.getByRole('checkbox'));await waitFor(()=>expect(screen.getByRole('button',{name:'提交 Travel Moments'})).toBeEnabled());fireEvent.submit(container.querySelector('form')!);await waitFor(()=>expect(services.submitShareLink).toHaveBeenCalledWith(expect.objectContaining({platform:'tiktok',mentionConfirmed:true,authorized:true})));expect(await screen.findByText(/TT-202610-ABCDEF12/)).toBeVisible()});
});
