import {describe,expect,it,vi} from 'vitest';import {readFileSync} from 'node:fs';import {createHmac} from 'node:crypto';import type {SupabaseClient} from '@supabase/supabase-js';import {NotificationOutboxWorker,SignedNotificationReceiptHandler,SupabaseNotificationOutbox} from '../server/notifications';
const sql=readFileSync('supabase/migrations/202608250018_notification_delivery_lifecycle.sql','utf8');
describe('018 通知投递生命周期',()=>{
  it('使用跳过锁、租约恢复、最大五次和指数退避',()=>{expect(sql).toMatch(/for update skip locked/);expect(sql).toMatch(/locked_at<p_now-interval '5 minutes'/);expect(sql).toMatch(/n\.attempts<5/);expect(sql).toMatch(/power\(2,n\.attempts\)/)});
  it('claim/complete 只允许可信服务且锁令牌必须匹配',()=>{expect(sql).toMatch(/trusted service only/);expect(sql).toMatch(/n\.lock_token=p_lock_token/);expect(sql).not.toMatch(/grant execute[\s\S]*to authenticated/)});
  it('provider 缺失时不领取、不伪装发送',async()=>{const rpc=vi.fn();const worker=new NotificationOutboxWorker(new SupabaseNotificationOutbox({rpc} as unknown as SupabaseClient),null);expect(await worker.runOnce()).toEqual({claimed:0,submitted:0,retried:0,reason:'provider-unavailable'});expect(rpc).not.toHaveBeenCalled()});
  it('供应商接收只确认 submitted，供应商异常进入 retry',async()=>{const rpc=vi.fn(async(name:string)=>name==='claim_notification_outbox'?{data:[{id:'n1'},{id:'n2'}],error:null}:{data:true,error:null});const outbox=new SupabaseNotificationOutbox({rpc} as unknown as SupabaseClient);const deliver=vi.fn(async(item:{id:string})=>{if(item.id==='n2')throw new Error('test');return {externalId:'external-test'}});const result=await new NotificationOutboxWorker(outbox,{available:true,provider:'test-only',deliver}).runOnce();expect(result).toMatchObject({claimed:2,submitted:1,retried:1,reason:'processed'});expect(rpc).toHaveBeenCalledWith('complete_notification_delivery',expect.objectContaining({p_outcome:'submitted',p_provider:'test-only'}));expect(rpc).toHaveBeenCalledWith('complete_notification_delivery',expect.objectContaining({p_outcome:'retry',p_error_code:'provider-error'}))});
});

describe('通知供应商签名回执',()=>{
  const secret='test-only-notification-webhook-secret-123456';
  const payload=Buffer.from(JSON.stringify({eventId:'provider-event-1',outboxId:'123e4567-e89b-42d3-a456-426614174000',status:'delivered',externalId:'external-1',occurredAt:'2026-09-03T01:02:03.000Z'}));
  it('只接受正确 HMAC，并仅向存储层传递摘要',async()=>{const apply=vi.fn(async()=>true);const handler=new SignedNotificationReceiptHandler(secret,{apply});const signature=`sha256=${createHmac('sha256',secret).update(payload).digest('hex')}`;expect(await handler.handle(payload,signature)).toEqual({accepted:true,reason:'applied'});expect(apply).toHaveBeenCalledWith(expect.objectContaining({eventId:'provider-event-1',status:'delivered',payloadDigest:expect.stringMatching(/^[0-9a-f]{64}$/)}));expect(await handler.handle(payload,'sha256=00')).toEqual({accepted:false,reason:'invalid-signature'})});
  it('拒绝未知字段和非法时间，不把原始回调写入数据库',async()=>{const apply=vi.fn(async()=>true);const handler=new SignedNotificationReceiptHandler(secret,{apply});const invalid=Buffer.from(JSON.stringify({...JSON.parse(payload.toString()),rawPersonalData:'forbidden'}));const signature=createHmac('sha256',secret).update(invalid).digest('hex');expect(await handler.handle(invalid,signature)).toEqual({accepted:false,reason:'invalid-payload'});expect(apply).not.toHaveBeenCalled()});
});
