import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,describe,expect,it,vi} from 'vitest';
import {MemoryRouter} from 'react-router-dom';
vi.mock('../src/app/store',()=>({useApp:()=>({state:{ui:{locale:'zh-CN'}}})}));
import {PassengerChatRoom} from '../src/app/PassengerChatRoom';
import {passengerChatDemo} from '../src/shared/data/passengerChatDemo';

afterEach(()=>{cleanup();vi.restoreAllMocks()});
const renderRoom=(overrides:Partial<Parameters<typeof PassengerChatRoom>[0]>={})=>render(<MemoryRouter><PassengerChatRoom {...passengerChatDemo} {...overrides}/></MemoryRouter>);

describe('游客群聊紧凑交互',()=>{
  it('点击集合栏展开并再次收起',()=>{renderRoom();const bar=screen.getByRole('button',{name:/11:30\s*集合/});expect(bar).toHaveAttribute('aria-expanded','false');fireEvent.click(bar);expect(bar).toHaveAttribute('aria-expanded','true');expect(screen.getByText('工作人员与车辆')).toBeInTheDocument();fireEvent.click(bar);expect(screen.queryByText('工作人员与车辆')).not.toBeInTheDocument()});
  it('电话和统一地图入口阻止集合栏展开，群聊不再嵌入 iframe 地图',()=>{vi.spyOn(window,'confirm').mockReturnValue(false);renderRoom({mapHref:'/app/trip-map?vehicleGroup=group-1'});const bar=screen.getByRole('button',{name:/11:30\s*集合/});fireEvent.click(screen.getByRole('button',{name:'拨打工作人员电话'}));expect(bar).toHaveAttribute('aria-expanded','false');const mapLink=screen.getByRole('link',{name:'打开步行导航'});expect(mapLink).toHaveAttribute('href','/app/trip-map?vehicleGroup=group-1');fireEvent.click(mapLink);expect(bar).toHaveAttribute('aria-expanded','false');expect(screen.queryByTitle('集合点地图')).not.toBeInTheDocument()});
  it('消息左右分列、角色标签明确且翻译失败仍显示原文',()=>{renderRoom({messages:[{id:'other',senderId:'p2',name:'游客A',role:'passenger',content:'Original message',time:'10:00'},{id:'mine',senderId:'me',name:'我',role:'passenger',content:'我的消息',time:'10:01'}]});expect(screen.getByText('Original message')).toBeInTheDocument();expect(screen.getByText('Original message').closest('article')).toHaveClass('other','role-passenger');expect(screen.getByText('游客A').parentElement).toHaveTextContent('乘客');expect(screen.getByText('我的消息').closest('article')).toHaveClass('own')});
  it('游客只看到集合总进度，不渲染其他乘客隐私字段',()=>{renderRoom();fireEvent.click(screen.getByRole('button',{name:/11:30\s*集合/}));expect(screen.getByText(/本车已集合\s+9\/12人/)).toBeInTheDocument();expect(document.body.textContent).not.toContain('其他乘客电话');expect(document.body.textContent).not.toContain('付款金额');expect(document.body.textContent).not.toContain('证件号码')});
  it('行程结束后输入区转为只读',()=>{renderRoom({status:'ended',readOnly:true});expect(screen.getAllByText('行程已结束，聊天已转为只读').length).toBeGreaterThan(0);expect(screen.getByRole('textbox',{name:'输入消息'})).toBeDisabled();expect(screen.getByRole('button',{name:'发送'})).toBeDisabled()});
  it('重大集合变更在确认前保持提醒并可确认',()=>{renderRoom();const alert=screen.getByText(/集合信息已变更/).closest('article')!;expect(alert).not.toHaveClass('acknowledged');fireEvent.click(screen.getByRole('button',{name:'我知道了'}));expect(alert).toHaveClass('acknowledged')});
  it('司机发起集合后才显示到达按钮',()=>{const {rerender}=renderRoom({meetingActive:false});fireEvent.click(screen.getByRole('button',{name:/11:30\s*集合/}));expect(screen.queryByRole('button',{name:'我已到达'})).not.toBeInTheDocument();rerender(<MemoryRouter><PassengerChatRoom {...passengerChatDemo} meetingActive={true}/></MemoryRouter>);expect(screen.getByRole('button',{name:'我已到达'})).toBeInTheDocument()});
  it('旧集合点只变淡且当前集合点带三角标记',()=>{renderRoom();const oldMeeting=screen.getByText('集合：东大寺南大门西侧');expect(oldMeeting.tagName).toBe('SPAN');expect(oldMeeting).toHaveClass('pc-previous-meeting');expect(screen.getByLabelText('当前集合点')).toHaveTextContent('▲')});
  it('真实模式只显示服务端传入的消息并响应实时更新',()=>{const onSend=vi.fn();const {rerender}=renderRoom({messages:[],onSend});expect(screen.queryByText('Linh')).not.toBeInTheDocument();rerender(<MemoryRouter><PassengerChatRoom {...passengerChatDemo} onSend={onSend} messages={[{id:'live',senderId:'operations',name:'运营',role:'operations',content:'实时集合通知',time:'12:00'}]}/></MemoryRouter>);expect(screen.getByText('实时集合通知')).toBeInTheDocument();expect(screen.queryByText('Linh')).not.toBeInTheDocument()});
  it('服务端工作人员身份在群聊中正确显示',()=>{renderRoom({messages:[{id:'driver',senderId:'staff-1',name:'山田',role:'driver',content:'车辆已经到达',time:'10:00'},{id:'guide',senderId:'staff-2',name:'林导',role:'guide',content:'请在集合点等候',time:'10:01'},{id:'driver-guide',senderId:'staff-3',name:'王',role:'driver_guide',content:'请稍候',time:'10:02'}],onSend:vi.fn()});expect(screen.getByText('司机')).toBeInTheDocument();expect(screen.getByText('导游')).toBeInTheDocument();expect(screen.getByText('司导')).toBeInTheDocument();expect(screen.getByText('车辆已经到达').closest('article')).toHaveClass('other','role-driver');expect(screen.getByText('请稍候').closest('article')).toHaveClass('role-driver_guide')});
  it('更多面板保留位置、相册和拍照入口，并支持再次点击关闭',()=>{renderRoom({renderMoreControls:close=><><button onClick={close}>发送位置</button><button onClick={close}>相册</button><button onClick={close}>拍照</button></>});const trigger=screen.getAllByRole('button',{name:'更多'}).at(-1)!;fireEvent.click(trigger);expect(screen.getByText('发送位置')).toBeInTheDocument();expect(screen.getByText('相册')).toBeInTheDocument();expect(screen.getByText('拍照')).toBeInTheDocument();fireEvent.click(trigger);expect(screen.queryByText('发送位置')).not.toBeInTheDocument()});
  it('顶部语言选择通过全局 locale 回调，而不是保留本地翻译语言',()=>{const onLocaleChange=vi.fn();renderRoom({onLocaleChange});fireEvent.click(screen.getByRole('button',{name:'翻译语言'}));fireEvent.click(screen.getByRole('button',{name:'English'}));expect(onLocaleChange).toHaveBeenCalledWith('en')});
  it('顶部提供全部八种全局应用语言',()=>{const onLocaleChange=vi.fn();renderRoom({onLocaleChange});const languages:[string,string][]=[['简体中文','zh-CN'],['繁體中文','zh-TW'],['日本語','ja'],['English','en'],['한국어','ko'],['Español','es'],['Tiếng Việt','vi'],['नेपाली','ne']];for(const [label,code] of languages){fireEvent.click(screen.getByRole('button',{name:'翻译语言'}));fireEvent.click(screen.getByRole('button',{name:label}));expect(onLocaleChange).toHaveBeenLastCalledWith(code)}});
  it('工作人员区域不再提供私聊入口',()=>{renderRoom();fireEvent.click(screen.getByRole('button',{name:/11:30\s*集合/}));expect(screen.queryByText('给工作人员发消息')).not.toBeInTheDocument()});
  it('展开后显示运营发布的公开电话、车辆颜色和照片入口',()=>{renderRoom({guide:{...passengerChatDemo.guide,phone:'+81-6-0000-0000',vehicle:{...passengerChatDemo.guide.vehicle,color:'黑色',photoUrl:'https://example.test/vehicle.jpg'}}});fireEvent.click(screen.getByRole('button',{name:/11:30\s*集合/}));expect(screen.getByText(/\+81-6-0000-0000/)).toBeInTheDocument();expect(screen.getByText(/黑色/)).toBeInTheDocument();expect(screen.getByRole('link',{name:'查看车辆照片'})).toHaveAttribute('href','https://example.test/vehicle.jpg')});
  it('真实资料缺失时禁用电话地图并隐藏虚构距离',()=>{renderRoom({party:{...passengerChatDemo.party,distanceMeters:null,walkMinutes:null},guide:{...passengerChatDemo.guide,phone:''},stops:[{...passengerChatDemo.stops[0],latitude:Number.NaN,longitude:Number.NaN,status:'current'}]});expect(screen.getByRole('button',{name:'拨打工作人员电话'})).toBeDisabled();expect(screen.getByRole('button',{name:'打开步行导航'})).toBeDisabled();expect(screen.getByRole('button',{name:/--/})).toBeInTheDocument()});
  it('迟到上报成功后显示持久状态，失败时保持选择窗口',async()=>{const onLate=vi.fn(async(minutes:number)=>minutes===10);renderRoom({meetingActive:true,onLate});fireEvent.click(screen.getByRole('button',{name:/11:30\s*集合/}));fireEvent.click(screen.getByRole('button',{name:'我可能迟到'}));fireEvent.click(screen.getByRole('button',{name:/预计迟到 5\s*分钟/}));expect(await screen.findByRole('dialog',{name:'迟到上报'})).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:/预计迟到 10\s*分钟/}));await waitFor(()=>expect(screen.queryByRole('dialog',{name:'迟到上报'})).not.toBeInTheDocument());expect(screen.getByText(/预计迟到 10\s*分钟/)).toBeInTheDocument();expect(onLate).toHaveBeenNthCalledWith(1,5);expect(onLate).toHaveBeenNthCalledWith(2,10)});
});
