import {cleanup,fireEvent,render,screen} from '@testing-library/react';
import {afterEach,describe,expect,it,vi} from 'vitest';
import {MemoryRouter} from 'react-router-dom';
import {PassengerChatRoom} from '../src/app/PassengerChatRoom';
import {passengerChatDemo} from '../src/shared/data/passengerChatDemo';

afterEach(()=>{cleanup();vi.restoreAllMocks()});
const renderRoom=(overrides:Partial<Parameters<typeof PassengerChatRoom>[0]>={})=>render(<MemoryRouter><PassengerChatRoom {...passengerChatDemo} {...overrides}/></MemoryRouter>);

describe('游客群聊紧凑交互',()=>{
  it('点击集合栏展开并再次收起',()=>{renderRoom();const bar=screen.getByRole('button',{name:/11:30集合/});expect(bar).toHaveAttribute('aria-expanded','false');fireEvent.click(bar);expect(bar).toHaveAttribute('aria-expanded','true');expect(screen.getByText('司导与车辆')).toBeInTheDocument();fireEvent.click(bar);expect(screen.queryByText('司导与车辆')).not.toBeInTheDocument()});
  it('电话和地图按钮阻止集合栏展开，地图可折叠且完整导航使用当前坐标',()=>{vi.spyOn(window,'confirm').mockReturnValue(false);const opened=vi.spyOn(window,'open').mockImplementation(()=>null);renderRoom();const bar=screen.getByRole('button',{name:/11:30集合/});fireEvent.click(screen.getByRole('button',{name:'拨打司导电话'}));expect(bar).toHaveAttribute('aria-expanded','false');const mapButton=screen.getByRole('button',{name:'打开步行导航'});fireEvent.click(mapButton);expect(bar).toHaveAttribute('aria-expanded','false');expect(mapButton).toHaveAttribute('aria-expanded','true');expect(screen.getByTitle('集合点地图')).toHaveAttribute('src',expect.stringContaining('34.6889%2C135.8398'));fireEvent.click(screen.getByRole('button',{name:'开始步行导航'}));expect(opened).toHaveBeenCalledWith(expect.stringContaining('34.6889%2C135.8398'),'_blank');fireEvent.click(mapButton);expect(screen.queryByTitle('集合点地图')).not.toBeInTheDocument()});
  it('消息左右分列且翻译失败仍显示原文',()=>{renderRoom({messages:[{id:'other',senderId:'p2',name:'游客A',role:'passenger',content:'Original message',time:'10:00'},{id:'mine',senderId:'me',name:'我',role:'passenger',content:'我的消息',time:'10:01'}]});expect(screen.getByText('Original message')).toBeInTheDocument();expect(screen.getByText('Original message').closest('article')).toHaveClass('other');expect(screen.getByText('我的消息').closest('article')).toHaveClass('own')});
  it('游客只看到集合总进度，不渲染其他乘客隐私字段',()=>{renderRoom();fireEvent.click(screen.getByRole('button',{name:/11:30集合/}));expect(screen.getByText(/全团已集合 9\/12人/)).toBeInTheDocument();expect(document.body.textContent).not.toContain('其他乘客电话');expect(document.body.textContent).not.toContain('付款金额');expect(document.body.textContent).not.toContain('证件号码')});
  it('行程结束后输入区转为只读',()=>{renderRoom({status:'ended',readOnly:true});expect(screen.getAllByText('行程已结束，聊天已转为只读').length).toBeGreaterThan(0);expect(screen.getByRole('textbox',{name:'输入消息'})).toBeDisabled();expect(screen.getByRole('button',{name:'发送'})).toBeDisabled()});
  it('重大集合变更在确认前保持提醒并可确认',()=>{renderRoom();const alert=screen.getByText(/集合信息已变更/).closest('article')!;expect(alert).not.toHaveClass('acknowledged');fireEvent.click(screen.getByRole('button',{name:'我知道了'}));expect(alert).toHaveClass('acknowledged')});
  it('司机发起集合后才显示到达按钮',()=>{const {rerender}=renderRoom({meetingActive:false});fireEvent.click(screen.getByRole('button',{name:/11:30集合/}));expect(screen.queryByRole('button',{name:'我已到达'})).not.toBeInTheDocument();rerender(<MemoryRouter><PassengerChatRoom {...passengerChatDemo} meetingActive={true}/></MemoryRouter>);expect(screen.getByRole('button',{name:'我已到达'})).toBeInTheDocument()});
  it('旧集合点只变淡且当前集合点带三角标记',()=>{renderRoom();const oldMeeting=screen.getByText('集合：东大寺南大门西侧');expect(oldMeeting.tagName).toBe('SPAN');expect(oldMeeting).toHaveClass('pc-previous-meeting');expect(screen.getByLabelText('当前集合点')).toHaveTextContent('▲')});
  it('真实模式只显示服务端传入的消息并响应实时更新',()=>{const onSend=vi.fn();const {rerender}=renderRoom({messages:[],onSend});expect(screen.queryByText('Linh')).not.toBeInTheDocument();rerender(<MemoryRouter><PassengerChatRoom {...passengerChatDemo} onSend={onSend} messages={[{id:'live',senderId:'operations',name:'运营',role:'operations',content:'实时集合通知',time:'12:00'}]}/></MemoryRouter>);expect(screen.getByText('实时集合通知')).toBeInTheDocument();expect(screen.queryByText('Linh')).not.toBeInTheDocument()});
  it('服务端工作人员身份在群聊中正确显示',()=>{renderRoom({messages:[{id:'driver',senderId:'staff-1',name:'山田',role:'driver',content:'车辆已经到达',time:'10:00'},{id:'guide',senderId:'staff-2',name:'林导',role:'guide',content:'请在集合点等候',time:'10:01'}],onSend:vi.fn()});expect(screen.getByText('司机')).toBeInTheDocument();expect(screen.getByText('司导')).toBeInTheDocument();expect(screen.getByText('车辆已经到达').closest('article')).toHaveClass('other')});
  it('真实资料缺失时禁用电话地图并隐藏虚构距离',()=>{renderRoom({party:{...passengerChatDemo.party,distanceMeters:null,walkMinutes:null},guide:{...passengerChatDemo.guide,phone:''},stops:[{...passengerChatDemo.stops[0],latitude:Number.NaN,longitude:Number.NaN,status:'current'}]});expect(screen.getByRole('button',{name:'拨打司导电话'})).toBeDisabled();expect(screen.getByRole('button',{name:'打开步行导航'})).toBeDisabled();expect(screen.getByRole('button',{name:/--/})).toBeInTheDocument()});
});
