import {describe,expect,it,vi} from 'vitest';import {readFileSync} from 'node:fs';import {SupabaseOperationsRepository} from '../src/shared/integrations/supabaseOperations';
const migration=readFileSync('supabase/migrations/202609090098_departure_edit_and_driver_statistics.sql','utf8');const page=readFileSync('src/app/operations/DepartureCenter.tsx','utf8');
describe('V3-D operations controls',()=>{
 it('lists editable departures with versions and committed inventory',()=>{expect(migration).toContain('get_operations_editable_departures');expect(migration).toContain('schedule_version');expect(migration).toContain("l.status='committed'")});
 it('provides source-backed driver workload statistics',()=>{expect(migration).toContain('get_operations_driver_statistics');expect(migration).toContain("js.status='completed'");expect(migration).toContain('driver_location_points')});
 it('sends optimistic version and complete schedule fields to the update RPC',async()=>{const rpc=vi.fn().mockResolvedValue({data:{affectedPaidOrders:1},error:null});const repository=new SupabaseOperationsRepository({rpc} as never);await repository.updateDeparture({id:'d',expectedVersion:1,departsAt:'2026-09-12T00:00:00Z',endsAt:'2026-09-12T10:00:00Z',price:8000,capacity:10,salesOpenAt:'2026-09-01T00:00:00Z',salesCloseAt:'2026-09-10T00:00:00Z',status:'open',meetingName:'大阪站',meetingAddress:'大阪市北区测试地址',mapLat:34.7,mapLng:135.5});expect(rpc).toHaveBeenCalledWith('operations_update_departure_v2',expect.objectContaining({p_expected_version:1,p_price:8000,p_capacity:10,p_departs_at:'2026-09-12T00:00:00Z'}))});
 it('exposes existing departure editing instead of batch-create only',()=>{expect(page).toContain('日期、集合、价格与截止时间调整');expect(page).toContain('旧订单价格、路线与取消政策快照不会改变')});
 it('reuses one operation id and coordinates business cutoffs',()=>{const schedule=readFileSync('supabase/migrations/202609090093_departure_schedule_and_order_snapshot.sql','utf8');expect(page).toMatch(/const input\s*=\s*\{[\s\S]*values\(new FormData\(event\.currentTarget\)\)[\s\S]*operationId:\s*uuid\(\)/);expect(page).toContain('createDepartureBatch(');expect(page).toContain('request as Parameters');expect(migration).toContain('departures_trip_departure_unique');expect(schedule).toContain('booking_closes_at=p_sales_close');expect(schedule).toContain("time '12:00'")});
});
