import type {PassengerLocale} from './passengerLocale';
type Copy={send:string;confirm:string;stop:string;cancel:string;working:string;failed:string;shared:string;staff:string;empty:string};
export const locationShareCopy:Record<PassengerLocale,Copy>={
 'zh-CN':{send:'发送当前位置',confirm:'将此位置共享15分钟，仅本车授权工作人员可见？这不是签到或登车。',stop:'停止共享',cancel:'取消',working:'正在处理…',failed:'位置操作失败，请检查定位权限或网络后重试。',shared:'位置快照共享中，15分钟后到期；不持续定位。',staff:'游客主动共享的位置',empty:'暂无有效的位置共享'},
 'zh-TW':{send:'傳送目前位置',confirm:'分享此位置15分鐘，僅本車授權工作人員可見？這不是報到或登車。',stop:'停止分享',cancel:'取消',working:'處理中…',failed:'位置操作失敗，請檢查定位權限或網路後重試。',shared:'位置快照分享中，15分鐘後到期；不持續定位。',staff:'旅客主動分享的位置',empty:'目前沒有有效的位置分享'},
 en:{send:'Send current location',confirm:'Share this location for 15 minutes with assigned staff only? This is not arrival or boarding confirmation.',stop:'Stop sharing',cancel:'Cancel',working:'Working…',failed:'Location action failed. Check permission or connection and retry.',shared:'Sharing a location snapshot for 15 minutes, not continuous tracking.',staff:'Locations shared by passengers',empty:'No active location shares'},
 ja:{send:'現在地を送信',confirm:'この位置を担当スタッフだけに15分間共有しますか？到着・乗車確認にはなりません。',stop:'共有を停止',cancel:'キャンセル',working:'処理中…',failed:'位置情報の操作に失敗しました。権限と通信を確認し再試行してください。',shared:'取得した位置を15分間共有中です。継続的な追跡ではありません。',staff:'参加者が共有した位置',empty:'有効な位置共有はありません'},
 ko:{send:'현재 위치 보내기',confirm:'이 위치를 담당 직원에게만 15분 동안 공유할까요? 도착 또는 탑승 확인이 아닙니다.',stop:'공유 중지',cancel:'취소',working:'처리 중…',failed:'위치 작업에 실패했습니다. 권한과 연결을 확인하고 다시 시도하세요.',shared:'위치 스냅샷을 15분 동안 공유합니다. 지속적인 추적이 아닙니다.',staff:'승객이 공유한 위치',empty:'활성 위치 공유가 없습니다'},
 es:{send:'Enviar ubicación actual',confirm:'¿Compartir esta ubicación durante 15 minutos solo con el personal asignado? No confirma la llegada ni el embarque.',stop:'Dejar de compartir',cancel:'Cancelar',working:'Procesando…',failed:'No se pudo completar la acción. Revisa los permisos y la conexión e inténtalo de nuevo.',shared:'Ubicación puntual compartida durante 15 minutos, sin seguimiento continuo.',staff:'Ubicaciones compartidas por viajeros',empty:'No hay ubicaciones compartidas activas'},
 vi:{send:'Gửi vị trí hiện tại',confirm:'Chia sẻ vị trí này trong 15 phút chỉ với nhân viên được phân công? Đây không phải xác nhận đến nơi hoặc lên xe.',stop:'Dừng chia sẻ',cancel:'Hủy',working:'Đang xử lý…',failed:'Thao tác vị trí thất bại. Kiểm tra quyền và kết nối rồi thử lại.',shared:'Chia sẻ vị trí tại thời điểm lấy trong 15 phút, không theo dõi liên tục.',staff:'Vị trí khách đã chia sẻ',empty:'Không có vị trí đang được chia sẻ'},
 ne:{send:'हालको स्थान पठाउनुहोस्',confirm:'यो स्थान तोकिएका कर्मचारीसँग मात्र १५ मिनेट साझा गर्ने? यसले आइपुगेको वा बस चढेको पुष्टि गर्दैन।',stop:'साझेदारी रोक्नुहोस्',cancel:'रद्द गर्नुहोस्',working:'प्रक्रियामा…',failed:'स्थानसम्बन्धी कार्य असफल भयो। अनुमति र नेटवर्क जाँचेर फेरि प्रयास गर्नुहोस्।',shared:'१५ मिनेटका लागि एकपटकको स्थान साझा हुँदैछ, निरन्तर ट्र्याकिङ होइन।',staff:'यात्रुले साझा गरेका स्थान',empty:'सक्रिय स्थान साझेदारी छैन'},
};
