export const passengerLocales = [
  { code: "zh-CN", short: "简", label: "简体中文" },
  { code: "zh-TW", short: "繁", label: "繁體中文" },
  { code: "ja", short: "日", label: "日本語" },
  { code: "en", short: "EN", label: "English" },
  { code: "vi", short: "VI", label: "Tiếng Việt" },
  { code: "ne", short: "ने", label: "नेपाली" },
  { code: "ko", short: "한", label: "한국어" },
] as const;

export type PassengerLocale = (typeof passengerLocales)[number]["code"];

export function normalizePassengerLocale(value: string): PassengerLocale | null {
  const code = value.trim().toLowerCase();
  if (code.startsWith("zh-tw") || code.startsWith("zh-hk") || code.startsWith("zh-hant")) return "zh-TW";
  if (code.startsWith("zh")) return "zh-CN";
  if (code.startsWith("ja")) return "ja";
  if (code.startsWith("en")) return "en";
  if (code.startsWith("vi")) return "vi";
  if (code.startsWith("ne")) return "ne";
  if (code.startsWith("ko")) return "ko";
  return null;
}

export const passengerCoreCopy = {
  "zh-CN": { language: "语言", home: "首页", trips: "行程", orders: "订单", messages: "消息", profile: "我的", backHome: "返回游客端首页", welcome: "欢迎", loginTitle: "从关西周末出发", login: "登录账户", testLogin: "登录测试账户", localAccount: "创建仅限当前会话的本地开发账户", unavailable: "正式账户服务尚未连接", email: "电子邮箱", emailPlaceholder: "请输入电子邮箱", password: "密码", referral: "推荐码", optional: "选填", submit: "登录 / 创建账户", steps: ["选择班次", "乘客资料", "确认订单", "提交订单"] },
  "zh-TW": { language: "語言", home: "首頁", trips: "行程", orders: "訂單", messages: "訊息", profile: "我的", backHome: "返回旅客端首頁", welcome: "歡迎", loginTitle: "從關西週末出發", login: "登入帳戶", testLogin: "登入測試帳戶", localAccount: "建立僅限目前工作階段的本機開發帳戶", unavailable: "正式帳戶服務尚未連線", email: "電子郵件", emailPlaceholder: "請輸入電子郵件", password: "密碼", referral: "推薦碼", optional: "選填", submit: "登入／建立帳戶", steps: ["選擇班次", "旅客資料", "確認訂單", "提交訂單"] },
  ja: { language: "言語", home: "ホーム", trips: "ツアー", orders: "予約", messages: "メッセージ", profile: "マイページ", backHome: "旅行者ホームへ戻る", welcome: "ようこそ", loginTitle: "関西から週末の旅へ", login: "アカウントにログイン", testLogin: "テストアカウントにログイン", localAccount: "このセッション専用の開発アカウントを作成", unavailable: "アカウントサービスは未接続です", email: "メールアドレス", emailPlaceholder: "メールアドレスを入力", password: "パスワード", referral: "紹介コード", optional: "任意", submit: "ログイン／アカウント作成", steps: ["便を選択", "乗客情報", "予約確認", "予約送信"] },
  en: { language: "Language", home: "Home", trips: "Trips", orders: "Orders", messages: "Messages", profile: "Profile", backHome: "Back to passenger home", welcome: "Welcome", loginTitle: "Your weekend from Kansai", login: "Sign in", testLogin: "Sign in to a test account", localAccount: "Create a local account for this session", unavailable: "Account service is not connected", email: "Email", emailPlaceholder: "Enter your email", password: "Password", referral: "Referral code", optional: "Optional", submit: "Sign in / Create account", steps: ["Choose departure", "Passenger details", "Review order", "Submit order"] },
  vi: { language: "Ngôn ngữ", home: "Trang chủ", trips: "Chuyến đi", orders: "Đơn đặt", messages: "Tin nhắn", profile: "Cá nhân", backHome: "Về trang chủ hành khách", welcome: "Chào mừng", loginTitle: "Cuối tuần khởi hành từ Kansai", login: "Đăng nhập", testLogin: "Đăng nhập tài khoản thử nghiệm", localAccount: "Tạo tài khoản cục bộ cho phiên này", unavailable: "Dịch vụ tài khoản chưa được kết nối", email: "Email", emailPlaceholder: "Nhập email", password: "Mật khẩu", referral: "Mã giới thiệu", optional: "Không bắt buộc", submit: "Đăng nhập / Tạo tài khoản", steps: ["Chọn chuyến", "Thông tin hành khách", "Xác nhận đơn", "Gửi đơn"] },
  ne: { language: "भाषा", home: "गृहपृष्ठ", trips: "यात्रा", orders: "अर्डर", messages: "सन्देश", profile: "मेरो", backHome: "यात्री गृहपृष्ठमा फर्कनुहोस्", welcome: "स्वागत छ", loginTitle: "कान्साइबाट सप्ताहन्त यात्रा", login: "लग इन गर्नुहोस्", testLogin: "परीक्षण खातामा लग इन", localAccount: "यस सत्रका लागि स्थानीय खाता बनाउनुहोस्", unavailable: "खाता सेवा जडान भएको छैन", email: "इमेल", emailPlaceholder: "इमेल लेख्नुहोस्", password: "पासवर्ड", referral: "रेफरल कोड", optional: "वैकल्पिक", submit: "लग इन / खाता बनाउनुहोस्", steps: ["प्रस्थान छान्नुहोस्", "यात्री विवरण", "अर्डर जाँच", "अर्डर पठाउनुहोस्"] },
  ko: { language: "언어", home: "홈", trips: "여행", orders: "예약", messages: "메시지", profile: "마이", backHome: "여행자 홈으로", welcome: "환영합니다", loginTitle: "간사이에서 떠나는 주말 여행", login: "로그인", testLogin: "테스트 계정 로그인", localAccount: "현재 세션용 로컬 계정 만들기", unavailable: "계정 서비스가 연결되지 않았습니다", email: "이메일", emailPlaceholder: "이메일을 입력하세요", password: "비밀번호", referral: "추천 코드", optional: "선택", submit: "로그인 / 계정 만들기", steps: ["출발편 선택", "승객 정보", "예약 확인", "예약 제출"] },
} satisfies Record<PassengerLocale, { language:string; home:string; trips:string; orders:string; messages:string; profile:string; backHome:string; welcome:string; loginTitle:string; login:string; testLogin:string; localAccount:string; unavailable:string; email:string; emailPlaceholder:string; password:string; referral:string; optional:string; submit:string; steps:readonly string[] }>;

type HomeCopy={kicker:string;greeting:string;passTitle:string;passText:string;choose:string;credit:string;tier:string;benefits:string;meeting:string;guides:string;support:string;alert:string;alertText:string;picks:string;allRoutes:string;available:string;all:string;ideas:string;privateTitle:string;privateText:string;inquire:string;loadingTitle:string;loadingText:string;errorTitle:string;errorText:string;emptyTitle:string;emptyText:string;pricePending:string;perSeat:string;seatsLeft:string};
export const passengerHomeCopy:Record<PassengerLocale,HomeCopy>={
  'zh-CN':{kicker:'周末，从大阪出发',greeting:'你好，今天想去哪里？',passTitle:'把关西周末装进口袋',passText:'路线、订单、集合与旅行消息集中查看',choose:'开始选路线',credit:'旅行金',tier:'会员等级',benefits:'查看权益',meeting:'集合行程',guides:'旅行指南',support:'客服',alert:'出发提醒',alertText:'付款、集合与车辆通知集中查看',picks:'这个周末，去看更远的风景',allRoutes:'全部路线',available:'近期可订班次',all:'查看全部',ideas:'出发前，看一点有用的',privateTitle:'企业、学校或亲友团体出行',privateText:'告诉我们人数和日期，获取专属方案。',inquire:'咨询',loadingTitle:'正在读取可售班次',loadingText:'请稍候，正在同步最新出发信息。',errorTitle:'暂时无法读取班次',errorText:'请稍后刷新页面重试。',emptyTitle:'暂无开放班次',emptyText:'目前没有正式开放的日期、价格和余位。',pricePending:'价格待确认',perSeat:'每席',seatsLeft:'余'},
  'zh-TW':{kicker:'週末，從大阪出發',greeting:'你好，今天想去哪裡？',passTitle:'把關西週末裝進口袋',passText:'集中查看路線、訂單、集合與旅行訊息',choose:'開始選路線',credit:'旅行金',tier:'會員等級',benefits:'查看權益',meeting:'集合行程',guides:'旅行指南',support:'客服',alert:'出發提醒',alertText:'集中查看付款、集合與車輛通知',picks:'這個週末，去看更遠的風景',allRoutes:'全部路線',available:'近期可訂班次',all:'查看全部',ideas:'出發前，看一點有用的',privateTitle:'企業、學校或親友團體出行',privateText:'告訴我們人數和日期，取得專屬方案。',inquire:'諮詢',loadingTitle:'正在讀取可售班次',loadingText:'請稍候，正在同步最新出發資訊。',errorTitle:'暫時無法讀取班次',errorText:'請稍後重新整理頁面。',emptyTitle:'暫無開放班次',emptyText:'目前沒有正式開放的日期、價格和餘位。',pricePending:'價格待確認',perSeat:'每席',seatsLeft:'餘'},
  ja:{kicker:'週末は大阪から',greeting:'今日はどこへ行きますか？',passTitle:'関西の週末旅をポケットに',passText:'ツアー、予約、集合、旅行メッセージをまとめて確認',choose:'ツアーを選ぶ',credit:'トラベルクレジット',tier:'会員ランク',benefits:'特典を見る',meeting:'集合・旅程',guides:'旅行ガイド',support:'サポート',alert:'出発のお知らせ',alertText:'支払い・集合・車両のお知らせをまとめて確認',picks:'今週末、少し遠くの景色へ',allRoutes:'すべてのツアー',available:'近日予約可能',all:'すべて見る',ideas:'出発前に役立つ情報',privateTitle:'企業・学校・ご家族や友人の団体旅行',privateText:'人数と日程をお知らせください。専用プランをご案内します。',inquire:'問い合わせ',loadingTitle:'予約可能な便を取得中',loadingText:'最新の出発情報を同期しています。',errorTitle:'便を取得できません',errorText:'しばらくしてから更新してください。',emptyTitle:'予約可能な便はありません',emptyText:'現在、正式に販売中の日程・料金・残席はありません。',pricePending:'料金確認中',perSeat:'1席',seatsLeft:'残り'},
  en:{kicker:'Weekends from Osaka',greeting:'Where would you like to go today?',passTitle:'Your Kansai weekend in one place',passText:'Routes, orders, meeting details and travel messages',choose:'Choose a trip',credit:'Travel credit',tier:'Member tier',benefits:'View benefits',meeting:'My itinerary',guides:'Travel guides',support:'Support',alert:'Departure alerts',alertText:'Payment, meeting and vehicle updates in one place',picks:'Go a little farther this weekend',allRoutes:'All trips',available:'Available soon',all:'View all',ideas:'Useful before you go',privateTitle:'Trips for companies, schools, families and friends',privateText:'Tell us your group size and date for a tailored plan.',inquire:'Enquire',loadingTitle:'Loading departures',loadingText:'Syncing the latest departure information.',errorTitle:'Departures unavailable',errorText:'Please refresh and try again later.',emptyTitle:'No departures available',emptyText:'There are currently no published dates, prices or seats.',pricePending:'Price pending',perSeat:'per seat',seatsLeft:'left'},
  vi:{kicker:'Cuối tuần khởi hành từ Osaka',greeting:'Hôm nay bạn muốn đi đâu?',passTitle:'Cuối tuần Kansai trong tầm tay',passText:'Xem tuyến, đơn đặt, điểm tập trung và tin nhắn tại một nơi',choose:'Chọn chuyến đi',credit:'Tín dụng du lịch',tier:'Hạng thành viên',benefits:'Xem quyền lợi',meeting:'Lịch trình tập trung',guides:'Hướng dẫn du lịch',support:'Hỗ trợ',alert:'Nhắc khởi hành',alertText:'Xem chung thông báo thanh toán, tập trung và xe',picks:'Cuối tuần này, đi xa hơn một chút',allRoutes:'Tất cả tuyến',available:'Chuyến sắp mở bán',all:'Xem tất cả',ideas:'Thông tin hữu ích trước khi đi',privateTitle:'Chuyến đi cho công ty, trường học, gia đình và bạn bè',privateText:'Cho chúng tôi biết số người và ngày đi để nhận phương án riêng.',inquire:'Tư vấn',loadingTitle:'Đang tải chuyến có thể đặt',loadingText:'Đang đồng bộ thông tin khởi hành mới nhất.',errorTitle:'Không thể tải chuyến',errorText:'Vui lòng làm mới và thử lại sau.',emptyTitle:'Chưa có chuyến mở bán',emptyText:'Hiện chưa có ngày, giá và chỗ trống được công bố.',pricePending:'Giá đang xác nhận',perSeat:'mỗi ghế',seatsLeft:'còn'},
  ne:{kicker:'ओसाकाबाट सप्ताहन्त यात्रा',greeting:'आज कहाँ जान चाहनुहुन्छ?',passTitle:'कान्साइ सप्ताहन्त यात्रा एकै ठाउँमा',passText:'रुट, अर्डर, भेट्ने विवरण र यात्रा सन्देश',choose:'यात्रा छान्नुहोस्',credit:'यात्रा क्रेडिट',tier:'सदस्य स्तर',benefits:'सुविधा हेर्नुहोस्',meeting:'मेरो यात्रा',guides:'यात्रा गाइड',support:'सहायता',alert:'प्रस्थान सूचना',alertText:'भुक्तानी, भेट्ने र गाडीका सूचना एकै ठाउँमा',picks:'यो सप्ताहन्त अलि टाढा घुम्नुहोस्',allRoutes:'सबै यात्रा',available:'छिट्टै बुक गर्न मिल्ने',all:'सबै हेर्नुहोस्',ideas:'जानुअघि उपयोगी जानकारी',privateTitle:'कम्पनी, विद्यालय, परिवार र साथीका समूह यात्रा',privateText:'समूह संख्या र मिति दिनुहोस्, विशेष योजना पाउनुहोस्।',inquire:'सोधपुछ',loadingTitle:'उपलब्ध प्रस्थान लोड हुँदैछ',loadingText:'नवीनतम प्रस्थान जानकारी मिलाइँदैछ।',errorTitle:'प्रस्थान लोड गर्न सकिएन',errorText:'पछि फेरि प्रयास गर्नुहोस्।',emptyTitle:'खुला प्रस्थान छैन',emptyText:'हाल प्रकाशित मिति, मूल्य वा सिट छैन।',pricePending:'मूल्य पुष्टि हुन बाँकी',perSeat:'प्रति सिट',seatsLeft:'बाँकी'},
  ko:{kicker:'주말, 오사카에서 출발',greeting:'오늘은 어디로 떠나고 싶으세요?',passTitle:'간사이 주말여행을 한곳에서',passText:'노선, 예약, 집합 정보와 여행 메시지를 한 번에 확인',choose:'여행 선택하기',credit:'여행 크레딧',tier:'회원 등급',benefits:'혜택 보기',meeting:'집합 일정',guides:'여행 가이드',support:'고객지원',alert:'출발 알림',alertText:'결제·집합·차량 알림을 한곳에서 확인',picks:'이번 주말, 조금 더 먼 풍경으로',allRoutes:'전체 여행',available:'곧 예약 가능한 일정',all:'전체 보기',ideas:'출발 전 유용한 정보',privateTitle:'기업·학교·가족·친구 단체 여행',privateText:'인원과 날짜를 알려 주시면 맞춤 플랜을 안내합니다.',inquire:'문의',loadingTitle:'예약 가능한 일정을 불러오는 중',loadingText:'최신 출발 정보를 동기화하고 있습니다.',errorTitle:'일정을 불러올 수 없습니다',errorText:'잠시 후 새로고침해 주세요.',emptyTitle:'예약 가능한 일정이 없습니다',emptyText:'현재 공개된 날짜, 가격 또는 잔여 좌석이 없습니다.',pricePending:'가격 확인 중',perSeat:'1인',seatsLeft:'잔여'},
};

type RoutesCopy={eyebrow:string;title:string;text:string;selected:string;catalogMeta:string;duration:string;walking:string;service:string;roundTrip:string;roundTripText:string;transparent:string;transparentText:string;notices:string;noticesText:string;highlights:string;schedule:string;prep:string;why:string;spots:string;daySchedule:string;scheduleNote:string;book:string;availability:string;notFound:string};
export const passengerRoutesCopy:Record<PassengerLocale,RoutesCopy>={
 'zh-CN':{eyebrow:'精选路线',title:'下一次想去哪里？',text:'浏览路线，并查看正式开放的日期、价格和余位。',selected:'条精选路线',catalogMeta:'每日可订 · 大阪出发 · 多语言游客服务',duration:'行程时长',walking:'步行强度',service:'服务语言',roundTrip:'当天往返',roundTripText:'清楚显示预计结束时间',transparent:'价格透明',transparentText:'下单前核对费用与规则',notices:'集中通知',noticesText:'集合及车辆变更及时送达',highlights:'路线亮点',schedule:'参考行程',prep:'出发准备',why:'这条路线值得去的理由',spots:'沿途会看到什么',daySchedule:'参考行程顺序',scheduleNote:'具体时间会因路况、天气和现场运营情况调整，请以当日通知为准。',book:'选择班次',availability:'查看开放状态',notFound:'未找到行程'},
 'zh-TW':{eyebrow:'精選路線',title:'下一次想去哪裡？',text:'瀏覽路線，並查看正式開放的日期、價格和餘位。',selected:'條精選路線',catalogMeta:'每日可訂 · 大阪出發 · 多語言旅客服務',duration:'行程時間',walking:'步行強度',service:'服務語言',roundTrip:'當天往返',roundTripText:'清楚顯示預計結束時間',transparent:'價格透明',transparentText:'下單前核對費用與規則',notices:'集中通知',noticesText:'集合及車輛變更及時送達',highlights:'路線亮點',schedule:'參考行程',prep:'出發準備',why:'這條路線值得去的理由',spots:'沿途會看到什麼',daySchedule:'參考行程順序',scheduleNote:'具體時間可能因路況、天氣和現場營運調整，請以當日通知為準。',book:'選擇班次',availability:'查看開放狀態',notFound:'找不到行程'},
 ja:{eyebrow:'おすすめツアー',title:'次はどこへ行きますか？',text:'ツアーと、販売中の日程・料金・残席をご確認ください。',selected:'件の厳選ツアー',catalogMeta:'毎日予約可能 · 大阪発 · 多言語旅行者サポート',duration:'所要時間',walking:'歩行レベル',service:'対応言語',roundTrip:'日帰り',roundTripText:'終了予定時刻を明確に表示',transparent:'明瞭な料金',transparentText:'予約前に料金と規定を確認',notices:'一括通知',noticesText:'集合・車両変更をすぐにお知らせ',highlights:'見どころ',schedule:'参考行程',prep:'出発準備',why:'このツアーをおすすめする理由',spots:'訪れるスポット',daySchedule:'参考スケジュール',scheduleNote:'道路・天候・当日の運行状況により変更されます。当日の案内をご確認ください。',book:'便を選択',availability:'販売状況を見る',notFound:'ツアーが見つかりません'},
 en:{eyebrow:'Featured trips',title:'Where will you go next?',text:'Browse routes and check published dates, prices and seats.',selected:'featured trips',catalogMeta:'Daily departures · From Osaka · Multilingual passenger support',duration:'Duration',walking:'Walking level',service:'Service languages',roundTrip:'Day return',roundTripText:'Expected finish time clearly shown',transparent:'Clear pricing',transparentText:'Review fees and rules before booking',notices:'Central updates',noticesText:'Meeting and vehicle changes delivered promptly',highlights:'Highlights',schedule:'Itinerary',prep:'Before you go',why:'Why this trip is worth taking',spots:'What you will see',daySchedule:'Sample itinerary',scheduleNote:'Times may change with traffic, weather and operations. Follow the latest trip notice.',book:'Choose departure',availability:'View availability',notFound:'Trip not found'},
 vi:{eyebrow:'Tuyến nổi bật',title:'Chuyến tới bạn muốn đi đâu?',text:'Xem tuyến cùng ngày, giá và chỗ trống đã công bố.',selected:'tuyến được chọn',catalogMeta:'Có chuyến hằng ngày · Khởi hành Osaka · Hỗ trợ đa ngôn ngữ',duration:'Thời lượng',walking:'Mức độ đi bộ',service:'Ngôn ngữ phục vụ',roundTrip:'Đi về trong ngày',roundTripText:'Hiển thị rõ giờ kết thúc dự kiến',transparent:'Giá minh bạch',transparentText:'Kiểm tra phí và quy định trước khi đặt',notices:'Thông báo tập trung',noticesText:'Nhận nhanh thay đổi điểm tập trung và xe',highlights:'Điểm nổi bật',schedule:'Lịch trình',prep:'Chuẩn bị',why:'Lý do nên chọn chuyến này',spots:'Bạn sẽ thấy gì',daySchedule:'Lịch trình tham khảo',scheduleNote:'Thời gian có thể đổi do giao thông, thời tiết và vận hành. Vui lòng theo thông báo trong ngày.',book:'Chọn chuyến',availability:'Xem tình trạng mở bán',notFound:'Không tìm thấy chuyến'},
 ne:{eyebrow:'छानिएका यात्रा',title:'अर्को पटक कहाँ जाने?',text:'रुट र प्रकाशित मिति, मूल्य तथा सिट हेर्नुहोस्।',selected:'छानिएका यात्रा',catalogMeta:'दैनिक प्रस्थान · ओसाकाबाट · बहुभाषिक यात्री सहयोग',duration:'अवधि',walking:'हिँडाइ स्तर',service:'सेवा भाषा',roundTrip:'एकै दिन फर्कने',roundTripText:'समाप्त हुने अनुमानित समय स्पष्ट',transparent:'स्पष्ट मूल्य',transparentText:'बुकिङअघि शुल्क र नियम जाँच',notices:'एकीकृत सूचना',noticesText:'भेट्ने र गाडी परिवर्तन तुरुन्त प्राप्त',highlights:'मुख्य आकर्षण',schedule:'यात्रा तालिका',prep:'प्रस्थान तयारी',why:'यो यात्रा किन उपयुक्त छ',spots:'बाटोमा के देखिन्छ',daySchedule:'नमुना तालिका',scheduleNote:'ट्राफिक, मौसम र सञ्चालनले समय बदलिन सक्छ। सोही दिनको सूचना पालना गर्नुहोस्।',book:'प्रस्थान छान्नुहोस्',availability:'उपलब्धता हेर्नुहोस्',notFound:'यात्रा भेटिएन'},
 ko:{eyebrow:'추천 여행',title:'다음에는 어디로 떠나실래요?',text:'노선을 둘러보고 공개된 날짜·가격·잔여 좌석을 확인하세요.',selected:'개의 추천 여행',catalogMeta:'매일 예약 가능 · 오사카 출발 · 다국어 여행자 지원',duration:'여행 시간',walking:'도보 강도',service:'지원 언어',roundTrip:'당일 왕복',roundTripText:'예상 종료 시간을 명확히 안내',transparent:'투명한 가격',transparentText:'예약 전 비용과 규정 확인',notices:'통합 알림',noticesText:'집합 및 차량 변경을 신속히 전달',highlights:'여행 포인트',schedule:'일정 안내',prep:'출발 준비',why:'이 여행을 추천하는 이유',spots:'여행 중 만나는 장소',daySchedule:'예상 일정',scheduleNote:'교통, 날씨, 현장 운영에 따라 시간이 변경될 수 있습니다. 당일 안내를 확인해 주세요.',book:'출발편 선택',availability:'예약 가능 여부',notFound:'여행을 찾을 수 없습니다'},
};

type BookingCopy={selectDate:string;next30:string;selectedDate:string;departureTime:string;seatPrice:string;remaining:string;pending:string;people:string;adult:string;child:string;infant:string;seatNote:string;seatText:string;total:string;continue:string;noDepartures:string;noDeparturesText:string;expectedReturn:string;meeting:string;japanTime:string};
export const passengerBookingCopy:Record<PassengerLocale,BookingCopy>={
 'zh-CN':{selectDate:'选择出发日期',next30:'未来30天 · 日本时间',selectedDate:'已选日期',departureTime:'出发时间',seatPrice:'每席价格',remaining:'余位',pending:'待确认',people:'出行人数',adult:'成人座位',child:'儿童座位',infant:'婴儿',seatNote:'座位与车辆说明',seatText:'所有乘客均计入配车人数。车辆根据最终人数统一安排，购买时不指定车型。',total:'合计',continue:'继续填写资料',noDepartures:'该路线暂无开放班次',noDeparturesText:'目前没有已发布的日期、价格或余位。',expectedReturn:'预计返回',meeting:'集合',japanTime:'日本时间'},
 'zh-TW':{selectDate:'選擇出發日期',next30:'未來30天 · 日本時間',selectedDate:'已選日期',departureTime:'出發時間',seatPrice:'每席價格',remaining:'餘位',pending:'待確認',people:'出行人數',adult:'成人座位',child:'兒童座位',infant:'嬰兒',seatNote:'座位與車輛說明',seatText:'所有旅客均計入配車人數。車輛依最終人數統一安排，購買時不指定車型。',total:'合計',continue:'繼續填寫資料',noDepartures:'此路線暫無開放班次',noDeparturesText:'目前沒有已發布的日期、價格或餘位。',expectedReturn:'預計返回',meeting:'集合',japanTime:'日本時間'},
 ja:{selectDate:'出発日を選択',next30:'今後30日 · 日本時間',selectedDate:'選択日',departureTime:'出発時刻',seatPrice:'1席料金',remaining:'残席',pending:'確認中',people:'参加人数',adult:'大人席',child:'子ども席',infant:'乳幼児',seatNote:'座席と車両について',seatText:'すべての参加者を配車人数に含めます。車両は最終人数に応じて手配され、購入時に車種は指定できません。',total:'合計',continue:'乗客情報へ',noDepartures:'販売中の便はありません',noDeparturesText:'現在、公開済みの日程・料金・残席はありません。',expectedReturn:'帰着予定',meeting:'集合',japanTime:'日本時間'},
 en:{selectDate:'Choose departure date',next30:'Next 30 days · Japan time',selectedDate:'Selected date',departureTime:'Departure',seatPrice:'Price per seat',remaining:'Seats left',pending:'Pending',people:'Travellers',adult:'Adult seats',child:'Child seats',infant:'Infants',seatNote:'Seats and vehicle',seatText:'All travellers count toward vehicle capacity. The vehicle is assigned by final group size and cannot be selected at purchase.',total:'Total',continue:'Continue to details',noDepartures:'No departures available',noDeparturesText:'There are no published dates, prices or seats for this trip.',expectedReturn:'Expected return',meeting:'Meeting',japanTime:'Japan time'},
 vi:{selectDate:'Chọn ngày khởi hành',next30:'30 ngày tới · Giờ Nhật Bản',selectedDate:'Ngày đã chọn',departureTime:'Giờ khởi hành',seatPrice:'Giá mỗi ghế',remaining:'Chỗ còn lại',pending:'Đang xác nhận',people:'Số người đi',adult:'Ghế người lớn',child:'Ghế trẻ em',infant:'Em bé',seatNote:'Ghế và phương tiện',seatText:'Tất cả hành khách đều được tính vào sức chứa xe. Xe được bố trí theo tổng số người và không thể chọn loại xe khi mua.',total:'Tổng cộng',continue:'Tiếp tục điền thông tin',noDepartures:'Chưa có chuyến mở bán',noDeparturesText:'Chuyến này chưa có ngày, giá hoặc chỗ trống được công bố.',expectedReturn:'Dự kiến trở về',meeting:'Tập trung',japanTime:'Giờ Nhật Bản'},
 ne:{selectDate:'प्रस्थान मिति छान्नुहोस्',next30:'आगामी ३० दिन · जापान समय',selectedDate:'छानिएको मिति',departureTime:'प्रस्थान समय',seatPrice:'प्रति सिट मूल्य',remaining:'बाँकी सिट',pending:'पुष्टि हुन बाँकी',people:'यात्री संख्या',adult:'वयस्क सिट',child:'बाल सिट',infant:'शिशु',seatNote:'सिट र गाडी',seatText:'सबै यात्री गाडी क्षमतामा गनिन्छन्। अन्तिम संख्याअनुसार गाडी मिलाइन्छ र खरिद गर्दा गाडीको प्रकार छान्न मिल्दैन।',total:'जम्मा',continue:'विवरण भर्नुहोस्',noDepartures:'खुला प्रस्थान छैन',noDeparturesText:'यस यात्राका लागि प्रकाशित मिति, मूल्य वा सिट छैन।',expectedReturn:'फर्कने अनुमान',meeting:'भेट्ने स्थान',japanTime:'जापान समय'},
 ko:{selectDate:'출발일 선택',next30:'향후 30일 · 일본 시간',selectedDate:'선택한 날짜',departureTime:'출발 시간',seatPrice:'1인 가격',remaining:'잔여 좌석',pending:'확인 중',people:'여행 인원',adult:'성인 좌석',child:'어린이 좌석',infant:'유아',seatNote:'좌석 및 차량 안내',seatText:'모든 여행자는 차량 정원에 포함됩니다. 최종 인원에 따라 차량을 배정하며 구매 시 차종을 선택할 수 없습니다.',total:'합계',continue:'승객 정보 입력',noDepartures:'예약 가능한 일정이 없습니다',noDeparturesText:'이 여행에 공개된 날짜, 가격 또는 잔여 좌석이 없습니다.',expectedReturn:'예상 귀착',meeting:'집합',japanTime:'일본 시간'},
};

type PassengerFormCopy={step:string;title:string;text:string;contact:string;contactText:string;name:string;namePlaceholder:string;nationality:string;nationalityPlaceholder:string;language:string;phone:string;phonePlaceholder:string;emergency:string;emergencyPlaceholder:string;assistance:string;assistanceText:string;childNeeds:string;wheelchair:string;otherNeeds:string;extra:string;extraText:string;dietary:string;notes:string;optional:string;review:string;privacy:string};
export const passengerFormCopy:Record<PassengerLocale,PassengerFormCopy>={
 'zh-CN':{step:'第2步，共4步',title:'填写出行联系人',text:'用于发送订单确认和行前集合通知，请填写当天能够联系到的信息。',contact:'主要联系人',contactText:'订单与紧急联络信息',name:'主要乘客姓名',namePlaceholder:'请与旅行证件姓名保持一致',nationality:'国籍',nationalityPlaceholder:'例如：中国、日本',language:'首选沟通语言',phone:'手机号码',phonePlaceholder:'包含国家或地区代码',emergency:'紧急联系人',emergencyPlaceholder:'姓名及联系电话',assistance:'乘车与协助需求',assistanceText:'没有特殊需求时保持默认即可',childNeeds:'儿童乘车需求',wheelchair:'轮椅／行动协助',otherNeeds:'其他配车与集合需求',extra:'补充信息',extraText:'均为选填，请只填写本次行程需要的信息',dietary:'饮食需求',notes:'订单备注',optional:'选填',review:'核对订单',privacy:'继续后仍可返回修改。平台只向本次行程必要的工作人员提供最少履约信息。'},
 'zh-TW':{step:'第2步，共4步',title:'填寫出行聯絡人',text:'用於傳送訂單確認和行前集合通知，請填寫當天可聯絡的資訊。',contact:'主要聯絡人',contactText:'訂單與緊急聯絡資訊',name:'主要旅客姓名',namePlaceholder:'請與旅行證件姓名一致',nationality:'國籍',nationalityPlaceholder:'例如：中國、日本',language:'首選溝通語言',phone:'手機號碼',phonePlaceholder:'包含國家或地區代碼',emergency:'緊急聯絡人',emergencyPlaceholder:'姓名及聯絡電話',assistance:'乘車與協助需求',assistanceText:'沒有特殊需求時維持預設即可',childNeeds:'兒童乘車需求',wheelchair:'輪椅／行動協助',otherNeeds:'其他配車與集合需求',extra:'補充資訊',extraText:'均為選填，請只填寫本次行程需要的資訊',dietary:'飲食需求',notes:'訂單備註',optional:'選填',review:'核對訂單',privacy:'繼續後仍可返回修改。平台只向本次行程必要的工作人員提供最少履約資訊。'},
 ja:{step:'ステップ2／4',title:'旅行代表者情報',text:'予約確認と集合案内に使用します。当日連絡可能な情報をご入力ください。',contact:'代表者',contactText:'予約・緊急連絡先',name:'代表者氏名',namePlaceholder:'旅行証明書と同じ氏名',nationality:'国籍',nationalityPlaceholder:'例：中国、日本',language:'希望連絡言語',phone:'携帯電話番号',phonePlaceholder:'国番号を含めて入力',emergency:'緊急連絡先',emergencyPlaceholder:'氏名と電話番号',assistance:'乗車・サポート希望',assistanceText:'特別な希望がなければ変更不要です',childNeeds:'お子様の乗車希望',wheelchair:'車椅子・移動サポート',otherNeeds:'その他の配車・集合希望',extra:'追加情報',extraText:'任意。本旅行に必要な情報のみ入力してください',dietary:'食事上の希望',notes:'予約メモ',optional:'任意',review:'予約内容を確認',privacy:'後から戻って修正できます。運行に必要な最小限の情報のみ担当者に共有します。'},
 en:{step:'Step 2 of 4',title:'Passenger contact details',text:'Used for order confirmation and pre-trip meeting notices. Enter contact details available on the day.',contact:'Primary contact',contactText:'Order and emergency contact details',name:'Lead passenger name',namePlaceholder:'Use the name on the travel document',nationality:'Nationality',nationalityPlaceholder:'For example: China, Japan',language:'Preferred language',phone:'Mobile number',phonePlaceholder:'Include country or region code',emergency:'Emergency contact',emergencyPlaceholder:'Name and phone number',assistance:'Boarding and assistance needs',assistanceText:'Leave unchanged if no special assistance is needed',childNeeds:'Child travel needs',wheelchair:'Wheelchair / mobility assistance',otherNeeds:'Other vehicle and meeting needs',extra:'Additional information',extraText:'Optional. Only enter information needed for this trip',dietary:'Dietary requirements',notes:'Order notes',optional:'Optional',review:'Review order',privacy:'You can return and edit later. Only the minimum information needed to operate this trip is shared with relevant staff.'},
 vi:{step:'Bước 2/4',title:'Thông tin liên hệ hành khách',text:'Dùng để gửi xác nhận đơn và thông báo tập trung. Hãy nhập thông tin có thể liên lạc trong ngày đi.',contact:'Người liên hệ chính',contactText:'Thông tin đơn và liên hệ khẩn cấp',name:'Tên hành khách chính',namePlaceholder:'Giống tên trên giấy tờ du lịch',nationality:'Quốc tịch',nationalityPlaceholder:'Ví dụ: Việt Nam, Nhật Bản',language:'Ngôn ngữ liên hệ',phone:'Số điện thoại',phonePlaceholder:'Bao gồm mã quốc gia hoặc khu vực',emergency:'Liên hệ khẩn cấp',emergencyPlaceholder:'Tên và số điện thoại',assistance:'Nhu cầu lên xe và hỗ trợ',assistanceText:'Giữ mặc định nếu không có nhu cầu đặc biệt',childNeeds:'Nhu cầu đi xe của trẻ em',wheelchair:'Xe lăn / hỗ trợ di chuyển',otherNeeds:'Nhu cầu xe và tập trung khác',extra:'Thông tin bổ sung',extraText:'Không bắt buộc; chỉ nhập thông tin cần cho chuyến này',dietary:'Yêu cầu ăn uống',notes:'Ghi chú đơn',optional:'Không bắt buộc',review:'Kiểm tra đơn',privacy:'Bạn vẫn có thể quay lại sửa. Chỉ thông tin tối thiểu cần thiết mới được chia sẻ với nhân viên phụ trách.'},
 ne:{step:'चरण २/४',title:'यात्री सम्पर्क विवरण',text:'अर्डर पुष्टि र यात्रा अघि भेट्ने सूचना पठाउन प्रयोग हुन्छ। यात्राको दिन सम्पर्क हुने विवरण लेख्नुहोस्।',contact:'मुख्य सम्पर्क',contactText:'अर्डर र आपतकालीन सम्पर्क',name:'मुख्य यात्रीको नाम',namePlaceholder:'यात्रा कागजातकै नाम लेख्नुहोस्',nationality:'राष्ट्रियता',nationalityPlaceholder:'उदाहरण: नेपाल, जापान',language:'रुचाइएको भाषा',phone:'मोबाइल नम्बर',phonePlaceholder:'देश वा क्षेत्र कोडसहित',emergency:'आपतकालीन सम्पर्क',emergencyPlaceholder:'नाम र फोन नम्बर',assistance:'चढ्ने र सहायता आवश्यकता',assistanceText:'विशेष आवश्यकता नभए परिवर्तन नगर्नुहोस्',childNeeds:'बाल यात्री आवश्यकता',wheelchair:'ह्वीलचेयर / हिँडडुल सहायता',otherNeeds:'अन्य गाडी र भेट्ने आवश्यकता',extra:'थप जानकारी',extraText:'वैकल्पिक; यस यात्राका लागि आवश्यक जानकारी मात्र',dietary:'खानासम्बन्धी आवश्यकता',notes:'अर्डर टिप्पणी',optional:'वैकल्पिक',review:'अर्डर जाँच',privacy:'पछि फर्केर सच्याउन सकिन्छ। आवश्यक कर्मचारीलाई न्यूनतम सञ्चालन जानकारी मात्र दिइन्छ।'},
 ko:{step:'2단계 / 총 4단계',title:'여행자 연락처 입력',text:'예약 확인과 출발 전 집합 안내에 사용합니다. 여행 당일 연락 가능한 정보를 입력해 주세요.',contact:'대표 연락처',contactText:'예약 및 긴급 연락 정보',name:'대표 여행자 이름',namePlaceholder:'여행 서류와 동일한 이름',nationality:'국적',nationalityPlaceholder:'예: 한국, 일본',language:'선호 연락 언어',phone:'휴대전화 번호',phonePlaceholder:'국가 또는 지역 번호 포함',emergency:'긴급 연락처',emergencyPlaceholder:'이름 및 전화번호',assistance:'탑승 및 지원 요청',assistanceText:'특별한 요청이 없으면 기본값을 유지하세요',childNeeds:'어린이 탑승 요청',wheelchair:'휠체어／이동 지원',otherNeeds:'기타 차량 및 집합 요청',extra:'추가 정보',extraText:'선택 사항이며 이번 여행에 필요한 정보만 입력하세요',dietary:'식사 요청',notes:'예약 메모',optional:'선택',review:'예약 내용 확인',privacy:'다음 단계에서도 돌아와 수정할 수 있습니다. 운영에 필요한 최소 정보만 관련 직원에게 제공됩니다.'},
};

type CheckoutCopy={incomplete:string;selectValid:string;selectValidText:string;back:string;step:string;title:string;text:string;tripCost:string;edit:string;trip:string;departure:string;travellers:string;assistance:string;reviewStatus:string;seatPrice:string;total:string;contact:string;name:string;phone:string;language:string;cancel:string;japanTime:string;fullRefund:string;halfRefund:string;noRefund:string;consentCancel:string;consentTerms:string;submit:string};
export const passengerCheckoutCopy:Record<PassengerLocale,CheckoutCopy>={
 'zh-CN':{incomplete:'订单资料不完整',selectValid:'请先选择有效班次',selectValidText:'价格、库存和乘客资料确认后才能进入结账。',back:'返回选择出发班次',step:'第3步，共4步',title:'确认预订信息',text:'请核对出发日期、人数和联系电话。',tripCost:'行程与费用',edit:'修改',trip:'行程',departure:'出发班次',travellers:'成人／儿童／婴儿',assistance:'特殊乘车需求',reviewStatus:'运营审核状态',seatPrice:'每席价格',total:'应付总额',contact:'主要联系人',name:'姓名',phone:'联系电话',language:'沟通语言',cancel:'取消规则',japanTime:'按日本时间计算',fullRefund:'3天前：退还100%',halfRefund:'2～3天：退还50%',noRefund:'前1天起：原则不退',consentCancel:'我已阅读并理解上述取消退款规则',consentTerms:'我同意预订条款及隐私政策',submit:'确认并进入提交页'},
 'zh-TW':{incomplete:'訂單資料不完整',selectValid:'請先選擇有效班次',selectValidText:'價格、庫存和旅客資料確認後才能進入結帳。',back:'返回選擇出發班次',step:'第3步，共4步',title:'確認預訂資訊',text:'請核對出發日期、人數和聯絡電話。',tripCost:'行程與費用',edit:'修改',trip:'行程',departure:'出發班次',travellers:'成人／兒童／嬰兒',assistance:'特殊乘車需求',reviewStatus:'營運審核狀態',seatPrice:'每席價格',total:'應付總額',contact:'主要聯絡人',name:'姓名',phone:'聯絡電話',language:'溝通語言',cancel:'取消規則',japanTime:'按日本時間計算',fullRefund:'3天前：退還100%',halfRefund:'2～3天：退還50%',noRefund:'前1天起：原則不退',consentCancel:'我已閱讀並理解上述取消退款規則',consentTerms:'我同意預訂條款及隱私政策',submit:'確認並進入提交頁'},
 ja:{incomplete:'予約情報が不足しています',selectValid:'有効な便を選択してください',selectValidText:'料金・在庫・乗客情報の確認後に決済へ進めます。',back:'出発便の選択へ戻る',step:'ステップ3／4',title:'予約内容の確認',text:'出発日、人数、電話番号を確認してください。',tripCost:'旅程と料金',edit:'変更',trip:'ツアー',departure:'出発便',travellers:'大人／子ども／乳幼児',assistance:'特別な乗車希望',reviewStatus:'運営確認状況',seatPrice:'1席料金',total:'お支払い総額',contact:'代表連絡先',name:'氏名',phone:'電話番号',language:'連絡言語',cancel:'取消規定',japanTime:'日本時間で計算',fullRefund:'3日前まで：100%返金',halfRefund:'2～3日前：50%返金',noRefund:'前日以降：原則返金なし',consentCancel:'上記の取消・返金規定を確認しました',consentTerms:'予約規約とプライバシーポリシーに同意します',submit:'確認して次へ'},
 en:{incomplete:'Order details incomplete',selectValid:'Select a valid departure',selectValidText:'Price, inventory and passenger details must be confirmed before checkout.',back:'Back to departures',step:'Step 3 of 4',title:'Review your booking',text:'Check the departure date, party size and contact number.',tripCost:'Trip and price',edit:'Edit',trip:'Trip',departure:'Departure',travellers:'Adults / Children / Infants',assistance:'Special travel needs',reviewStatus:'Operations review',seatPrice:'Price per seat',total:'Amount due',contact:'Primary contact',name:'Name',phone:'Phone',language:'Contact language',cancel:'Cancellation policy',japanTime:'Calculated in Japan time',fullRefund:'3+ days before: 100% refund',halfRefund:'2–3 days before: 50% refund',noRefund:'From 1 day before: generally non-refundable',consentCancel:'I have read and understand the cancellation and refund policy',consentTerms:'I agree to the booking terms and privacy policy',submit:'Confirm and continue'},
 vi:{incomplete:'Thông tin đơn chưa đầy đủ',selectValid:'Hãy chọn chuyến hợp lệ',selectValidText:'Cần xác nhận giá, chỗ trống và thông tin hành khách trước khi thanh toán.',back:'Quay lại chọn chuyến',step:'Bước 3/4',title:'Xác nhận thông tin đặt chỗ',text:'Hãy kiểm tra ngày đi, số người và số liên hệ.',tripCost:'Hành trình và chi phí',edit:'Sửa',trip:'Chuyến đi',departure:'Chuyến khởi hành',travellers:'Người lớn / Trẻ em / Em bé',assistance:'Nhu cầu hỗ trợ đặc biệt',reviewStatus:'Trạng thái duyệt',seatPrice:'Giá mỗi ghế',total:'Tổng cần trả',contact:'Liên hệ chính',name:'Tên',phone:'Điện thoại',language:'Ngôn ngữ liên hệ',cancel:'Quy định hủy',japanTime:'Tính theo giờ Nhật Bản',fullRefund:'Trước 3 ngày: hoàn 100%',halfRefund:'Trước 2–3 ngày: hoàn 50%',noRefund:'Từ 1 ngày trước: thông thường không hoàn',consentCancel:'Tôi đã đọc và hiểu quy định hủy và hoàn tiền',consentTerms:'Tôi đồng ý điều khoản đặt chỗ và chính sách riêng tư',submit:'Xác nhận và tiếp tục'},
 ne:{incomplete:'अर्डर विवरण अपूर्ण',selectValid:'मान्य प्रस्थान छान्नुहोस्',selectValidText:'चेकआउट अघि मूल्य, सिट र यात्री विवरण पुष्टि हुनुपर्छ।',back:'प्रस्थान चयनमा फर्कनुहोस्',step:'चरण ३/४',title:'बुकिङ विवरण जाँच',text:'प्रस्थान मिति, यात्री संख्या र फोन जाँच गर्नुहोस्।',tripCost:'यात्रा र मूल्य',edit:'सच्याउनुहोस्',trip:'यात्रा',departure:'प्रस्थान',travellers:'वयस्क / बाल / शिशु',assistance:'विशेष यात्रा आवश्यकता',reviewStatus:'सञ्चालन समीक्षा',seatPrice:'प्रति सिट मूल्य',total:'तिर्नुपर्ने जम्मा',contact:'मुख्य सम्पर्क',name:'नाम',phone:'फोन',language:'सम्पर्क भाषा',cancel:'रद्द नीति',japanTime:'जापान समयअनुसार',fullRefund:'३ दिनअघि: १००% फिर्ता',halfRefund:'२–३ दिनअघि: ५०% फिर्ता',noRefund:'१ दिनअघिबाट: सामान्यतया फिर्ता हुँदैन',consentCancel:'मैले रद्द र फिर्ता नीति पढेर बुझेको छु',consentTerms:'म बुकिङ सर्त र गोपनीयता नीतिमा सहमत छु',submit:'पुष्टि गरी अघि बढ्नुहोस्'},
 ko:{incomplete:'예약 정보가 완전하지 않습니다',selectValid:'유효한 출발편을 선택해 주세요',selectValidText:'가격, 좌석 및 승객 정보가 확인되어야 결제로 진행할 수 있습니다.',back:'출발편 선택으로 돌아가기',step:'3단계 / 총 4단계',title:'예약 정보 확인',text:'출발일, 인원과 연락처를 확인해 주세요.',tripCost:'여행 및 요금',edit:'수정',trip:'여행',departure:'출발편',travellers:'성인 / 어린이 / 유아',assistance:'특별 탑승 요청',reviewStatus:'운영 확인 상태',seatPrice:'1인 가격',total:'결제 예정 금액',contact:'대표 연락처',name:'이름',phone:'전화번호',language:'연락 언어',cancel:'취소 규정',japanTime:'일본 시간 기준',fullRefund:'3일 전: 100% 환불',halfRefund:'2~3일 전: 50% 환불',noRefund:'1일 전부터: 원칙적으로 환불 불가',consentCancel:'위 취소 및 환불 규정을 읽고 이해했습니다',consentTerms:'예약 약관 및 개인정보 처리방침에 동의합니다',submit:'확인 후 다음 단계'},
};
