import type {PassengerLocale} from './passengerLocale';

type PaymentState='paid'|'review'|'refunded'|'cancelled'|'pending'|'confirming';
type StateText={title:string;description:string;label:string};
type PaymentCopy={eyebrow:string;orderNumber:string;orderStatus:string;due:string;viewOrder:string;states:Record<PaymentState,StateText>};

export const passengerPaymentCopy:Record<PassengerLocale,PaymentCopy>={
 'zh-CN':{eyebrow:'支付状态',orderNumber:'订单编号',orderStatus:'订单状态',due:'转账付款期限（日本时间）',viewOrder:'查看我的订单',states:{paid:{title:'支付成功',description:'订单已支付，并已加入“我的账户／我的行程”。',label:'已支付'},review:{title:'付款需要人工确认',description:'付款结果已收到，但库存或状态需要工作人员核对；请勿重复付款。',label:'人工核对中'},refunded:{title:'退款已发起',description:'退款已原路发起，实际到账时间以银行或发卡机构为准。',label:'退款处理中'},cancelled:{title:'订单未完成',description:'本次订单未完成，不会作为已付款行程。',label:'未完成'},pending:{title:'等待付款确认',description:'付款申请已记录，正在等待确认；请勿重复付款。',label:'待确认'},confirming:{title:'正在确认订单',description:'正在等待服务端确认支付结果；请勿重复付款。',label:'确认中'}}},
 'zh-TW':{eyebrow:'付款狀態',orderNumber:'訂單編號',orderStatus:'訂單狀態',due:'轉帳付款期限（日本時間）',viewOrder:'查看我的訂單',states:{paid:{title:'付款成功',description:'訂單已付款，並已加入「我的帳戶／我的行程」。',label:'已付款'},review:{title:'付款需要人工確認',description:'已收到付款結果，但庫存或狀態需要工作人員核對；請勿重複付款。',label:'人工核對中'},refunded:{title:'退款已發起',description:'退款已按原路發起，實際到帳時間以銀行或發卡機構為準。',label:'退款處理中'},cancelled:{title:'訂單未完成',description:'本次訂單未完成，不會作為已付款行程。',label:'未完成'},pending:{title:'等待付款確認',description:'付款申請已記錄並等待確認；請勿重複付款。',label:'待確認'},confirming:{title:'正在確認訂單',description:'正在等待伺服器確認付款結果；請勿重複付款。',label:'確認中'}}},
 ja:{eyebrow:'支払い状況',orderNumber:'注文番号',orderStatus:'注文状況',due:'振込期限（日本時間）',viewOrder:'注文を見る',states:{paid:{title:'支払い完了',description:'お支払いが完了し、マイページと旅程に追加されました。',label:'支払い済み'},review:{title:'支払いを確認中',description:'支払い結果を受信しましたが、在庫または状態の確認が必要です。重複して支払わないでください。',label:'スタッフ確認中'},refunded:{title:'返金手続き開始',description:'元の支払い方法へ返金を開始しました。入金日は銀行またはカード会社により異なります。',label:'返金処理中'},cancelled:{title:'注文未完了',description:'この注文は完了しておらず、支払い済みの旅程には含まれません。',label:'未完了'},pending:{title:'支払い確認待ち',description:'支払い申請を記録しました。確認まで重複して支払わないでください。',label:'確認待ち'},confirming:{title:'注文を確認中',description:'サーバーで支払い結果を確認しています。重複して支払わないでください。',label:'確認中'}}},
 en:{eyebrow:'Payment status',orderNumber:'Order number',orderStatus:'Order status',due:'Bank transfer deadline (Japan time)',viewOrder:'View my order',states:{paid:{title:'Payment successful',description:'Your order is paid and has been added to your account and trip.',label:'Paid'},review:{title:'Payment needs review',description:'We received the payment result, but staff must verify inventory or status. Do not pay again.',label:'Under review'},refunded:{title:'Refund initiated',description:'The refund has been sent to the original payment method. Arrival time depends on your bank or card issuer.',label:'Refund processing'},cancelled:{title:'Order not completed',description:'This order was not completed and will not appear as a paid trip.',label:'Not completed'},pending:{title:'Waiting for payment confirmation',description:'Your payment request was recorded and is awaiting confirmation. Do not pay again.',label:'Pending'},confirming:{title:'Confirming your order',description:'The server is confirming the payment result. Do not pay again.',label:'Confirming'}}},
 vi:{eyebrow:'Trạng thái thanh toán',orderNumber:'Mã đơn',orderStatus:'Trạng thái đơn',due:'Hạn chuyển khoản (giờ Nhật Bản)',viewOrder:'Xem đơn của tôi',states:{paid:{title:'Thanh toán thành công',description:'Đơn đã được thanh toán và thêm vào tài khoản cùng lịch trình của bạn.',label:'Đã thanh toán'},review:{title:'Thanh toán cần kiểm tra',description:'Đã nhận kết quả thanh toán nhưng nhân viên cần kiểm tra chỗ hoặc trạng thái. Không thanh toán lại.',label:'Đang kiểm tra'},refunded:{title:'Đã bắt đầu hoàn tiền',description:'Tiền hoàn đã được gửi về phương thức ban đầu. Thời gian nhận tùy ngân hàng hoặc đơn vị phát hành thẻ.',label:'Đang hoàn tiền'},cancelled:{title:'Đơn chưa hoàn tất',description:'Đơn này chưa hoàn tất và không được tính là chuyến đã thanh toán.',label:'Chưa hoàn tất'},pending:{title:'Chờ xác nhận thanh toán',description:'Yêu cầu thanh toán đã được ghi nhận và đang chờ xác nhận. Không thanh toán lại.',label:'Chờ xác nhận'},confirming:{title:'Đang xác nhận đơn',description:'Máy chủ đang xác nhận kết quả thanh toán. Không thanh toán lại.',label:'Đang xác nhận'}}},
 ne:{eyebrow:'भुक्तानी स्थिति',orderNumber:'अर्डर नम्बर',orderStatus:'अर्डर स्थिति',due:'बैंक ट्रान्सफर समयसीमा (जापान समय)',viewOrder:'मेरो अर्डर हेर्नुहोस्',states:{paid:{title:'भुक्तानी सफल',description:'अर्डर भुक्तानी भयो र तपाईंको खाता तथा यात्रामा थपियो।',label:'भुक्तानी भयो'},review:{title:'भुक्तानी समीक्षा आवश्यक',description:'भुक्तानी नतिजा प्राप्त भयो तर सिट वा स्थिति कर्मचारीले जाँच्नुपर्छ। फेरि नतिर्नुहोस्।',label:'समीक्षामा'},refunded:{title:'रकम फिर्ता सुरु',description:'मूल भुक्तानी माध्यममा फिर्ता पठाइएको छ। बैंक वा कार्ड जारीकर्ताअनुसार समय लाग्न सक्छ।',label:'फिर्ता प्रक्रियामा'},cancelled:{title:'अर्डर पूरा भएन',description:'यो अर्डर पूरा भएन र भुक्तानी भएको यात्राका रूपमा देखिँदैन।',label:'अपूर्ण'},pending:{title:'भुक्तानी पुष्टि प्रतीक्षा',description:'भुक्तानी अनुरोध सुरक्षित भयो र पुष्टि पर्खँदैछ। फेरि नतिर्नुहोस्।',label:'प्रतीक्षामा'},confirming:{title:'अर्डर पुष्टि हुँदैछ',description:'सर्भरले भुक्तानी नतिजा पुष्टि गर्दैछ। फेरि नतिर्नुहोस्।',label:'पुष्टि हुँदैछ'}}},
 ko:{eyebrow:'결제 상태',orderNumber:'예약 번호',orderStatus:'예약 상태',due:'계좌이체 기한(일본 시간)',viewOrder:'내 예약 보기',states:{paid:{title:'결제 완료',description:'결제가 완료되어 내 계정과 여행 일정에 추가되었습니다.',label:'결제 완료'},review:{title:'결제 확인 필요',description:'결제 결과를 받았지만 좌석 또는 상태를 직원이 확인해야 합니다. 다시 결제하지 마세요.',label:'직원 확인 중'},refunded:{title:'환불 시작',description:'원래 결제 수단으로 환불을 시작했습니다. 실제 입금 시점은 은행 또는 카드사에 따라 다릅니다.',label:'환불 처리 중'},cancelled:{title:'예약 미완료',description:'이 예약은 완료되지 않았으며 결제된 여행으로 처리되지 않습니다.',label:'미완료'},pending:{title:'결제 확인 대기',description:'결제 요청이 기록되어 확인을 기다리고 있습니다. 다시 결제하지 마세요.',label:'확인 대기'},confirming:{title:'예약 확인 중',description:'서버에서 결제 결과를 확인하고 있습니다. 다시 결제하지 마세요.',label:'확인 중'}}}
};

export function paymentState(status:string|undefined,manual=false):PaymentState{
  if(status==='paid'||status==='confirmed')return 'paid';
  if(status==='payment_review')return 'review';
  if(status==='refunded')return 'refunded';
  if(status==='cancelled'||status==='expired')return 'cancelled';
  if(manual||status==='pending_manual_review'||status==='pending_payment')return 'pending';
  return 'confirming';
}
