/* Auto-generated small index. It intentionally excludes guide bodies. */
export const attractionGuideLocales=[
  "zh-CN",
  "ja",
  "en",
  "ko",
  "vi",
  "ne",
  "es"
] as const;
export type AttractionGuideLocale=typeof attractionGuideLocales[number];
export const attractionGuideTitleAliases={
  "zh-CN": {
    "天桥立": "amanohashidate",
    "岚山竹林・天龙寺区域": "arashiyama-bamboo-tenryu-ji",
    "岚山・渡月桥": "arashiyama-togetsukyo",
    "有马温泉": "arima-onsen",
    "Biwako Valley / 琵琶湖": "biwako-valley-lake-biwa",
    "宇治平等院・凤凰堂": "byodoin-phoenix-hall",
    "智恩寺文殊堂": "chion-ji-monju-do",
    "伏见稻荷大社": "fushimi-inari-taisha",
    "伊根舟屋": "ine-funaya",
    "胜尾寺": "katsuo-ji",
    "贵船神社": "kifune-shrine",
    "金阁寺": "kinkaku-ji",
    "贵志站・猫站长・特色电车": "kishi-station-cat-theme-trains",
    "北野异人馆街": "kitano-ijinkan",
    "清水寺": "kiyomizu-dera",
    "神户港 / Harborland": "kobe-harbor-harborland",
    "La Collina 近江八幡": "la-collina-omihachiman",
    "六甲山夜景": "mount-rokko-night-view",
    "奈良公园": "nara-park",
    "二年坂・三年坂": "ninenzaka-sannenzaka",
    "爱宕念佛寺": "otagi-nenbutsu-ji",
    "三段壁": "sandanbeki",
    "三千院": "sanzen-in",
    "千畳敷": "senjojiki",
    "白须神社": "shirahige-shrine",
    "源氏物语博物馆・宇治十帖": "tale-of-genji-uji-chapters",
    "Toretore 市场": "toretore-market",
    "Toretore 温泉": "toretore-onsen",
    "宇治源氏之汤": "uji-genji-no-yu",
    "宇治茶": "uji-tea"
  },
  "ja": {
    "天橋立": "amanohashidate",
    "嵐山竹林・天龍寺エリア": "arashiyama-bamboo-tenryu-ji",
    "嵐山・渡月橋": "arashiyama-togetsukyo",
    "有馬温泉": "arima-onsen",
    "びわ湖バレイ・琵琶湖": "biwako-valley-lake-biwa",
    "宇治平等院・鳳凰堂": "byodoin-phoenix-hall",
    "智恩寺文殊堂": "chion-ji-monju-do",
    "伏見稲荷大社": "fushimi-inari-taisha",
    "伊根の舟屋": "ine-funaya",
    "勝尾寺": "katsuo-ji",
    "貴船神社": "kifune-shrine",
    "金閣寺": "kinkaku-ji",
    "貴志駅・猫駅長・特色電車": "kishi-station-cat-theme-trains",
    "北野異人館街": "kitano-ijinkan",
    "清水寺": "kiyomizu-dera",
    "神戸港・ハーバーランド": "kobe-harbor-harborland",
    "ラ コリーナ近江八幡": "la-collina-omihachiman",
    "六甲山の夜景": "mount-rokko-night-view",
    "奈良公園": "nara-park",
    "二年坂・三年坂": "ninenzaka-sannenzaka",
    "愛宕念仏寺": "otagi-nenbutsu-ji",
    "三段壁": "sandanbeki",
    "三千院": "sanzen-in",
    "千畳敷": "senjojiki",
    "白鬚神社": "shirahige-shrine",
    "源氏物語ミュージアム・宇治十帖": "tale-of-genji-uji-chapters",
    "とれとれ市場": "toretore-market",
    "とれとれの湯": "toretore-onsen",
    "宇治源氏の湯": "uji-genji-no-yu",
    "宇治茶": "uji-tea"
  },
  "en": {
    "Amanohashidate": "amanohashidate",
    "Arashiyama Bamboo Grove and Tenryu-ji Area": "arashiyama-bamboo-tenryu-ji",
    "Arashiyama and Togetsukyo Bridge": "arashiyama-togetsukyo",
    "Arima Onsen": "arima-onsen",
    "Biwako Valley and Lake Biwa": "biwako-valley-lake-biwa",
    "Byodo-in Phoenix Hall": "byodoin-phoenix-hall",
    "Chion-ji Monju-do": "chion-ji-monju-do",
    "Fushimi Inari Taisha": "fushimi-inari-taisha",
    "Ine Funaya": "ine-funaya",
    "Katsuo-ji": "katsuo-ji",
    "Kifune Shrine": "kifune-shrine",
    "Kinkaku-ji": "kinkaku-ji",
    "Kishi Station, Cat Stationmaster, and Theme Trains": "kishi-station-cat-theme-trains",
    "Kitano Ijinkan District": "kitano-ijinkan",
    "Kiyomizu-dera": "kiyomizu-dera",
    "Kobe Harbor and Harborland": "kobe-harbor-harborland",
    "La Collina Omihachiman": "la-collina-omihachiman",
    "Mount Rokko Night View": "mount-rokko-night-view",
    "Nara Park": "nara-park",
    "Ninenzaka and Sannenzaka": "ninenzaka-sannenzaka",
    "Otagi Nenbutsu-ji": "otagi-nenbutsu-ji",
    "Sandanbeki": "sandanbeki",
    "Sanzen-in": "sanzen-in",
    "Senjojiki": "senjojiki",
    "Shirahige Shrine": "shirahige-shrine",
    "The Tale of Genji Museum and the Uji Chapters": "tale-of-genji-uji-chapters",
    "Toretore Market": "toretore-market",
    "Toretore Onsen": "toretore-onsen",
    "Uji Genji-no-Yu": "uji-genji-no-yu",
    "Uji Tea": "uji-tea"
  },
  "ko": {
    "아마노하시다테": "amanohashidate",
    "아라시야마 대나무숲・덴류지 일대": "arashiyama-bamboo-tenryu-ji",
    "아라시야마・도게쓰교": "arashiyama-togetsukyo",
    "아리마 온천": "arima-onsen",
    "비와코 밸리・비와호": "biwako-valley-lake-biwa",
    "우지 뵤도인・봉황당": "byodoin-phoenix-hall",
    "지온지 문수당": "chion-ji-monju-do",
    "후시미이나리타이샤": "fushimi-inari-taisha",
    "이네 후나야": "ine-funaya",
    "가쓰오지": "katsuo-ji",
    "기후네 신사": "kifune-shrine",
    "긴카쿠지": "kinkaku-ji",
    "기시역・고양이 역장・테마 열차": "kishi-station-cat-theme-trains",
    "기타노 이진칸 거리": "kitano-ijinkan",
    "기요미즈데라": "kiyomizu-dera",
    "고베항・하버랜드": "kobe-harbor-harborland",
    "라 콜리나 오미하치만": "la-collina-omihachiman",
    "롯코산 야경": "mount-rokko-night-view",
    "나라공원": "nara-park",
    "니넨자카・산넨자카": "ninenzaka-sannenzaka",
    "오타기 넨부쓰지": "otagi-nenbutsu-ji",
    "산단베키": "sandanbeki",
    "산젠인": "sanzen-in",
    "센조지키": "senjojiki",
    "시라히게 신사": "shirahige-shrine",
    "겐지모노가타리 뮤지엄・우지십첩": "tale-of-genji-uji-chapters",
    "토레토레 시장": "toretore-market",
    "토레토레 온천": "toretore-onsen",
    "우지 겐지노유": "uji-genji-no-yu",
    "우지차": "uji-tea"
  },
  "vi": {
    "Amanohashidate": "amanohashidate",
    "Rừng tre Arashiyama・khu Tenryu-ji": "arashiyama-bamboo-tenryu-ji",
    "Arashiyama・Cầu Togetsukyo": "arashiyama-togetsukyo",
    "Arima Onsen": "arima-onsen",
    "Biwako Valley và hồ Biwa": "biwako-valley-lake-biwa",
    "Byodo-in・Phoenix Hall": "byodoin-phoenix-hall",
    "Chion-ji Monju-do": "chion-ji-monju-do",
    "Fushimi Inari Taisha": "fushimi-inari-taisha",
    "Nhà thuyền Ine": "ine-funaya",
    "Katsuo-ji": "katsuo-ji",
    "Đền Kifune": "kifune-shrine",
    "Kinkaku-ji – Chùa Vàng": "kinkaku-ji",
    "Ga Kishi, mèo trưởng ga và tàu chủ đề": "kishi-station-cat-theme-trains",
    "Khu Kitano Ijinkan": "kitano-ijinkan",
    "Chùa Kiyomizu-dera": "kiyomizu-dera",
    "Cảng Kobe・Harborland": "kobe-harbor-harborland",
    "La Collina Omihachiman": "la-collina-omihachiman",
    "Cảnh đêm núi Rokko": "mount-rokko-night-view",
    "Công viên Nara": "nara-park",
    "Ninenzaka và Sannenzaka": "ninenzaka-sannenzaka",
    "Otagi Nenbutsu-ji": "otagi-nenbutsu-ji",
    "Sandanbeki": "sandanbeki",
    "Sanzen-in": "sanzen-in",
    "Senjojiki": "senjojiki",
    "Đền Shirahige": "shirahige-shrine",
    "Bảo tàng Genji Monogatari・Uji Jujo": "tale-of-genji-uji-chapters",
    "Chợ Toretore": "toretore-market",
    "Toretore Onsen": "toretore-onsen",
    "Uji Genji-no-Yu": "uji-genji-no-yu",
    "Trà Uji": "uji-tea"
  },
  "ne": {
    "अमानोहोशिदाते": "amanohashidate",
    "अराशियामा बाँस वन・तेनर्युजी क्षेत्र": "arashiyama-bamboo-tenryu-ji",
    "अराशियामा・तोगेत्सुक्यो": "arashiyama-togetsukyo",
    "अरिमा ओन्सेन": "arima-onsen",
    "बिवाको भ्याली・बिवा ताल": "biwako-valley-lake-biwa",
    "ब्योदोइन・फिनिक्स हल": "byodoin-phoenix-hall",
    "चिओनजी मोन्जुदो": "chion-ji-monju-do",
    "फुशिमी इनारी ताइशा": "fushimi-inari-taisha",
    "इने फुनाया": "ine-funaya",
    "कात्सुओजी": "katsuo-ji",
    "किफुने श्राइन": "kifune-shrine",
    "किन्काकुजी": "kinkaku-ji",
    "किशी स्टेशन・बिरालो स्टेशन मास्टर・थिम ट्रेन": "kishi-station-cat-theme-trains",
    "कितानो इजिनकान क्षेत्र": "kitano-ijinkan",
    "कियोमिजुदेरा": "kiyomizu-dera",
    "कोबे हार्बर・हार्बरल्यान्ड": "kobe-harbor-harborland",
    "ला कोलिना ओमिहाचिमान": "la-collina-omihachiman",
    "रोक्को पहाडको रात्री दृश्य": "mount-rokko-night-view",
    "नारा पार्क": "nara-park",
    "निनेनजाका・साननेनजाका": "ninenzaka-sannenzaka",
    "ओतागी नेन्बुत्सुजी": "otagi-nenbutsu-ji",
    "सानदानबेकी": "sandanbeki",
    "सानजेनइन": "sanzen-in",
    "सेन्जोजिकी": "senjojiki",
    "शिराहिगे श्राइन": "shirahige-shrine",
    "गेन्जी मोनोगातारी संग्रहालय・उजी दस अध्याय": "tale-of-genji-uji-chapters",
    "तोरेतोरे बजार": "toretore-market",
    "तोरेतोरे ओन्सेन": "toretore-onsen",
    "उजी गेन्जी नो यु": "uji-genji-no-yu",
    "उजी चिया": "uji-tea"
  },
  "es": {
    "Amanohashidate": "amanohashidate",
    "Bosque de bambú de Arashiyama y zona de Tenryu-ji": "arashiyama-bamboo-tenryu-ji",
    "Arashiyama y puente Togetsukyo": "arashiyama-togetsukyo",
    "Arima Onsen": "arima-onsen",
    "Biwako Valley y lago Biwa": "biwako-valley-lake-biwa",
    "Byodo-in・Phoenix Hall": "byodoin-phoenix-hall",
    "Chion-ji Monju-do": "chion-ji-monju-do",
    "Fushimi Inari Taisha": "fushimi-inari-taisha",
    "Casas-barco de Ine": "ine-funaya",
    "Katsuo-ji": "katsuo-ji",
    "Santuario Kifune": "kifune-shrine",
    "Kinkaku-ji": "kinkaku-ji",
    "Estación Kishi, el gato jefe de estación y los trenes temáticos": "kishi-station-cat-theme-trains",
    "Barrio Kitano Ijinkan": "kitano-ijinkan",
    "Kiyomizu-dera": "kiyomizu-dera",
    "Puerto de Kobe y Harborland": "kobe-harbor-harborland",
    "La Collina Omihachiman": "la-collina-omihachiman",
    "Vista nocturna del monte Rokko": "mount-rokko-night-view",
    "Parque de Nara": "nara-park",
    "Ninenzaka y Sannenzaka": "ninenzaka-sannenzaka",
    "Otagi Nenbutsu-ji": "otagi-nenbutsu-ji",
    "Sandanbeki": "sandanbeki",
    "Sanzen-in": "sanzen-in",
    "Senjojiki": "senjojiki",
    "Santuario Shirahige": "shirahige-shrine",
    "Museo de Genji y los Diez Capítulos de Uji": "tale-of-genji-uji-chapters",
    "Mercado Toretore": "toretore-market",
    "Toretore Onsen": "toretore-onsen",
    "Uji Genji-no-Yu": "uji-genji-no-yu",
    "Té de Uji": "uji-tea"
  }
} as Record<AttractionGuideLocale,Record<string,string>>;
