export type DomainOrderStatus='pending_payment'|'paid'|'cancelled'|'expired'|'refunded'|'payment_review';
type Hold={orderId:string;accountId:string;departureId:string;seats:number;key:string;expiresAt:number;status:'held'|'committed'|'released'|'expired'};
type DomainOrder={id:string;accountId:string;departureId:string;seats:number;key:string;status:DomainOrderStatus;latestEventAt:number};
export class CommerceDomain{
  private serial:Promise<void>=Promise.resolve();private holds:Hold[]=[];private orders:DomainOrder[]=[];private events=new Set<string>();
  constructor(private readonly capacity:number){}
  private async transaction<T>(work:()=>T|Promise<T>){const previous=this.serial;let release=()=>{};this.serial=new Promise<void>(resolve=>{release=resolve});await previous;try{return await work()}finally{release()}}
  reserve(input:{accountId:string;departureId:string;seats:number;key:string;expiresAt:number},now:number){return this.transaction(()=>{const existing=this.orders.find(x=>x.accountId===input.accountId&&x.key===input.key);if(existing){const hold=this.holds.find(x=>x.orderId===existing.id)!;if(existing.departureId!==input.departureId||existing.seats!==input.seats)throw new Error('idempotency parameter mismatch');if(existing.status!=='pending_payment'||hold.status!=='held'||hold.expiresAt<=now)throw new Error('idempotency request no longer active');return existing}for(const hold of this.holds)if(hold.status==='held'&&hold.expiresAt<=now){hold.status='expired';this.orders.find(x=>x.id===hold.orderId)!.status='expired'}const used=this.holds.filter(x=>x.departureId===input.departureId&&(x.status==='held'||x.status==='committed')).reduce((n,x)=>n+x.seats,0);if(used+input.seats>this.capacity)throw new Error('insufficient inventory');const order={id:`order-${this.orders.length+1}`,...input,status:'pending_payment' as const,latestEventAt:0};this.orders.push(order);this.holds.push({orderId:order.id,...input,status:'held'});return order})}
  cancel(orderId:string,accountId:string,now:number){return this.transaction(()=>{const order=this.orders.find(x=>x.id===orderId&&x.accountId===accountId);if(!order||order.status!=='pending_payment')return false;order.status='cancelled';order.latestEventAt=now;const hold=this.holds.find(x=>x.orderId===orderId);if(hold?.status==='held')hold.status='released';return true})}
  payment(input:{eventId:string;orderId:string;status:'succeeded'|'failed'|'cancelled'|'refunded';eventAt:number},now:number){return this.transaction(()=>{if(this.events.has(input.eventId))return 'duplicate';this.events.add(input.eventId);const order=this.orders.find(x=>x.id===input.orderId);if(!order)throw new Error('order not found');if(input.eventAt<order.latestEventAt)return 'ignored-out-of-order';order.latestEventAt=input.eventAt;const hold=this.holds.find(x=>x.orderId===order.id)!;if(input.status==='succeeded'){if(hold.status==='held'&&hold.expiresAt>now){hold.status='committed';order.status='paid';return 'paid'}order.status='payment_review';return 'payment-review'}if(input.status==='refunded'&&(order.status==='paid'||order.status==='payment_review')){order.status='refunded';return 'refunded'}return 'recorded'})}
  snapshot(orderId:string){const order=this.orders.find(x=>x.id===orderId);const hold=this.holds.find(x=>x.orderId===orderId);return structuredClone({order,hold})}
}

export type AccessRole='owner'|'operations'|'assigned_staff'|'group_passenger'|'anonymous';
export const visibleAssistanceFields=(role:AccessRole)=>role==='owner'||role==='operations'?['privatePayload','staffProjection']:role==='assigned_staff'?['staffProjection']:[];
export const canReceiveVehicleGroup=(role:AccessRole)=>role==='owner'||role==='operations'||role==='assigned_staff'||role==='group_passenger';
export const canSendVehicleGroupChat=(role:AccessRole,roomStatus:'frozen'|'open'|'closed')=>roomStatus==='open'&&canReceiveVehicleGroup(role);
