import {createServer,type ServerResponse} from 'node:http';
import {CheckoutEndpoint} from './api/checkout.js';
import {createSupabaseServerClient,SupabaseAccessTokenVerifier,SupabaseManualPaymentGateway,SupabaseOrderInventoryGateway,SupabasePaymentEventStore,SupabasePaymentIntentRecorder,SupabaseServerPricingGateway} from './supabase.js';
import {StripeCardPaymentSessionGateway,StripeTestAdapter} from './stripe.js';
import {allowedCorsOrigin,parseAllowedOrigins} from './cors.js';
import {SupabaseBoardingGateway} from './boarding.js';
import {checkTestApiReadiness} from './readiness.js';
import {GoogleCloudTranslationProvider,isTranslationTarget,SupabaseMessageTranslationGateway,translateVehicleMessage} from './translation.js';
import {apiSecurityHeaders,FixedWindowRateLimiter,readRequestBody,RequestBodyTooLargeError,requestRateKey,sendRateLimit} from './security.js';
import {SignedNotificationReceiptHandler,SupabaseNotificationReceiptStore} from './notifications.js';

const port=Number(process.env.PORT||8787);const allowedOrigins=parseAllowedOrigins(process.env.ALLOWED_ORIGIN||'');
const supabase=createSupabaseServerClient({url:process.env.SUPABASE_URL||'',serviceRoleKey:process.env.SUPABASE_SERVICE_ROLE_KEY||''});
const stripe=new StripeTestAdapter({secretKey:process.env.STRIPE_SECRET_KEY||'',webhookSecret:process.env.STRIPE_WEBHOOK_SECRET||''});
const checkout=new CheckoutEndpoint(new SupabaseAccessTokenVerifier(supabase),new SupabaseOrderInventoryGateway(supabase),new StripeCardPaymentSessionGateway(stripe,new SupabasePaymentIntentRecorder(supabase)),new SupabaseManualPaymentGateway(supabase),new SupabaseServerPricingGateway(supabase));
const events=new SupabasePaymentEventStore(supabase);
const boarding=new SupabaseBoardingGateway(supabase);const sessions=new SupabaseAccessTokenVerifier(supabase);
const translations=new SupabaseMessageTranslationGateway(supabase);const translationProvider=new GoogleCloudTranslationProvider(process.env.GOOGLE_TRANSLATION_API_KEY,process.env.JTW_TRANSLATION_ENABLED==='true');
const notificationReceipts=new SignedNotificationReceiptHandler(process.env.NOTIFICATION_WEBHOOK_SECRET||'',new SupabaseNotificationReceiptStore(supabase));
const checkoutRate=new FixedWindowRateLimiter(30,60_000);const actionRate=new FixedWindowRateLimiter(60,60_000);

function send(res:ServerResponse,status:number,body:unknown,corsOrigin:string|null=null,headers:Record<string,string>={}){res.writeHead(status,{...apiSecurityHeaders,'content-type':'application/json; charset=utf-8','cache-control':'no-store',...(corsOrigin?{'access-control-allow-origin':corsOrigin,'vary':'Origin'}:{}),...headers});res.end(JSON.stringify(body))}
const server=createServer(async(req,res)=>{const corsOrigin=allowedCorsOrigin(req.headers.origin,allowedOrigins);try{
  if(req.method==='GET'&&req.url==='/health')return send(res,200,{ok:true,mode:'test'},corsOrigin);
  if(req.method==='GET'&&req.url==='/ready'){const readiness=await checkTestApiReadiness(supabase,{STRIPE_SECRET_KEY:process.env.STRIPE_SECRET_KEY,STRIPE_WEBHOOK_SECRET:process.env.STRIPE_WEBHOOK_SECRET,NOTIFICATION_WEBHOOK_SECRET:process.env.NOTIFICATION_WEBHOOK_SECRET});return send(res,readiness.ok?200:503,readiness,corsOrigin)}
  if(req.method==='OPTIONS'){if(req.headers.origin&&!corsOrigin)return send(res,403,{error:'origin_not_allowed'});res.writeHead(204,{...apiSecurityHeaders,...(corsOrigin?{'access-control-allow-origin':corsOrigin}:{ }),'access-control-allow-methods':'POST,OPTIONS','access-control-allow-headers':'authorization,content-type,stripe-signature,x-jtw-notification-signature','vary':'Origin'});return res.end()}
  if(req.headers.origin&&!corsOrigin)return send(res,403,{error:'origin_not_allowed'});
  if(req.method==='POST'&&req.url==='/v1/checkout'){const rate=checkoutRate.take(requestRateKey(req));if(!rate.allowed)return sendRateLimit(res,rate.retryAfterSeconds,corsOrigin,send);const body=JSON.parse((await readRequestBody(req,64_000)).toString('utf8'));const result=await checkout.post(req.headers.authorization,body);return send(res,result.status,result.body,corsOrigin)}
  if(req.method==='POST'&&req.url==='/v1/boarding/issue'){const rate=actionRate.take(requestRateKey(req));if(!rate.allowed)return sendRateLimit(res,rate.retryAfterSeconds,corsOrigin,send);const token=req.headers.authorization?.replace(/^Bearer\s+/i,'')??'';const session=await sessions.verify(token);if(!session)return send(res,401,{error:'unauthorized'},corsOrigin);const body=JSON.parse((await readRequestBody(req,16_000)).toString('utf8')) as {orderId?:string};const result=body.orderId?await boarding.issue(session.accountId,body.orderId):null;return result?send(res,200,result,corsOrigin):send(res,409,{error:'boarding_unavailable'},corsOrigin)}
  if(req.method==='POST'&&req.url==='/v1/boarding/verify'){const rate=actionRate.take(requestRateKey(req));if(!rate.allowed)return sendRateLimit(res,rate.retryAfterSeconds,corsOrigin,send);const token=req.headers.authorization?.replace(/^Bearer\s+/i,'')??'';const session=await sessions.verify(token);if(!session)return send(res,401,{error:'unauthorized'},corsOrigin);const body=JSON.parse((await readRequestBody(req,16_000)).toString('utf8')) as {token?:string;vehicleGroupId?:string;idempotencyKey?:string};const result=body.token&&body.vehicleGroupId&&body.idempotencyKey?await boarding.verify(session.accountId,{token:body.token,vehicleGroupId:body.vehicleGroupId,idempotencyKey:body.idempotencyKey}):null;return result?send(res,200,result,corsOrigin):send(res,403,{error:'boarding_verification_rejected'},corsOrigin)}
  if(req.method==='POST'&&req.url==='/v1/translations/message'){const rate=actionRate.take(requestRateKey(req));if(!rate.allowed)return sendRateLimit(res,rate.retryAfterSeconds,corsOrigin,send);const token=req.headers.authorization?.replace(/^Bearer\s+/i,'')??'';const session=await sessions.verify(token);if(!session)return send(res,401,{error:'unauthorized'},corsOrigin);const body=JSON.parse((await readRequestBody(req,16_000)).toString('utf8')) as {messageId?:string;targetLanguage?:string};if(!body.messageId||!isTranslationTarget(body.targetLanguage))return send(res,400,{error:'invalid_translation_request'},corsOrigin);const result=await translateVehicleMessage({accountId:session.accountId,messageId:body.messageId,targetLanguage:body.targetLanguage},translations,translationProvider);return send(res,result.status,result.body,corsOrigin)}
  if(req.method==='POST'&&req.url==='/v1/webhooks/stripe'){const signature=req.headers['stripe-signature'];if(typeof signature!=='string')return send(res,400,{error:'missing_signature'});const result=await stripe.handleWebhook(await readRequestBody(req,1_000_000),signature,events);return send(res,result.accepted?200:400,result)}
  if(req.method==='POST'&&req.url==='/v1/webhooks/notifications'){const signature=req.headers['x-jtw-notification-signature'];if(typeof signature!=='string')return send(res,400,{error:'missing_signature'});const result=await notificationReceipts.handle(await readRequestBody(req,64_000),signature);return send(res,result.accepted?200:result.reason==='store-unavailable'?503:400,result)}
  return send(res,404,{error:'not_found'});
}catch(error){const tooLarge=error instanceof RequestBodyTooLargeError;return send(res,tooLarge?413:error instanceof SyntaxError?400:500,{error:tooLarge?'body_too_large':error instanceof SyntaxError?'invalid_json':'server_error'})}});
server.requestTimeout=15_000;server.headersTimeout=10_000;server.keepAliveTimeout=5_000;server.maxRequestsPerSocket=100;
server.listen(port,'127.0.0.1',()=>console.log(`Japan Travel Weekend test API listening on http://127.0.0.1:${port}`));
