import type {TravelMomentStatus} from './travelMoments';
export type TravelMomentAction='recheck'|'edit_account'|'edit_trip'|'edit_url'|'view';
type Presentation={category:'needs_adjustment'|'pending_review'|'ineligible'|'eligible';title:string;message:string;action?:TravelMomentAction;actionLabel?:string};
const zh:Record<string,Presentation>={
 CHECKING:{category:'pending_review',title:'正在核验投稿资格',message:'正在读取帖子公开信息，请稍候。'},
 MISSING_OFFICIAL_MENTION:{category:'needs_adjustment',title:'还差一步即可参加',message:'暂未确认到 JTW 官方账号的 @ 标记。请在原帖中补充后重新核验。',action:'recheck',actionLabel:'我已修改，重新核验'},
 ACCOUNT_MISMATCH:{category:'needs_adjustment',title:'账号信息需要确认',message:'填写的社交账号名称与帖子发布账号暂时不一致。',action:'edit_account',actionLabel:'修改账号信息'},TRIP_MISMATCH:{category:'needs_adjustment',title:'行程对应关系需要调整',message:'请重新选择这条内容对应的实际 JTW 旅行。',action:'edit_trip',actionLabel:'重新选择行程'},INVALID_URL:{category:'needs_adjustment',title:'帖子链接好像不正确',message:'请直接复制有效 TikTok 或 Instagram 帖子链接。',action:'edit_url',actionLabel:'修改帖子链接'},PROFILE_URL_NOT_POST:{category:'needs_adjustment',title:'请提交具体帖子链接',message:'当前链接似乎指向个人主页，而不是具体帖子。',action:'edit_url',actionLabel:'修改帖子链接'},POST_UNAVAILABLE:{category:'needs_adjustment',title:'暂时无法找到该帖子',message:'请确认帖子仍存在，或修改帖子链接。',action:'edit_url',actionLabel:'修改帖子链接'},ORDER_REFUNDED:{category:'ineligible',title:'该行程暂不能参加本次活动',message:'当前对应订单已完成退款，因此不计入有效旅行记录。'},TRIP_NOT_COMPLETED:{category:'ineligible',title:'行程结束后即可参加',message:'活动投稿将在行程结束后开放核验。'},ORDER_UNPAID:{category:'ineligible',title:'订单状态暂不符合活动条件',message:'当前对应订单尚未完成支付。'},EXTERNAL_CHECK_UNAVAILABLE:{category:'pending_review',title:'正在等待平台信息',message:'投稿已保存，暂时无法自动确认部分公开信息，不会因此被直接淘汰。',action:'recheck',actionLabel:'重新核验'},DUPLICATE_CONTENT:{category:'needs_adjustment',title:'这条内容已经参加过啦',message:'这条帖子已经提交过本次活动，无需重复投稿。',action:'view',actionLabel:'查看我的投稿'}
};
const en:Record<string,Presentation>=Object.fromEntries(Object.entries(zh).map(([key,value])=>[key,{...value,title:key==='EXTERNAL_CHECK_UNAVAILABLE'?'Waiting for platform information':key==='ORDER_REFUNDED'?'This trip is not eligible':key==='TRIP_NOT_COMPLETED'?'Available after your trip ends':'Action needed',message:'Please review this submission and follow the next step.',actionLabel:value.action==='recheck'?'Check again':value.action==='edit_account'?'Edit account':value.action==='edit_trip'?'Choose trip':value.action==='edit_url'?'Edit post URL':'View submissions'}]));
export function getTravelMomentReasonPresentation(reason:string|undefined,locale:string):Presentation{const map=locale==='zh-CN'?zh:en;return map[reason??'']??(reason?{category:'pending_review',title:locale==='zh-CN'?'正在等待确认':'Waiting for confirmation',message:locale==='zh-CN'?'投稿已保存，运营正在确认。':'Your submission has been saved.',action:'recheck',actionLabel:locale==='zh-CN'?'重新核验':'Check again'}:{category:'eligible',title:locale==='zh-CN'?'投稿成功，已进入本月活动':'Submission accepted',message:locale==='zh-CN'?'核验已经完成。':'Verification is complete.'});}
export function travelerStatus(status:TravelMomentStatus,reason:string|undefined,locale:string){return getTravelMomentReasonPresentation(reason,locale).category}
