import type {PassengerLocale} from '../shared/i18n/passengerLocale';

type GrowthCopy={
  together:string; inviteTitle:string; inviteBody:string; momentsEntryTitle:string; momentsEntryBody:string; invite:string; viewMoments:string;
  referralEyebrow:string; referralTitle:string; referralBody:(percent:number)=>string; code:string; link:string; share:string; copy:string; copied:string; progress:(count:number)=>string; next:(remaining:number)=>string; qualified:string; rewards:string; noRewards:string; rewardStatus:(status:string)=>string; availableAt:(value:string)=>string; expiresAt:(value:string)=>string; rewardRecorded:string;
  momentsEyebrow:string; momentsTitle:string; momentsBody:string; mentionTitle:string; mentionBody:string; copyCaption:string; copiedCaption:string; trip:string; chooseTrip:string; url:string; handle:string; authorization:string; submit:string; invalidUrl:string; noCampaign:string; noTrips:string; submitted:string; records:string; open:string; loading:string; unavailable:string;
};

const zh:GrowthCopy={together:'一起旅行',inviteTitle:'一起旅行，一起更省',inviteBody:'邀请朋友参加 JTW，朋友首单享 10% 优惠；你也获得旅行奖励。',momentsEntryTitle:'Travel Moments',momentsEntryBody:'分享你的日本旅行作品',invite:'邀请好友',viewMoments:'Travel Moments →',referralEyebrow:'一起旅行',referralTitle:'邀请好友，一起出发',referralBody:p=>`朋友首单享 ${p}% 优惠；你也获得 ${p}% JTW 旅行奖励。`,code:'我的邀请码',link:'我的推荐链接',share:'分享给好友',copy:'复制链接',copied:'邀请链接已复制',progress:n=>`已成功邀请 ${n} 位朋友`,next:n=>`再邀请 ${n} 位，即可申请 JTW Ambassador`,qualified:'已达到 Ambassador 申请条件',rewards:'我的旅行奖励',noRewards:'暂时还没有旅行奖励。',rewardStatus:status=>({pending_trip_completion:'待解锁',active:'可使用',reserved:'已预留',redeemed:'已使用',void:'已失效',frozen:'已冻结',expired:'已过期'}[status]??status),availableAt:value=>`预计可用时间：${value}`,expiresAt:value=>`有效期至：${value}`,rewardRecorded:'奖励状态已记录',momentsEyebrow:'JTW TRAVEL MOMENTS',momentsTitle:'分享你的日本旅行',momentsBody:'把参加 JTW 时拍下的旅行内容发布到 TikTok 或 Instagram，再把作品链接提交给我们。',mentionTitle:'投稿前必须完成',mentionBody:'在 TikTok / Instagram 文案中 @japan-travel.info，这是参加当月 Travel Moments 的必要条件。',copyCaption:'复制投稿文案',copiedCaption:'投稿文案已复制',trip:'选择本月参加过的 JTW 行程',chooseTrip:'请选择行程',url:'TikTok / Instagram 作品链接',handle:'我的社媒账号',authorization:'我确认拥有该作品的发布权，并同意 JTW 在 Travel Moments 及 JTW 官方 TikTok / Instagram 中展示或转载该作品，并标注我的社媒账号。付费广告不包含在此授权内。',submit:'提交 Travel Moments',invalidUrl:'请粘贴 TikTok 或 Instagram 的公开作品链接',noCampaign:'本月 Travel Moments 尚未开放。',noTrips:'暂时没有符合条件的已完成行程。',submitted:'投稿成功，已加入本月 JTW Travel Moments',records:'我的投稿',open:'打开原帖',loading:'正在读取活动…',unavailable:'活动服务暂时不可用，请稍后重试。'};
const en:GrowthCopy={together:'Travel together',inviteTitle:'Travel together, save together',inviteBody:'Invite friends to JTW. Their first trip gets 10% off and you earn travel credit.',momentsEntryTitle:'Travel Moments',momentsEntryBody:'Share your Japan travel story',invite:'Invite friends',viewMoments:'Travel Moments →',referralEyebrow:'TRAVEL TOGETHER',referralTitle:'Invite friends, set off together',referralBody:p=>`A friend gets ${p}% off their first JTW trip, and you receive ${p}% JTW travel credit.`,code:'My invite code',link:'My invite link',share:'Share with friends',copy:'Copy link',copied:'Invite link copied',progress:n=>`${n} successful invites`,next:n=>`${n} more to apply for JTW Ambassador`,qualified:'Eligible to apply for JTW Ambassador',rewards:'My travel rewards',noRewards:'No travel rewards yet.',rewardStatus:status=>({pending_trip_completion:'Pending unlock',active:'Available',reserved:'Reserved',redeemed:'Used',void:'Voided',frozen:'Frozen',expired:'Expired'}[status]??status),availableAt:value=>`Expected availability: ${value}`,expiresAt:value=>`Valid until: ${value}`,rewardRecorded:'Reward status recorded',momentsEyebrow:'JTW TRAVEL MOMENTS',momentsTitle:'Share your Japan travel',momentsBody:'Post your JTW travel moment to TikTok or Instagram, then submit the public link.',mentionTitle:'Required before submitting',mentionBody:'Include @japan-travel.info in your TikTok or Instagram caption. It is required for this month’s Travel Moments.',copyCaption:'Copy caption',copiedCaption:'Caption copied',trip:'Choose a JTW trip you completed this month',chooseTrip:'Choose a trip',url:'TikTok / Instagram post link',handle:'My social handle',authorization:'I confirm that I have the right to publish this work and allow JTW to display or repost it on Travel Moments and JTW’s official TikTok / Instagram with my social handle credited. This does not include paid advertising.',submit:'Submit Travel Moments',invalidUrl:'Paste a public TikTok or Instagram post link',noCampaign:'Travel Moments is not open this month.',noTrips:'No eligible completed trips are available yet.',submitted:'Submitted — you have joined this month’s JTW Travel Moments',records:'My submissions',open:'Open post',loading:'Loading activity…',unavailable:'Travel Moments is temporarily unavailable. Please try again later.'};
export const growthCopy:Record<PassengerLocale,GrowthCopy>={'zh-CN':zh,en,'zh-TW':{...zh,together:'一起旅行',inviteTitle:'一起旅行，一起更省',invite:'邀請好友',momentsEntryBody:'分享你的日本旅行作品',copy:'複製連結',copied:'邀請連結已複製',submit:'提交 Travel Moments'},ja:{...en,together:'一緒に旅する',inviteTitle:'一緒に旅して、もっとお得に',inviteBody:'友人を JTW に招待。初回旅行は10%オフ、あなたには旅行特典。',invite:'友達を招待',referralTitle:'友達を招待して、一緒に出発',momentsTitle:'日本旅行をシェア',submit:'Travel Moments に投稿',copy:'リンクをコピー'},ko:{...en,together:'함께 여행하기',inviteTitle:'함께 여행하고 함께 절약하세요',invite:'친구 초대',referralTitle:'친구를 초대하고 함께 떠나요',momentsTitle:'일본 여행을 공유하세요',submit:'Travel Moments 제출'},es:{...en,together:'Viajar juntos',inviteTitle:'Viajen juntos y ahorren juntos',invite:'Invitar amigos',referralTitle:'Invita a tus amigos y viajen juntos',momentsTitle:'Comparte tu viaje por Japón',submit:'Enviar a Travel Moments'},vi:{...en,together:'Cùng nhau du lịch',inviteTitle:'Đi cùng nhau, tiết kiệm cùng nhau',invite:'Mời bạn bè',referralTitle:'Mời bạn bè, cùng khởi hành',momentsTitle:'Chia sẻ chuyến đi Nhật Bản',submit:'Gửi Travel Moments'},ne:{...en,together:'सँगै यात्रा',inviteTitle:'सँगै यात्रा, सँगै बचत',invite:'साथीलाई निम्तो',referralTitle:'साथीलाई निम्तो दिई सँगै जानुहोस्',momentsTitle:'आफ्नो जापान यात्रा साझा गर्नुहोस्',submit:'Travel Moments पठाउनुहोस्'}};

export const travelMomentsCaption='今天和 JTW 一起出发，\n记录我的日本旅行 ✨\n\n@japan-travel.info\n#JapanTravelWeekend\n#JTWTravelMoments';
