import {useEffect,useMemo,useState,type FormEvent} from 'react';
import {Link} from 'react-router-dom';
import QRCode from 'qrcode';
import {useApp} from './store';
import {detectBoostPlatform,validBoostPost,type BoostPlatform} from './boostPost';
import {growthCopy,travelMomentsCaption} from './growthCopy';
import './growthPages.css';

export function GrowthEntry(){const {state}=useApp();const c=growthCopy[state.ui.locale??'zh-CN'];return <section className="growth-entry"><div><small>{c.together.toUpperCase()}</small><h2>{c.inviteTitle}</h2><p>{c.inviteBody}</p><Link className="button" to="/app/referral">{c.invite}</Link></div><div className="growth-entry-links"><Link to="/app/referral"><b>{c.together}</b><span>{c.inviteBody}</span>›</Link><Link to="/app/travel-moments"><b>{c.momentsEntryTitle}</b><span>{c.momentsEntryBody}</span>›</Link></div></section>}

export function GrowthProfileRows(){const {state}=useApp();const c=growthCopy[state.ui.locale??'zh-CN'];return <section className="growth-profile" aria-label={c.together}><h2>{c.together}</h2><Link className="profile-setting-row" to="/app/referral"><i aria-hidden="true">♡</i><span><b>{c.code}</b><small>{c.inviteBody}</small></span><b aria-hidden="true">›</b></Link><Link className="profile-setting-row" to="/app/travel-moments"><i aria-hidden="true">✧</i><span><b>{c.momentsEntryTitle}</b><small>{c.momentsEntryBody}</small></span><b aria-hidden="true">›</b></Link></section>}

export function ReferralGrowth(){const {services,state}=useApp();const locale=state.ui.locale??'zh-CN';const c=growthCopy[locale];const [summary,setSummary]=useState<Awaited<ReturnType<NonNullable<typeof services>['loadOwnReferralSummary']>>>(null);const [notice,setNotice]=useState('');const [qr,setQr]=useState('');
 useEffect(()=>{let live=true;void services?.loadOwnReferralSummary().then(data=>{if(live)setSummary(data)});return()=>{live=false}},[services]);
 const link=useMemo(()=>summary?.code?`${window.location.origin}/app/create-account?ref=${encodeURIComponent(summary.code)}`:'',[summary?.code]);
 useEffect(()=>{if(link)void QRCode.toDataURL(link,{width:220,margin:1}).then(setQr).catch(()=>setQr(''))},[link]);
 const copy=async()=>{try{await navigator.clipboard.writeText(link);setNotice(c.copied)}catch{setNotice(link)}}; const share=async()=>{if(navigator.share)try{await navigator.share({title:'Japan Travel Weekend',url:link});return}catch{};void copy()};
 if(!summary)return <section className="growth-page"><p role="status">{c.loading}</p></section>;
 const count=Math.max(0,summary.completedInvites??summary.successfulInvites??0), percent=summary.discountPercent, remain=Math.max(0,10-count);
 const coupons=Array.isArray(summary.coupons)?summary.coupons:[];
 return <main className="growth-page referral-growth"><header><small>{c.referralEyebrow}</small><h1>{c.referralTitle}</h1><p>{c.referralBody(percent)}</p></header><section className="growth-card"><label>{c.code}<strong>{summary.code}</strong></label><label>{c.link}<input readOnly value={link} onFocus={e=>e.currentTarget.select()}/></label><div className="growth-actions"><button className="button" onClick={()=>void share()}>{c.share}</button><button className="button secondary" onClick={()=>void copy()}>{c.copy}</button></div>{qr&&<img className="growth-qr" src={qr} alt={c.code}/>} {notice&&<p role="status">{notice}</p>}</section><section className="growth-card"><h2>{c.progress(count)}</h2><div className="growth-progress" role="progressbar" aria-valuemin={0} aria-valuemax={10} aria-valuenow={Math.min(count,10)}><i style={{width:`${Math.min(100,count*10)}%`}}/></div><p>{count>=10?c.qualified:c.next(remain)}</p></section><section className="growth-card"><h2>{c.rewards}</h2>{coupons.length===0?<p>{c.noRewards}</p>:coupons.map((coupon:any)=><article className="growth-record" key={String(coupon.id)}><b>{Number(coupon.discountPercent??percent)}% · {c.rewardStatus(String(coupon.status))}</b><small>{rewardTiming(coupon,locale,c)}</small></article>)}</section></main>}

export function TravelMoments(){const {services,state}=useApp();const locale=state.ui.locale??'zh-CN';const c=growthCopy[locale];const [data,setData]=useState<Awaited<ReturnType<NonNullable<typeof services>['loadOwnShareCampaign']>>|null>(null);const [url,setUrl]=useState('');const [handle,setHandle]=useState('');const [orderId,setOrderId]=useState('');const [authorized,setAuthorized]=useState(false);const [notice,setNotice]=useState('');const [successCode,setSuccessCode]=useState('');const [busy,setBusy]=useState(false);const platform=detectBoostPlatform(url);
 useEffect(()=>{let live=true;if(services)void services.loadOwnShareCampaign().then(value=>{if(live)setData(value)}).catch(()=>{if(live)setNotice(c.unavailable)});return()=>{live=false}},[services,c.unavailable]);
 const copyCaption=async()=>{try{await navigator.clipboard.writeText(travelMomentsCaption);setNotice(c.copiedCaption)}catch{setNotice(travelMomentsCaption)}};
 const submit=async(event:FormEvent)=>{event.preventDefault();if(!services||!data?.campaign||!platform||!validBoostPost(platform,url)||!authorized||!orderId||busy)return;setBusy(true);setNotice('');const result=await services.submitShareLink({campaignId:String(data.campaign.id),orderId,platform,url:url.trim(),platformAccount:handle.trim(),authorizationVersion:'share-link-limited-v2',mentionConfirmed:true,authorized:true});setBusy(false);if(!result.ok){setNotice(result.error??c.unavailable);return}setSuccessCode(submissionCode(platform,String(data.campaign.campaign_month),result.id??''));setUrl('');setHandle('');setOrderId('');setAuthorized(false);setData(await services.loadOwnShareCampaign())};
 return <main className="growth-page moments-page"><header><small>{c.momentsEyebrow}</small><h1>{c.momentsTitle}</h1><p>{c.momentsBody}</p></header><section className="growth-card growth-mention"><h2>{c.mentionTitle}</h2><strong>@japan-travel.info</strong><p>{c.mentionBody}</p><button className="button secondary" onClick={()=>void copyCaption()}>{c.copyCaption}</button></section>{successCode&&<section className="growth-card" role="status"><h2>{c.submitted}</h2><p>{successCode}</p></section>}{!data?<p role="status">{c.loading}</p>:data.error?<p role="alert">{data.error}</p>:!data.campaign?<p>{c.noCampaign}</p>:<><form className="growth-card" onSubmit={submit}><label>{c.trip}<select value={orderId} onChange={e=>setOrderId(e.target.value)} required><option value="">{c.chooseTrip}</option>{data.orders.map((order:any)=><option value={String(order.id)} key={String(order.id)}>{String(order.tripTitle??order.id)} · {formatDate(String(order.departureAt??order.created_at),locale)}</option>)}</select></label>{data.orders.length===0&&<p>{c.noTrips}</p>}<label>{c.url}<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…" required/>{url&&!platform&&<small role="alert">{c.invalidUrl}</small>}</label><label>{c.handle}<input value={handle} minLength={2} maxLength={120} onChange={e=>setHandle(e.target.value)} placeholder="@yourname" required/></label><label className="growth-consent"><input type="checkbox" checked={authorized} onChange={e=>setAuthorized(e.target.checked)}/><span>{c.authorization}</span></label><button className="button full" disabled={!platform||!validBoostPost(platform,url)||!authorized||!orderId||busy}>{busy?c.loading:c.submit}</button></form><section className="growth-card"><h2>{c.records}</h2>{data.submissions.length===0?<p>{c.noTrips}</p>:data.submissions.map((item:any)=><article className="growth-record" key={String(item.id)}><b>{String(item.platform).toUpperCase()} · {submissionCode(String(item.platform) as BoostPlatform,String(item.campaignMonth??data.campaign?.campaign_month),String(item.id))}</b><span>{formatHandle(String(item.platform_account))}</span><small>{friendlyStatus(String(item.status),locale)} · {formatDate(String(item.created_at),locale)}</small><a href={String(item.post_url)} target="_blank" rel="noreferrer">{c.open}</a></article>)}</section></>}</main>}
function formatDate(value:string,locale:string){const date=new Date(value);return Number.isNaN(date.valueOf())?'—':new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeZone:'Asia/Tokyo'}).format(date)}
function formatDateTime(value:string,locale:string){const date=new Date(value);return Number.isNaN(date.valueOf())?'—':new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Tokyo'}).format(date)}
function rewardTiming(coupon:Record<string,unknown>,locale:string,c:typeof growthCopy['zh-CN']){const available=typeof coupon.availableAt==='string'?coupon.availableAt:'';const expiry=typeof coupon.expiresAt==='string'?coupon.expiresAt:'';if(String(coupon.status)==='pending_trip_completion'&&available)return c.availableAt(formatDateTime(available,locale));if(['active','reserved'].includes(String(coupon.status))&&expiry)return c.expiresAt(formatDateTime(expiry,locale));return c.rewardRecorded}
function submissionCode(platform:BoostPlatform,month:string,id:string){return `${platform==='instagram'?'IG':'TT'}-${month.slice(0,7).replace('-','')}-${id.replace(/-/g,'').slice(0,8).toUpperCase()}`}
function formatHandle(value:string){return value.startsWith('@')?value:`@${value}`}
function friendlyStatus(value:string,locale:string){const zh:Record<string,string>={pending:'已提交',valid:'已加入本月活动',needs_information:'需要补充',ineligible:'不符合本月活动',withdrawn:'已撤回'};const en:Record<string,string>={pending:'Submitted',valid:'Included this month',needs_information:'More information needed',ineligible:'Not eligible this month',withdrawn:'Withdrawn'};return (locale==='zh-CN'||locale==='zh-TW'?zh:en)[value]??value}
