import {useEffect,useMemo,useState,type FormEvent} from 'react';
import {Link} from 'react-router-dom';
import QRCode from 'qrcode';
import {useApp} from './store';
import {canonicalizeTravelMomentUrl} from '../shared/travelMoments';
import {TravelMomentSubmissionList} from './TravelMomentSubmissionList';
import {growthCopy,travelMomentsCaption} from './growthCopy';
import './growthPages.css';

export function GrowthEntry(){const {state}=useApp();const c=growthCopy[state.ui.locale??'zh-CN'];return <section className="growth-entry"><div><small>{c.together.toUpperCase()}</small><h2>{c.inviteTitle}</h2><p>{c.inviteBody}</p><Link className="button" to="/app/referral">{c.invite}</Link></div><div className="growth-entry-links"><Link to="/app/referral"><b>{c.together}</b><span>{c.inviteBody}</span>›</Link><Link to="/app/travel-moments"><b>{c.momentsEntryTitle}</b><span>{c.momentsEntryBody}</span>›</Link></div></section>}

export function GrowthProfileRows(){const {state}=useApp();const c=growthCopy[state.ui.locale??'zh-CN'];const ambassador=state.ui.locale==='zh-CN'?'推广大使':state.ui.locale==='ja'?'アンバサダー':'Ambassador';const ambassadorHelp=state.ui.locale==='zh-CN'?'分享 Japan Travel Weekend，解锁推广大使权益':state.ui.locale==='ja'?'紹介してアンバサダー特典を解放':'Share JTW to unlock Ambassador benefits';return <section className="growth-profile" aria-label={c.together}><h2>{c.together}</h2><Link className="profile-setting-row" to="/app/referral"><i aria-hidden="true">♡</i><span><b>{c.code}</b><small>{c.inviteBody}</small></span><b aria-hidden="true">›</b></Link><Link className="profile-setting-row" to="/app/ambassador"><i aria-hidden="true">✦</i><span><b>{ambassador}</b><small>{ambassadorHelp}</small></span><b aria-hidden="true">›</b></Link><Link className="profile-setting-row" to="/app/travel-moments"><i aria-hidden="true">✧</i><span><b>{c.momentsEntryTitle}</b><small>{c.momentsEntryBody}</small></span><b aria-hidden="true">›</b></Link></section>}

export function ReferralGrowth(){const {services,state}=useApp();const locale=state.ui.locale??'zh-CN';const c=growthCopy[locale];const [summary,setSummary]=useState<Awaited<ReturnType<NonNullable<typeof services>['loadOwnReferralSummary']>>>(null);const [notice,setNotice]=useState('');const [qr,setQr]=useState('');
 useEffect(()=>{let live=true;void services?.loadOwnReferralSummary().then(data=>{if(live)setSummary(data)});return()=>{live=false}},[services]);
 const link=useMemo(()=>summary?.code?`${window.location.origin}/r/${encodeURIComponent(summary.code)}`:'',[summary?.code]);
 useEffect(()=>{if(link)void QRCode.toDataURL(link,{width:220,margin:1}).then(setQr).catch(()=>setQr(''))},[link]);
 const copy=async()=>{try{await navigator.clipboard.writeText(link);setNotice(c.copied)}catch{setNotice(link)}}; const share=async()=>{if(navigator.share)try{await navigator.share({title:'Japan Travel Weekend',url:link});return}catch{};void copy()};
 if(!summary)return <section className="growth-page"><p role="status">{c.loading}</p></section>;
 const count=Math.max(0,summary.completedInvites??summary.successfulInvites??0), percent=summary.discountPercent, remain=Math.max(0,10-count);
 const coupons=Array.isArray(summary.coupons)?summary.coupons:[];
 return <main className="growth-page referral-growth"><header><small>{c.referralEyebrow}</small><h1>{c.referralTitle}</h1><p>{c.referralBody(percent)}</p></header><section className="growth-card"><label>{c.code}<strong>{summary.code}</strong></label><label>{c.link}<input readOnly value={link} onFocus={e=>e.currentTarget.select()}/></label><div className="growth-actions"><button className="button" onClick={()=>void share()}>{c.share}</button><button className="button secondary" onClick={()=>void copy()}>{c.copy}</button></div>{qr&&<img className="growth-qr" src={qr} alt={c.code}/>} {notice&&<p role="status">{notice}</p>}</section><section className="growth-card"><h2>{c.progress(count)}</h2><div className="growth-progress" role="progressbar" aria-valuemin={0} aria-valuemax={10} aria-valuenow={Math.min(count,10)}><i style={{width:`${Math.min(100,count*10)}%`}}/></div><p>{count>=10?c.qualified:c.next(remain)}</p></section><section className="growth-card"><h2>{c.rewards}</h2>{coupons.length===0?<p>{c.noRewards}</p>:coupons.map((coupon:any)=><article className="growth-record" key={String(coupon.id)}><b>{Number(coupon.discountPercent??percent)}% · {c.rewardStatus(String(coupon.status))}</b><small>{rewardTiming(coupon,locale,c)}</small></article>)}</section></main>}

const tmText={
 'zh-CN':{title:'旅行瞬间',body:'提交 TikTok 或 Instagram 的公开帖子链接，系统会立即核验旅行资格。',trip:'选择对应的 JTW 旅行',url:'帖子链接',account:'社交账号名称',submit:'提交投稿并开始核验',checking:'正在核验投稿资格…',records:'我的投稿',recheck:'我已修改，重新核验',eligible:'投稿成功，已进入本月活动',adjust:'还差一步即可参加',pending:'正在等待平台信息',ineligible:'暂不符合活动资格',duplicate:'这条内容已经参加过啦',empty:'暂时没有可关联的已完成旅行。'},
 en:{title:'Travel Moments',body:'Submit a public TikTok or Instagram post. We check eligibility right away.',trip:'Choose your JTW trip',url:'Post URL',account:'Social account name',submit:'Submit and check eligibility',checking:'Checking your submission…',records:'My submissions',recheck:'I updated it — check again',eligible:'Submitted — now in this month’s activity',adjust:'One more step is needed',pending:'Waiting for platform information',ineligible:'Not eligible for this submission',duplicate:'This post has already been submitted',empty:'No completed JTW trip is available.'}
} as const;
export function TravelMoments(){const {services,state}=useApp();const locale=state.ui.locale??'zh-CN';const copy=tmText[locale==='zh-CN'?'zh-CN':'en'];const [data,setData]=useState<{trips:any[];submissions:any[];error:string|null}|null>(null);const [url,setUrl]=useState('');const [account,setAccount]=useState('');const [orderId,setOrderId]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const parsed=canonicalizeTravelMomentUrl(url);
 const refresh=async()=>{const next=typeof services?.loadOwnTravelMoments==='function'?await services.loadOwnTravelMoments():null;if(next)setData(next)};useEffect(()=>{void refresh()},[services]);
 const submit=async(event:FormEvent)=>{event.preventDefault();if(!services||busy||!orderId||!('platform'in parsed)||!account.trim())return;setBusy(true);setNotice(copy.checking);const created=await services.createTravelMoment({orderId,platform:parsed.platform,url,socialAccountName:account});if(created.duplicate){setNotice(copy.duplicate);setBusy(false);await refresh();return}if(created.id&&created.status!=='ineligible')await services.checkTravelMoment({submissionId:created.id,trigger:'initial_submit',expectedGeneration:created.generation??1});setBusy(false);setNotice(created.error??'');setUrl('');setAccount('');await refresh()};
 return <main className="growth-page moments-page"><header><small>JTW TRAVEL MOMENTS</small><h1>{copy.title}</h1><p>{copy.body}</p></header><section className="growth-card growth-mention"><h2>@japan-travel.info · #JapanTravelWeekend</h2><p>发布公开帖子后，复制具体帖子链接提交；不需要授权登录社交平台。</p></section><form className="growth-card" onSubmit={submit}><label>{copy.trip}<select value={orderId} onChange={e=>setOrderId(e.target.value)} required><option value="">—</option>{data?.trips.map((trip:any)=><option key={String(trip.order_id)} value={String(trip.order_id)}>{String(trip.trip_title)} · {formatDate(String(trip.departure_at),locale)}</option>)}</select></label><label>{copy.url}<input type="url" value={url} onChange={e=>setUrl(e.target.value)} required/></label><label>{copy.account}<input value={account} onChange={e=>setAccount(e.target.value)} required/></label><button className="button full" disabled={busy||!orderId||!('platform'in parsed)}>{busy?copy.checking:copy.submit}</button>{notice&&<p role="status">{notice}</p>}</form>{data&&<TravelMomentSubmissionList data={data} locale={locale} refresh={refresh}/>}</main>}
function formatDate(value:string,locale:string){const date=new Date(value);return Number.isNaN(date.valueOf())?'—':new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeZone:'Asia/Tokyo'}).format(date)}
function formatDateTime(value:string,locale:string){const date=new Date(value);return Number.isNaN(date.valueOf())?'—':new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Tokyo'}).format(date)}
function rewardTiming(coupon:Record<string,unknown>,locale:string,c:typeof growthCopy['zh-CN']){const available=typeof coupon.availableAt==='string'?coupon.availableAt:'';const expiry=typeof coupon.expiresAt==='string'?coupon.expiresAt:'';if(String(coupon.status)==='pending_trip_completion'&&available)return c.availableAt(formatDateTime(available,locale));if(['active','reserved'].includes(String(coupon.status))&&expiry)return c.expiresAt(formatDateTime(expiry,locale));return c.rewardRecorded}
function formatHandle(value:string){return value.startsWith('@')?value:`@${value}`}
function friendlyStatus(value:string,locale:string){const zh:Record<string,string>={pending:'已提交',valid:'已加入本月活动',needs_information:'需要补充',ineligible:'不符合本月活动',withdrawn:'已撤回'};const en:Record<string,string>={pending:'Submitted',valid:'Included this month',needs_information:'More information needed',ineligible:'Not eligible this month',withdrawn:'Withdrawn'};return (locale==='zh-CN'||locale==='zh-TW'?zh:en)[value]??value}
