import {useCallback,useEffect,useMemo,useState,type FormEvent} from 'react';
import {appConfig} from '../shared/config/businessRules';
import {optimizeFleet,type FleetPlan} from '../shared/operations/fleetOptimizer';
import {recommendDrivers} from '../shared/operations/driverAssignment';
import type {OperationsSnapshot} from '../shared/integrations/supabaseOperations';
import {useApp} from './store';

export function OperationsDashboard(){
  const {services}=useApp();const [snapshot,setSnapshot]=useState<OperationsSnapshot|null>(null);const [error,setError]=useState<string|null>(null);const [notice,setNotice]=useState('');const [passengers,setPassengers]=useState(0);const [startsAt,setStartsAt]=useState('');const [endsAt,setEndsAt]=useState('');
  const reload=useCallback(async()=>{if(!services)return;const result=await services.operations.loadSnapshot();setSnapshot(result.data);setError(result.error)},[services]);
  useEffect(()=>{if(!services)return;void services.operations.loadSnapshot().then(result=>{setSnapshot(result.data);setError(result.error)})},[services]);
  const plan=useMemo(()=>{if(!snapshot||passengers<1)return null;const types=snapshot.vehicleTypes.map(type=>({...type,type:type.type_key,capacity:type.sellable_capacity,costUnits:Number(type.cost_units),availableCount:snapshot.vehicles.filter(vehicle=>vehicle.vehicle_type_key===type.type_key&&vehicle.status==='available').length}));try{return optimizeFleet(passengers,types,'operations-preview')}catch{return null}},[snapshot,passengers]);
  const recommendations=useMemo(()=>{if(!snapshot||!plan||!startsAt||!endsAt)return [];const start=new Date(startsAt).getTime(),end=new Date(endsAt).getTime();return recommendDrivers(plan.assignments,snapshot.drivers.map(driver=>{const window=driver.driver_availability_windows.find(item=>new Date(item.starts_at).getTime()<=start&&new Date(item.ends_at).getTime()>=end);return {id:driver.id,displayName:driver.display_name,externalDispatchId:driver.external_dispatch_id,qualifiedVehicleTypes:driver.driver_vehicle_qualifications.map(item=>item.vehicle_type_key),languages:driver.languages,availableFrom:window?.starts_at??'',availableUntil:window?.ends_at??'',status:driver.status,assignedWindows:[]}}),new Date(startsAt).toISOString(),new Date(endsAt).toISOString(),['zh-CN','ja'])},[snapshot,plan,startsAt,endsAt]);
  const submitVehicle=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!services)return;const form=new FormData(event.currentTarget);const ok=await services.operations.createVehicle({registration:String(form.get('registration')??''),vehicleType:String(form.get('vehicleType')??''),externalDispatchId:String(form.get('externalDispatchId')??'')});setNotice(ok?'车辆已保存':'车辆保存失败，请检查重复车牌与运营权限');if(ok){event.currentTarget.reset();await reload()}};
  const submitDriver=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!services)return;const form=new FormData(event.currentTarget);const ok=await services.operations.createDriver({displayName:String(form.get('displayName')??''),externalDispatchId:String(form.get('driverExternalId')??''),vehicleTypes:form.getAll('qualifiedTypes').map(String),languages:String(form.get('languages')??'').split(',').map(value=>value.trim()).filter(Boolean),availableFrom:new Date(String(form.get('availableFrom'))).toISOString(),availableUntil:new Date(String(form.get('availableUntil'))).toISOString()});setNotice(ok?'司机资料与可用时间已保存':'司机保存失败，请检查车型、时间与运营权限');if(ok){event.currentTarget.reset();await reload()}};
  return <main className="operations-dashboard"><header className="operations-head"><div><span>JT WEEKEND · OPERATIONS</span><h1>车辆与司机调度</h1><p>数据源：Supabase运营表；无数据时不生成虚构统计。</p></div><a href="/app">返回乘客应用</a></header>{!services||error?<section className="operations-error" role="alert"><h2>后台数据尚未就绪</h2><p>{error??'运营数据服务未配置'}</p><p>请先在测试项目执行021迁移，不会自动发送柚子任务。</p></section>:snapshot&&<><section className="operations-kpis"><Kpi label="车型" value={snapshot.vehicleTypes.length}/><Kpi label="可用车辆" value={snapshot.vehicles.filter(v=>v.status==='available').length}/><Kpi label="可用司机" value={snapshot.drivers.filter(d=>d.status==='available').length}/><Kpi label="待确认派单" value={snapshot.dispatchDrafts}/></section><p className="operations-freshness">更新：{new Date(snapshot.loadedAt).toLocaleString('zh-CN',{timeZone:'Asia/Tokyo'})}（日本时间）</p><section className="operations-grid"><article><h2>新增车辆</h2><form onSubmit={submitVehicle}><label>车牌／内部识别号<input required name="registration" maxLength={40}/></label><label>车型<select required name="vehicleType"><option value="">请选择</option>{snapshot.vehicleTypes.map(v=><option key={v.type_key} value={v.type_key}>{v.label}</option>)}</select></label><label>柚子车辆ID（可稍后补充）<input name="externalDispatchId"/></label><button className="button">保存车辆</button></form></article><article><h2>新增司机</h2><form onSubmit={submitDriver}><label>司机姓名<input required name="displayName"/></label><label>柚子司机ID<input name="driverExternalId"/></label><fieldset><legend>可驾驶车型</legend>{snapshot.vehicleTypes.map(v=><label className="check" key={v.type_key}><input type="checkbox" name="qualifiedTypes" value={v.type_key}/>{v.label}</label>)}</fieldset><label>语言代码（逗号分隔）<input name="languages" placeholder="zh-CN, ja"/></label><label>可用开始<input required type="datetime-local" name="availableFrom"/></label><label>可用结束<input required type="datetime-local" name="availableUntil"/></label><button className="button">保存司机</button></form></article></section><section className="operations-planner"><h2>自动配车与司机推荐</h2><div className="operations-controls"><label>报名人数<input type="number" min="1" value={passengers||''} onChange={event=>setPassengers(Number(event.target.value))}/></label><label>任务开始<input type="datetime-local" value={startsAt} onChange={event=>setStartsAt(event.target.value)}/></label><label>任务结束<input type="datetime-local" value={endsAt} onChange={event=>setEndsAt(event.target.value)}/></label></div>{passengers>0&&!plan?<p className="operations-error">当前可用车辆无法承载全部乘客。</p>:plan&&<Plan plan={plan} recommendations={recommendations}/>}<button className="button" disabled>确认并发送至柚子调度（真实API未连接）</button></section>{notice&&<p role="status" className="notice">{notice}</p>}</>}</main>;
}
function Kpi({label,value}:{label:string;value:number}){return <article><span>{label}</span><strong>{value}</strong></article>}
function Plan({plan,recommendations}:{plan:FleetPlan;recommendations:{vehicleAssignmentId:string;driverId:string|null;reason:string[]}[]}){return <div className="operations-plan"><p>推荐 {plan.vehicleCount} 辆 · 总容量 {plan.totalCapacity} · 空席 {plan.unusedSeats} · 相对成本 {plan.costUnits}</p>{plan.assignments.map(vehicle=>{const driver=recommendations.find(item=>item.vehicleAssignmentId===vehicle.id);return <article key={vehicle.id}><b>Vehicle {vehicle.sequence} · {appConfig.fleetVehicleTypes.find(type=>type.type===vehicle.vehicleType)?.label??vehicle.vehicleType}</b><span>{vehicle.booked}/{vehicle.capacity} 人</span><small>{driver?driver.driverId?`推荐司机：${driver.driverId}`:driver.reason[0]:'填写任务时间后推荐司机'}</small></article>})}</div>}
