import {useEffect,useMemo,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {passengerChatCopy as c} from '../shared/i18n/passengerChat';
import {chatLanguages,preferredChatLanguage,type ChatLanguage} from '../shared/services/chatTranslation';
import {currentMeetingStop,meetingUrgency,type ItineraryStop} from '../shared/services/itineraryMeeting';
import {guideTelephoneUrl,openWalkingNavigation} from '../shared/capabilities/meetingActions';

type ChatMessage={id:string;senderId?:string;name?:string;role?:'passenger'|'driver'|'guide'|'operations';time?:string;content?:string;translated?:string;sourceLanguage?:string;kind?:'unread'|'meeting-change';oldValue?:string;newValue?:string;reason?:string};
export type PassengerChatRoomProps={tripName:string;stage:string;status:'preparing'|'meeting'|'traveling'|'ended';party:{arrived:number;total:number;distanceMeters:number;walkMinutes:number};guide:{name:string;role:string;phone:string;avatar:string;vehicle:{type:string;color:string;plate:string}};stops:ItineraryStop[];messages:ChatMessage[];onSend?:(message:string)=>void;onArrive?:()=>void;readOnly?:boolean};

const roleLabel={passenger:'乘客',driver:'司机',guide:'司导',operations:'运营'} as const;
const PhoneIcon=()=> <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 3H4.8C3.8 3 3 3.8 3 4.8 3 13.7 10.3 21 19.2 21c1 0 1.8-.8 1.8-1.8V17l-4.7-1-1.1 2.1a15.8 15.8 0 0 1-9.3-9.3L8 7.7 7 3Z"/></svg>;
const MapIcon=()=> <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m3 6 5-2 8 2 5-2v14l-5 2-8-2-5 2V6Z"/><path d="M8 4v14m8-12v14M12.5 13.5l5.5-3-3 5.5-1-2-1.5-.5Z"/></svg>;

export function PassengerChatRoom(props:PassengerChatRoomProps){
  const [expanded,setExpanded]=useState(false);const [menu,setMenu]=useState(false);const [language,setLanguage]=useState<ChatLanguage>(()=>preferredChatLanguage(typeof navigator==='undefined'?[]:navigator.languages));const [translationMenu,setTranslationMenu]=useState(false);const [now,setNow]=useState(()=>new Date());const [arrived,setArrived]=useState(false);const [lateMenu,setLateMenu]=useState(false);const [late,setLate]=useState('');const [draft,setDraft]=useState('');const [quick,setQuick]=useState(false);const [acked,setAcked]=useState<string[]>([]);const [originals,setOriginals]=useState<string[]>([]);const [localMessages,setLocalMessages]=useState(props.messages);const scrollRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{const id=window.setInterval(()=>setNow(new Date()),30000);return()=>window.clearInterval(id)},[]);
  const stop=useMemo(()=>currentMeetingStop(props.stops),[props.stops]);
  const urgency=stop?meetingUrgency(stop,now):null;
  const ended=props.status==='ended'||props.readOnly;
  if(!stop)return null;
  const send=(value=draft)=>{const text=value.trim();if(!text||ended)return;setLocalMessages(items=>[...items,{id:crypto.randomUUID(),senderId:'me',name:'我',role:'passenger',time:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}),content:text}]);props.onSend?.(text);setDraft('');setQuick(false)};
  const callGuide=(event:React.MouseEvent)=>{event.stopPropagation();const url=guideTelephoneUrl(props.guide.phone);if(url&&window.confirm(c.confirmCall))window.location.href=url};
  const navigate=(event:React.MouseEvent)=>{event.stopPropagation();openWalkingNavigation({latitude:stop.latitude,longitude:stop.longitude,destinationName:stop.meetingPointName})};
  return <div className="passenger-chat-page">
    <header className="pc-header"><Link to="/app/my-trip" aria-label={c.back}>‹</Link><div><b>{props.tripName}</b><span><i className={`pc-status ${props.status}`}/>{c.status[props.status]} · {props.stage} · {props.party.total}{c.people}</span></div><button type="button" aria-label={c.translate} onClick={()=>setTranslationMenu(v=>!v)}>译</button><button type="button" aria-label={c.more} onClick={()=>setMenu(v=>!v)}>•••</button>{translationMenu&&<div className="pc-popover pc-language-menu">{chatLanguages.map(item=><button key={item.code} className={language===item.code?'active':''} onClick={()=>{setLanguage(item.code);setTranslationMenu(false)}}>{item.label}</button>)}</div>}{menu&&<div className="pc-popover pc-more-menu">{[c.members,c.notifications,c.emergency,c.feedback].map(item=><button key={item}>{item}</button>)}</div>}</header>
    <section className={`pc-meeting-shell ${expanded?'expanded':''} ${urgency?.late?'late':''}`}>
      <div className="pc-meeting-bar" role="button" tabIndex={0} aria-expanded={expanded} onClick={()=>setExpanded(v=>!v)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();setExpanded(v=>!v)}}}>
        <button className="pc-icon-button" type="button" aria-label={c.callGuide} onClick={callGuide}><PhoneIcon/></button><button className="pc-icon-button" type="button" aria-label={c.navigate} onClick={navigate}><MapIcon/></button><b>{stop.meetingTime}{c.meetingSuffix}</b><span title={stop.meetingPointName}>{stop.meetingPointName}</span><em>{props.party.distanceMeters}m</em><i className="pc-chevron" aria-hidden="true">⌄</i>
      </div>
      <div className={`pc-time-progress ${urgency?.tone}`} aria-label={urgency?.late?c.late:`${c.remaining}${urgency?.minutesRemaining}${c.minutes}`}><span style={{width:`${urgency?.progress??0}%`}}/></div>
      {expanded&&<MeetingDetails {...props} stop={stop} urgency={urgency!} arrived={arrived} late={late} onArrive={()=>{setArrived(true);props.onArrive?.()}} onLate={()=>setLateMenu(true)} onNavigate={()=>openWalkingNavigation({latitude:stop.latitude,longitude:stop.longitude,destinationName:stop.meetingPointName})}/>} 
    </section>
    {lateMenu&&<div className="pc-modal-backdrop" role="presentation" onClick={()=>setLateMenu(false)}><div className="pc-modal" role="dialog" aria-modal="true" aria-label={c.lateReport} onClick={e=>e.stopPropagation()}><h2>{c.lateReport}</h2>{['5分钟','10分钟','15分钟以上'].map(value=><button key={value} onClick={()=>{setLate(value);setLateMenu(false)}}>预计迟到 {value}</button>)}<button onClick={()=>setLateMenu(false)}>{c.cancel}</button></div></div>}
    <div className="pc-chat-scroll" ref={scrollRef}>
      <div className="pc-day-divider"><span>{c.dateToday}</span></div>
      {localMessages.map((message,index)=><MessageView key={message.id} message={message} previous={localMessages[index-1]} own={message.senderId==='me'} language={language} acknowledged={acked.includes(message.id)} originalOpen={originals.includes(message.id)} onAcknowledge={()=>setAcked(v=>[...v,message.id])} onOriginal={()=>setOriginals(v=>v.includes(message.id)?v.filter(id=>id!==message.id):[...v,message.id])}/>)}
    </div>
    <footer className="pc-composer">{ended&&<div className="pc-readonly">{c.closed}</div>}{quick&&<div className="pc-quick-phrases">{c.phrases.map(item=><button key={item} onClick={()=>send(item)}>{item}</button>)}</div>}<div className="pc-compose-row"><button aria-label={c.photo} disabled={ended}>＋</button><button aria-label={c.location} disabled={ended}>⌖</button><button aria-label={c.voice} disabled={ended}>◉</button><input aria-label={c.input} value={draft} disabled={ended} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}} placeholder={ended?c.closed:c.input}/><button className="pc-quick" aria-label={c.quickPhrases} disabled={ended} onClick={()=>setQuick(v=>!v)}>语</button><button className="pc-send" disabled={ended||!draft.trim()} onClick={()=>send()}>{c.send}</button></div></footer>
  </div>
}

function MeetingDetails({stop,party,guide,stops,urgency,arrived,late,onArrive,onLate,onNavigate}:PassengerChatRoomProps&{stop:ItineraryStop;urgency:ReturnType<typeof meetingUrgency>;arrived:boolean;late:string;onArrive:()=>void;onLate:()=>void;onNavigate:()=>void}){
  return <div className="pc-meeting-details"><div className="pc-detail-metrics"><span><small>{c.remaining}</small><b>{urgency.late?c.late:`${Math.max(0,urgency.minutesRemaining)} ${c.minutes}`}</b></span><span><small>{c.distance}</small><b>{party.distanceMeters} m</b></span><span><small>{c.walk}</small><b>{party.walkMinutes} {c.minutes}</b></span></div><div className="pc-landmark">{stop.meetingPointPhoto&&<img src={stop.meetingPointPhoto} alt="集合地点参考"/>}<div><b>{stop.meetingPointName}</b><p>{stop.meetingPointDescription}</p><button onClick={onNavigate}>{c.navigate}</button></div></div><div className="pc-checkin"><div><small>{c.ownCheckin}</small><b>{arrived?c.arrivedStatus:late?`预计迟到 ${late}`:c.notArrived}</b><span>{c.groupProgress} {party.arrived+(arrived?1:0)}/{party.total}{c.people}</span></div><button disabled={arrived} onClick={onArrive}>{arrived?'✓ '+c.arrivedStatus:c.arrived}</button><button onClick={onLate}>{c.mayBeLate}</button></div><section className="pc-guide-vehicle"><h3>{c.guideVehicle}</h3><div className="pc-guide-row"><i>{guide.avatar}</i><span><b>{guide.name}</b><small>{guide.role} · {guide.phone}</small></span><button>{c.messageGuide}</button></div><p>{guide.vehicle.type} · {guide.vehicle.color} · <b>{guide.vehicle.plate}</b> <a href="#vehicle-photo">{c.vehiclePhoto}</a></p></section><section className="pc-today"><h3>{c.today}</h3>{stops.map((item,index)=><div className={item.id===stop.id?'current':item.status} key={item.id}><i>{item.status==='completed'?'✓':index+1}</i><span><b>{item.name}</b><small>{item.meetingTime} · {item.meetingPointName}</small></span><em>{item.id===stop.id?c.current:item.status==='completed'?c.completed:index===stops.indexOf(stop)+1?c.next:c.upcoming}</em></div>)}</section></div>
}

function MessageView({message,previous,own,acknowledged,originalOpen,onAcknowledge,onOriginal}: {message:ChatMessage;previous?:ChatMessage;own:boolean;language:ChatLanguage;acknowledged:boolean;originalOpen:boolean;onAcknowledge:()=>void;onOriginal:()=>void}){
  if(message.kind==='unread')return <div className="pc-unread"><span>{c.unread}</span></div>;
  if(message.kind==='meeting-change')return <article className={`pc-change-notice ${acknowledged?'acknowledged':''}`}><header><b>! {c.changed}</b><time>{message.time}</time></header><p><del>{message.oldValue}</del><strong>{message.newValue}</strong><small>原因：{message.reason}</small></p>{!acknowledged&&<button onClick={onAcknowledge}>{c.ack}</button>}</article>;
  const merged=previous?.senderId===message.senderId&&previous?.kind==null;
  const display=message.translated??message.content;
  return <article className={`pc-message ${own?'own':'other'} ${merged?'merged':''}`}><div className="pc-avatar" aria-hidden="true">{own?'我':message.name?.slice(0,1)}</div><div className="pc-message-stack">{!merged&&!own&&<header><b>{message.name}</b>{message.role&&message.role!=='passenger'&&<span>{roleLabel[message.role]}</span>}</header>}<div className="pc-bubble"><p>{display}</p>{message.translated&&<small>{c.machineTranslation}</small>}{message.translated&&originalOpen&&<blockquote>{message.content}</blockquote>}</div><div className="pc-message-meta"><time>{message.time}</time><button>{c.reply}</button><button onClick={()=>void navigator.clipboard?.writeText(display??'')}>{c.copy}</button>{message.translated?<button onClick={onOriginal}>{originalOpen?c.hideOriginal:c.original}</button>:<button>{c.translateAction}</button>}</div></div></article>;
}
