import {useState} from 'react';
import {useApp} from './store';
import {getTravelMomentReasonPresentation} from '../shared/travelMomentPresentation';
import {growthCopy} from './growthCopy';
import {passengerOrderCopy} from '../shared/i18n/passengerLocale';

type Props={data:{trips:any[];submissions:any[]};locale:string;refresh:()=>Promise<void>};

export function TravelMomentSubmissionList({data,locale,refresh}:Props){
  const {services}=useApp();
  const localeCopy=growthCopy[locale as keyof typeof growthCopy]??growthCopy['zh-CN'];
  const orderCopy=passengerOrderCopy[locale as keyof typeof passengerOrderCopy]??passengerOrderCopy['zh-CN'];
  const [editing,setEditing]=useState<string|null>(null);
  const [account,setAccount]=useState('');
  const [orderId,setOrderId]=useState('');
  const [url,setUrl]=useState('');
  const [busy,setBusy]=useState<string|null>(null);
  const [notice,setNotice]=useState('');
  const start=(item:any)=>{setEditing(String(item.id));setAccount(String(item.social_account_name??''));setOrderId(String(item.order_id??''));setUrl(String(item.post_url??''));setNotice('')};
  const save=async(item:any)=>{if(!services||busy)return;const id=String(item.id);const reason=Array.isArray(item.reason_codes)?item.reason_codes[0]:undefined;const action=getTravelMomentReasonPresentation(reason,locale).action;if((action==='edit_account'&&!account.trim())||(action==='edit_trip'&&!orderId)||(action==='edit_url'&&!url.trim()))return;setBusy(id);const result=await services.updateOwnTravelMomentSubmission({submissionId:id,orderId:orderId||String(item.order_id),socialAccountName:account.trim()||String(item.social_account_name),url:action==='edit_url'?url:undefined});setBusy(null);if(result.ok){setEditing(null);setNotice(localeCopy.submitted);await refresh()}else{const friendly=getTravelMomentReasonPresentation(result.error??undefined,locale);setNotice(result.error&&friendly.title!==result.error?friendly.message:orderCopy.unavailable)}};
  const recheck=async(id:string)=>{if(!services||busy)return;setBusy(id);const queued=await services.requestTravelMomentRecheck(id);if(queued.ok&&queued.generation)await services.checkTravelMoment({submissionId:id,trigger:'user_recheck',expectedGeneration:queued.generation});setBusy(null);setNotice(queued.error??localeCopy.submitted);await refresh()};
  return <section className="account-section"><h2>{localeCopy.records}</h2>{notice&&<p role="status">{notice}</p>}{data.submissions.map((item:any)=>{const id=String(item.id);const reason=Array.isArray(item.reason_codes)?item.reason_codes[0]:undefined;const fallback=item.status==='checking'?'CHECKING':item.status==='pending_review'?'EXTERNAL_CHECK_UNAVAILABLE':undefined;const present=getTravelMomentReasonPresentation(reason??fallback,locale);const isEditing=editing===id;return <article className="travel-moment-card" key={id}><div><strong>{String(item.platform).toUpperCase()} · {String(item.social_account_name)}</strong><a href={String(item.post_url)} target="_blank" rel="noreferrer">{String(item.post_url)}</a><small>{new Date(String(item.created_at)).toLocaleString(locale)}</small></div><div><strong>{present.title}</strong><small>{present.message}</small>{isEditing&&present.action==='edit_account'&&<label>{localeCopy.handle}<input value={account} onChange={event=>setAccount(event.target.value)}/></label>}{isEditing&&present.action==='edit_trip'&&<label>{localeCopy.chooseTrip}<select value={orderId} onChange={event=>setOrderId(event.target.value)}><option value="">—</option>{data.trips.map((trip:any)=><option key={String(trip.order_id)} value={String(trip.order_id)}>{String(trip.trip_title)} · {new Date(String(trip.departure_at)).toLocaleDateString(locale)}</option>)}</select></label>}{isEditing&&present.action==='edit_url'&&<label>{localeCopy.url}<input type="url" value={url} onChange={event=>setUrl(event.target.value)}/></label>}<div className="account-inline-actions">{isEditing?<><button className="button secondary" disabled={busy===id} onClick={()=>void save(item)}>{busy===id?orderCopy.loading:localeCopy.save}</button><button className="button secondary" onClick={()=>setEditing(null)}>{localeCopy.cancel}</button></>:present.action==='edit_account'||present.action==='edit_trip'||present.action==='edit_url'?<button className="button secondary" onClick={()=>start(item)}>{present.actionLabel}</button>:null}{!isEditing&&present.action==='recheck'&&<button className="button secondary" disabled={busy===id} onClick={()=>void recheck(id)}>{busy===id?orderCopy.loading:present.actionLabel}</button>}</div></div></article>})}{!data.submissions.length&&<p>{localeCopy.noRecords}</p>}</section>;
}
