import {useEffect,useMemo,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {MapSurface} from './MapSurface';
import {useApp} from './store';
import {buildMapMarkers,mapMarkerGlyph,resolveMapSessionMode,type MapMarker} from '../shared/services/mapSession';
import type {MapSessionMode} from '../shared/services/mapSession';
import type {PassengerLocale} from '../shared/i18n/passengerLocale';
import './tripMap.css';

type Room={room_id:string;vehicle_group_id:string;room_status:string};
type Meeting={meeting_at:string;meeting_name:string;meeting_address:string;latitude:number;longitude:number;status:'scheduled'|'active'|'completed'|'cancelled';changed_at?:string};
type Driver={latitude:number;longitude:number;updated_at?:string};
type Stop={id:string;name:string;latitude:number;longitude:number;meetingPointDescription?:string;meetingTime:string};
type Place={id:string;label:string;address:string|null;latitude:number;longitude:number;author_name:string|null;created_at:string};
const copy={
 'zh-CN':{title:'本车地图',loading:'正在读取本车地图…',unavailable:'互动地图暂不可用；仍可使用下方导航。',empty:'暂无可显示的地图点位。',back:'返回本车群',meeting:'前往集合点',find_driver:'寻找本车司机',guide:'区域导览',return_to_meeting:'返回集合点',ended:'行程已结束',locate:'读取我的位置',locating:'正在读取位置…',navigate:'打开导航',guideTitle:'官方建议节点',guideEmpty:'暂无已发布的区域导览节点。',audio:'暂无该语言音频，仍可阅读讲解。',shareTitle:'分享临时地点',shareHint:'点击地图放置 pin，然后填写地点名称。',label:'地点名称',address:'地址或说明（可选）',send:'发送到本车群',cancel:'取消',shared:'本车共享地点',staffOnly:'仅本车司机／导游可分享临时地点。',saved:'地点已发送到本车群。',failed:'地点未发送；请检查房间状态和权限后重试。',permission:'定位未授权；不会把这视为已到达。',stale:'司机位置可能已过期。'},
 'zh-TW':{title:'本車地圖',loading:'正在讀取本車地圖…',unavailable:'互動地圖暫時無法使用；仍可使用下方導航。',empty:'暫無可顯示的地圖點位。',back:'返回本車群',meeting:'前往集合點',find_driver:'尋找本車司機',guide:'區域導覽',return_to_meeting:'返回集合點',ended:'行程已結束',locate:'讀取我的位置',locating:'正在讀取位置…',navigate:'開啟導航',guideTitle:'官方建議節點',guideEmpty:'暫無已發布的區域導覽節點。',audio:'此語言暫無音訊，仍可閱讀講解。',shareTitle:'分享臨時地點',shareHint:'點擊地圖放置 pin，然後填寫地點名稱。',label:'地點名稱',address:'地址或說明（選填）',send:'傳送到本車群',cancel:'取消',shared:'本車共享地點',staffOnly:'僅本車司機／導遊可分享臨時地點。',saved:'地點已傳送到本車群。',failed:'地點未傳送；請檢查房間狀態和權限後重試。',permission:'定位未授權；不會視為已到達。',stale:'司機位置可能已過期。'},
 ja:{title:'車両グループの地図',loading:'車両グループの地図を読み込み中…',unavailable:'インタラクティブ地図は利用できません。下のナビゲーションは使えます。',empty:'表示できる地図ポイントはありません。',back:'車両グループのチャットへ戻る',meeting:'集合場所へ',find_driver:'ドライバーを探す',guide:'エリア案内',return_to_meeting:'集合場所へ戻る',ended:'ツアー終了',locate:'現在地を読み取る',locating:'位置情報を取得中…',navigate:'ナビを開く',guideTitle:'公式おすすめスポット',guideEmpty:'公開済みの案内スポットはありません。',audio:'この言語の音声はありません。説明文をご覧ください。',shareTitle:'一時的な場所を共有',shareHint:'地図をタップしてピンを置き、場所の名前を入力してください。',label:'場所の名前',address:'住所または補足（任意）',send:'車両グループへ送信',cancel:'キャンセル',shared:'車両グループの共有場所',staffOnly:'一時的な場所を共有できるのは、この車両の乗務員のみです。',saved:'場所を車両グループへ送信しました。',failed:'場所を送信できませんでした。部屋の状態と権限を確認してください。',permission:'位置情報は許可されていません。到着扱いにはなりません。',stale:'ドライバー位置が古い可能性があります。'},
 en:{title:'Vehicle map',loading:'Loading your vehicle map…',unavailable:'Interactive map is unavailable. You can still use the navigation links below.',empty:'No map points are available.',back:'Back to vehicle chat',meeting:'Go to meeting point',find_driver:'Find my driver',guide:'Area guide',return_to_meeting:'Return to meeting point',ended:'Trip ended',locate:'Find my location',locating:'Finding location…',navigate:'Open navigation',guideTitle:'Official guide nodes',guideEmpty:'No published guide nodes for this area.',audio:'Audio is not available in this language; the guide text remains available.',shareTitle:'Share a temporary place',shareHint:'Tap the map to place a pin, then name the location.',label:'Place name',address:'Address or note (optional)',send:'Send to vehicle chat',cancel:'Cancel',shared:'Shared by this vehicle',staffOnly:'Only this vehicle’s driver or guide can share a temporary place.',saved:'Place sent to vehicle chat.',failed:'Place was not sent. Check room status and permissions.',permission:'Location permission was not granted. This does not mark you as arrived.',stale:'Driver location may be stale.'},
 ko:{title:'차량 지도',loading:'차량 지도를 불러오는 중…',unavailable:'대화형 지도를 사용할 수 없습니다. 아래 탐색은 계속 사용할 수 있습니다.',empty:'표시할 지도 지점이 없습니다.',back:'차량 채팅으로 돌아가기',meeting:'집합 장소로',find_driver:'기사 찾기',guide:'지역 안내',return_to_meeting:'집합 장소로 돌아가기',ended:'여행 종료',locate:'내 위치 읽기',locating:'위치 확인 중…',navigate:'길찾기 열기',guideTitle:'공식 안내 지점',guideEmpty:'공개된 안내 지점이 없습니다.',audio:'이 언어의 오디오는 없지만 안내문은 볼 수 있습니다.',shareTitle:'임시 장소 공유',shareHint:'지도를 눌러 핀을 놓고 장소 이름을 입력하세요.',label:'장소 이름',address:'주소 또는 메모(선택)',send:'차량 채팅에 보내기',cancel:'취소',shared:'차량 공유 장소',staffOnly:'이 차량의 기사 또는 가이드만 임시 장소를 공유할 수 있습니다.',saved:'차량 채팅에 장소를 보냈습니다.',failed:'장소를 보내지 못했습니다. 방 상태와 권한을 확인하세요.',permission:'위치 권한이 없습니다. 도착 처리되지 않습니다.',stale:'기사 위치가 오래되었을 수 있습니다.'},
 es:{title:'Mapa del vehículo',loading:'Cargando el mapa de tu vehículo…',unavailable:'El mapa interactivo no está disponible. Aún puedes usar la navegación inferior.',empty:'No hay puntos de mapa disponibles.',back:'Volver al chat del vehículo',meeting:'Ir al punto de encuentro',find_driver:'Buscar a mi conductor',guide:'Guía de zona',return_to_meeting:'Volver al punto de encuentro',ended:'Viaje finalizado',locate:'Buscar mi ubicación',locating:'Buscando ubicación…',navigate:'Abrir navegación',guideTitle:'Puntos oficiales de guía',guideEmpty:'No hay puntos de guía publicados para esta zona.',audio:'No hay audio en este idioma; el texto sigue disponible.',shareTitle:'Compartir un lugar temporal',shareHint:'Toca el mapa para colocar un pin y nombra el lugar.',label:'Nombre del lugar',address:'Dirección o nota (opcional)',send:'Enviar al chat del vehículo',cancel:'Cancelar',shared:'Compartido por este vehículo',staffOnly:'Solo el conductor o guía de este vehículo puede compartir un lugar temporal.',saved:'Lugar enviado al chat del vehículo.',failed:'No se pudo enviar el lugar. Comprueba el estado y permiso.',permission:'No se concedió permiso de ubicación. Esto no marca llegada.',stale:'La ubicación del conductor puede estar desactualizada.'},
 vi:{title:'Bản đồ xe',loading:'Đang tải bản đồ xe…',unavailable:'Không dùng được bản đồ tương tác. Bạn vẫn có thể dùng liên kết điều hướng bên dưới.',empty:'Chưa có điểm bản đồ.',back:'Quay lại trò chuyện xe',meeting:'Đến điểm hẹn',find_driver:'Tìm tài xế',guide:'Hướng dẫn khu vực',return_to_meeting:'Quay lại điểm hẹn',ended:'Chuyến đi đã kết thúc',locate:'Đọc vị trí của tôi',locating:'Đang tìm vị trí…',navigate:'Mở điều hướng',guideTitle:'Điểm hướng dẫn chính thức',guideEmpty:'Chưa có điểm hướng dẫn được xuất bản.',audio:'Chưa có âm thanh ngôn ngữ này; bạn vẫn có thể đọc hướng dẫn.',shareTitle:'Chia sẻ địa điểm tạm thời',shareHint:'Chạm bản đồ để đặt ghim, rồi đặt tên địa điểm.',label:'Tên địa điểm',address:'Địa chỉ hoặc ghi chú (tùy chọn)',send:'Gửi vào nhóm xe',cancel:'Hủy',shared:'Địa điểm chung của xe',staffOnly:'Chỉ tài xế hoặc hướng dẫn viên của xe này được chia sẻ địa điểm tạm thời.',saved:'Đã gửi địa điểm vào nhóm xe.',failed:'Không gửi được địa điểm. Kiểm tra trạng thái phòng và quyền.',permission:'Chưa cấp quyền vị trí. Điều này không đánh dấu đã đến.',stale:'Vị trí tài xế có thể đã cũ.'},
 ne:{title:'सवारीको नक्सा',loading:'सवारीको नक्सा लोड हुँदैछ…',unavailable:'अन्तरक्रियात्मक नक्सा उपलब्ध छैन। तलका नेभिगेसन लिङ्क अझै प्रयोग गर्न सकिन्छ।',empty:'देखाउन मिल्ने नक्सा बिन्दु छैन।',back:'सवारी च्याटमा फर्कनुहोस्',meeting:'भेट्ने स्थानमा जानुहोस्',find_driver:'ड्राइभर खोज्नुहोस्',guide:'क्षेत्र गाइड',return_to_meeting:'भेट्ने स्थानमा फर्कनुहोस्',ended:'यात्रा समाप्त',locate:'मेरो स्थान पढ्नुहोस्',locating:'स्थान खोजिँदै…',navigate:'नेभिगेसन खोल्नुहोस्',guideTitle:'आधिकारिक गाइड नोडहरू',guideEmpty:'यस क्षेत्रका प्रकाशित गाइड नोड छैनन्।',audio:'यो भाषामा अडियो छैन; गाइड पाठ पढ्न सकिन्छ।',shareTitle:'अस्थायी स्थान साझा गर्नुहोस्',shareHint:'पिन राख्न नक्सामा ट्याप गरी स्थानको नाम दिनुहोस्।',label:'स्थानको नाम',address:'ठेगाना वा नोट (वैकल्पिक)',send:'सवारी च्याटमा पठाउनुहोस्',cancel:'रद्द',shared:'यस सवारीले साझा गरेको',staffOnly:'यस सवारीका ड्राइभर वा गाइडले मात्र अस्थायी स्थान साझा गर्न सक्छन्।',saved:'स्थान सवारी च्याटमा पठाइयो।',failed:'स्थान पठाउन सकिएन। कोठाको स्थिति र अनुमति जाँच्नुहोस्।',permission:'स्थान अनुमति दिइएन। यसले आगमनको चिन्ह लगाउँदैन।',stale:'ड्राइभरको स्थान पुरानो हुन सक्छ।'}
} as const;
const markerCopy:Record<PassengerLocale,{user:string;driver:string;meeting:string;shared:string;guide:string}>={
 'zh-CN':{user:'我的位置',driver:'本车司机／车辆',meeting:'集合点',shared:'共享地点',guide:'导览节点'},
 'zh-TW':{user:'我的位置',driver:'本車司機／車輛',meeting:'集合點',shared:'共享地點',guide:'導覽節點'},
 ja:{user:'現在地',driver:'この車両のドライバー／車両',meeting:'集合場所',shared:'共有場所',guide:'案内スポット'},
 en:{user:'My location',driver:'My driver / vehicle',meeting:'Meeting point',shared:'Shared place',guide:'Guide node'},
 ko:{user:'내 위치',driver:'내 기사 / 차량',meeting:'집합 장소',shared:'공유 장소',guide:'안내 지점'},
 es:{user:'Mi ubicación',driver:'Mi conductor / vehículo',meeting:'Punto de encuentro',shared:'Lugar compartido',guide:'Punto de guía'},
 vi:{user:'Vị trí của tôi',driver:'Tài xế / xe của tôi',meeting:'Điểm hẹn',shared:'Địa điểm chung',guide:'Điểm hướng dẫn'},
 ne:{user:'मेरो स्थान',driver:'मेरो ड्राइभर / सवारी',meeting:'भेट्ने स्थान',shared:'साझा स्थान',guide:'गाइड नोड'}
};

export function TripMap(){
 const {services,state}=useApp();const [query]=useSearchParams();const group=query.get('vehicleGroup');const locale=state.ui.locale??'zh-CN';const c=copy[locale];
 const [room,setRoom]=useState<Room|null>(null);const [meeting,setMeeting]=useState<Meeting|null>(null);const [driver,setDriver]=useState<Driver|null>(null);const [stops,setStops]=useState<Stop[]>([]);const [places,setPlaces]=useState<Place[]>([]);const [user,setUser]=useState<{latitude:number;longitude:number}|null>(null);const [role,setRole]=useState<string|null>(null);const [error,setError]=useState('');const [selected,setSelected]=useState<MapMarker|null>(null);const [pin,setPin]=useState<{lat:number;lng:number}|null>(null);const [label,setLabel]=useState('');const [address,setAddress]=useState('');const [busy,setBusy]=useState(false);const refreshRef=useRef<()=>Promise<void>>(async()=>{});
 useEffect(()=>{let active=true;let subscription:{close():void}|null=null;if(!services||!group)return;const refresh=async()=>{try{const result=await services.tripRoom.loadAccessibleRoom(group);const next=result.data as Room|null;if(result.error||!next||next.vehicle_group_id!==group)throw Error(result.error||'access_denied');const [nextMeeting,nextDriver,nextStops,nextPlaces,nextRole]=await Promise.all([services.tripRoom.loadCurrentMeeting(group),services.tripRoom.loadDriverLocation(group),services.tripRoom.loadItinerary(group),services.tripRoom.loadSharedPlaces(group),services.currentRole()]);if(!active)return;setRoom(next);setMeeting(nextMeeting as Meeting|null);setDriver(nextDriver as Driver|null);setStops(nextStops as Stop[]);setPlaces(nextPlaces as Place[]);setRole(nextRole);setError('');if(!subscription){const live=await services.realtime.subscribeTripRoom(next.room_id,()=>void refresh(),()=>void refresh(),()=>void refresh());if(active)subscription=live;else live.close()}}catch{if(active)setError('map_load_failed')}};refreshRef.current=refresh;void refresh();const timer=window.setInterval(()=>void refresh(),15000);return()=>{active=false;window.clearInterval(timer);subscription?.close()}},[services,group]);
 const mode:MapSessionMode=resolveMapSessionMode({roomStatus:room?.room_status??'closed',meeting,driver});const guide=stops.map(stop=>({id:stop.id,name:stop.name,latitude:stop.latitude,longitude:stop.longitude,description:stop.meetingPointDescription}));const markerText=markerCopy[locale];const markers=useMemo(()=>buildMapMarkers({roomStatus:room?.room_status??'closed',meeting,driver,user,shared:places,guide,labels:{user:markerText.user,meeting:markerText.meeting,driver:markerText.driver}}),[room,meeting,driver,user,places,stops,markerText]);const assignedStaff=role==='driver'||role==='guide';const target=mode==='find_driver'?'driver':mode==='guide'?'guide':mode==='return_to_meeting'||mode==='meeting'?'meeting':null;const primary=markers.find(marker=>marker.id===target)??selected;
 const locate=()=>{if(!navigator.geolocation){setError('location_unavailable');return}navigator.geolocation.getCurrentPosition(position=>{setUser({latitude:position.coords.latitude,longitude:position.coords.longitude});setError('')},()=>setError('location_denied'),{enableHighAccuracy:true,maximumAge:0,timeout:12000})};
 const createPlace=async()=>{if(!services||!room||!pin||!label.trim()||busy)return;setBusy(true);const result=await services.tripRoom.createSharedPlace(room.room_id,{label:label.trim(),address:address.trim(),latitude:pin.lat,longitude:pin.lng});setBusy(false);if(!result){setError('place_failed');return}setPlaces(rows=>[...rows,result as Place]);setPin(null);setLabel('');setAddress('');setError('place_saved');void refreshRef.current()};
 const navigation=primary?`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${primary.lat},${primary.lng}`)}&travelmode=walking`:null;
 if(!services||!group)return <section className="trip-map-page"><h1>{c.title}</h1><p>{c.empty}</p><Link to="/app/messages">{c.back}</Link></section>;
 return <main className="trip-map-page"><header><Link to={`/app/my-trip/room?vehicleGroup=${encodeURIComponent(group)}`}>‹ {c.back}</Link><small>{c[mode]}</small><h1>{c.title}</h1></header>{error==='map_load_failed'&&<p role="alert">{c.unavailable}</p>}{error==='location_denied'&&<p role="status">{c.permission}</p>}{error==='place_failed'&&<p role="alert">{c.failed}</p>}{error==='place_saved'&&<p role="status">{c.saved}</p>}<MapSurface markers={markers} activeMarkerId={primary?.id} onMarkerClick={setSelected} onMapClick={assignedStaff&&room?.room_status==='open'?point=>{setPin(point);setSelected(null)}:undefined} interactive={Boolean(import.meta.env.VITE_GOOGLE_MAPS_BROWSER_KEY)} emptyLabel={c.loading} unavailableLabel={c.unavailable}/><div className="trip-map-legend">{([{type:'user_location',label:markerText.user},{type:'driver_vehicle',label:markerText.driver},{type:'meeting_point',label:markerText.meeting},{type:'shared_place',label:markerText.shared},{type:'guide_node',label:markerText.guide}] as const).map(item=><span key={item.type}>{mapMarkerGlyph[item.type]} {item.label}</span>)}</div><section className="trip-map-card"><b>{selected?.label??primary?.label??c[mode]}</b>{(selected?.subtitle??primary?.subtitle)&&<p>{selected?.subtitle??primary?.subtitle}</p>}{selected?.type==='guide_node'&&<><p>{selected.subtitle}</p><small>{c.audio}</small></>}{navigation&&<a href={navigation} target="_blank" rel="noreferrer">{c.navigate} →</a>}</section><div className="trip-map-actions"><button type="button" onClick={locate}>{c.locate}</button>{driver&&Date.now()-Date.parse(driver.updated_at??'')>180000&&<small>{c.stale}</small>}</div><section className="trip-map-guide"><h2>{c.guideTitle}</h2>{guide.length?guide.map((node,index)=><button type="button" key={node.id} onClick={()=>setSelected(markers.find(marker=>marker.id===`guide:${node.id}`)??null)}><b>{index+1}. {node.name}</b><span>{node.description}</span></button>):<p>{c.guideEmpty}</p>}</section><section className="trip-map-shared"><h2>{c.shared}</h2>{places.length?places.map(place=><button type="button" key={place.id} onClick={()=>setSelected(markers.find(marker=>marker.id===`shared:${place.id}`)??null)}>📍 {place.label}<small>{place.author_name??''}</small></button>):<p>{c.empty}</p>}</section>{assignedStaff&&room?.room_status==='open'&&<section className="trip-map-share"><h2>{c.shareTitle}</h2>{pin?<><p>{c.shareHint}</p><label>{c.label}<input value={label} onChange={event=>setLabel(event.target.value)} maxLength={120}/></label><label>{c.address}<input value={address} onChange={event=>setAddress(event.target.value)} maxLength={240}/></label><div><button type="button" onClick={()=>{setPin(null);setLabel('');setAddress('')}}>{c.cancel}</button><button type="button" disabled={!label.trim()||busy} onClick={()=>void createPlace()}>{c.send}</button></div></>:<p>{c.shareHint}</p>}</section>}{!assignedStaff&&<p className="trip-map-privacy">{c.staffOnly}</p>}</main>;
}
