import {useCallback,useEffect,useMemo,useState,type FormEvent} from 'react';
import {Link,useLocation,useNavigate,useSearchParams} from 'react-router-dom';
import {travelRepository} from '../shared/data/repository';
import type {VipCharterQuote,VipCharterRequest,VipCharterRouteOption,VipCharterVehicle} from '../shared/integrations/supabaseVipCharter';
import {useApp} from './store';

const osakaWards=['北区','都島区','福島区','此花区','中央区','西区','港区','大正区','天王寺区','浪速区','西淀川区','淀川区','東淀川区','東成区','生野区','旭区','城東区','阿倍野区','住吉区','東住吉区','西成区','鶴見区','住之江区','平野区'];
const todayTokyo=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const yen=(value:number)=>`¥${value.toLocaleString('ja-JP')}`;
const quoteKey=(departureId:string,vehicle:VipCharterVehicle)=>`${departureId}:${vehicle}`;
const requestStatus:Record<string,string>={pending_operations:'待运营确认',reviewing:'运营确认中',quoted:'最终报价已确认',declined:'暂时无法承接',cancelled:'已取消'};

export function VipCharter(){
  const {services,state}=useApp();const location=useLocation();const navigate=useNavigate();const [params,setParams]=useSearchParams();
  const initialDate=params.get('date')??todayTokyo();const initialPassengers=Math.min(9,Math.max(1,Number(params.get('passengers'))||1));
  const [serviceDate,setServiceDate]=useState(initialDate);const [passengers,setPassengers]=useState(initialPassengers);
  const [routeResult,setRouteResult]=useState<{key:string;routes:VipCharterRouteOption[];quotes:Record<string,VipCharterQuote>;error:string}|null>(null);
  const [selected,setSelected]=useState<{route:VipCharterRouteOption;vehicle:VipCharterVehicle}|null>(null);
  const [pickupWard,setPickupWard]=useState('北区');const [pickupAddress,setPickupAddress]=useState('');const [returnAddress,setReturnAddress]=useState('');const [specialRequests,setSpecialRequests]=useState('');
  const [notice,setNotice]=useState('');const [submitting,setSubmitting]=useState(false);const [requests,setRequests]=useState<VipCharterRequest[]>([]);const [idempotencyKey,setIdempotencyKey]=useState(()=>crypto.randomUUID());
  const loadRequests=useCallback(async()=>{if(!services||!state.user)return;const result=await services.loadOwnVipCharterRequests();if(!result.error)setRequests(result.data)},[services,state.user]);
  useEffect(()=>{let active=true;if(services&&state.user)void services.loadOwnVipCharterRequests().then(result=>{if(active&&!result.error)setRequests(result.data)});return()=>{active=false}},[services,state.user]);
  const routeKey=`${serviceDate}:${passengers}`;
  useEffect(()=>{let active=true;setParams({date:serviceDate,passengers:String(passengers)},{replace:true});if(!services)return()=>{active=false};(async()=>{const result=await services.loadVipCharterRoutePrices(serviceDate);if(!active)return;if(result.error){setRouteResult({key:routeKey,routes:[],quotes:{},error:`报价读取失败：${result.error}`});return}const pairs=await Promise.all(result.data.flatMap(route=>(['alphard','hiace'] as VipCharterVehicle[]).filter(vehicle=>vehicle==='hiace'||passengers<=4).map(async vehicle=>({key:quoteKey(route.departureId,vehicle),result:await services.quoteVipCharter(route.departureId,passengers,vehicle)}))));if(active)setRouteResult({key:routeKey,routes:result.data,quotes:Object.fromEntries(pairs.flatMap(item=>item.result.data?[[item.key,item.result.data]]:[])),error:''})})();return()=>{active=false}},[services,serviceDate,passengers,routeKey,setParams]);
  const loading=Boolean(services)&&routeResult?.key!==routeKey;const routes=useMemo(()=>routeResult?.key===routeKey?routeResult.routes:[],[routeResult,routeKey]);const quotes=routeResult?.key===routeKey?routeResult.quotes:{};const routeError=!services?'包车报价服务未配置':routeResult?.key===routeKey?routeResult.error:'';
  const activeQuote=selected?quotes[quoteKey(selected.route.departureId,selected.vehicle)]:null;
  const tripInfo=useMemo(()=>Object.fromEntries(routes.map(route=>[route.tripSlug,travelRepository.getTrip(route.tripSlug)])),[routes]);
  const choose=(route:VipCharterRouteOption,vehicle:VipCharterVehicle)=>{setSelected({route,vehicle});setIdempotencyKey(crypto.randomUUID());setNotice('');requestAnimationFrame(()=>{const target=document.getElementById('vip-charter-request');if(target&&typeof target.scrollIntoView==='function')target.scrollIntoView({behavior:'smooth',block:'start'})})};
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!services||!selected||!activeQuote||submitting)return;if(!state.user){navigate(`/app/login?returnTo=${encodeURIComponent(`${location.pathname}${location.search}`)}`);return}setSubmitting(true);setNotice('');const result=await services.submitVipCharterRequest({departureId:selected.route.departureId,passengerCount:passengers,vehicleType:selected.vehicle,pickupWard,pickupAddress,returnAddress,specialRequests,idempotencyKey});setSubmitting(false);if(result.error){setNotice(`提交失败：${result.error}`);return}setNotice(`包车需求已提交，编号 ${result.data?.requestId.slice(0,8)}。运营确认车辆与地址后再进入付款。`);await loadRequests()};
  return <main className="vip-charter-page">
    <header className="vip-charter-hero"><span>PRIVATE CHARTER</span><h1>VIP 行程包车报价</h1><p>先选择日期和人数，再按该日公开路线价格生成整车报价。包车与普通拼团分开，不占用拼团席位。</p></header>
    <section className="vip-charter-controls" aria-label="报价条件"><label>出发日期<input type="date" min={todayTokyo()} value={serviceDate} onChange={event=>{setSelected(null);setNotice('');setServiceDate(event.target.value)}}/></label><label>出行人数<select value={passengers} onChange={event=>{setSelected(null);setNotice('');setPassengers(Number(event.target.value))}}>{Array.from({length:9},(_,i)=><option key={i+1} value={i+1}>{i+1} 人</option>)}</select></label></section>
    {loading&&<section className="vip-charter-state" aria-live="polite">正在读取所选日期的真实路线价格…</section>}
    {!loading&&routeError&&<section className="vip-charter-state" role="alert"><b>包车报价暂时无法读取</b><p>{routeError}</p></section>}
    {!loading&&!routeError&&routes.length===0&&<section className="vip-charter-state"><b>该日期暂无可生成的公开路线价格</b><p>不会使用其他日期或演示价格替代。可以更换日期，或由运营人员另行确认。</p></section>}
    {!loading&&routes.length>0&&<section className="vip-charter-routes"><header><h2>选择包车路线</h2><small>{serviceDate} · {passengers} 人 · 整车含税参考价</small></header>{routes.map(route=>{const trip=tripInfo[route.tripSlug];const alphard=quotes[quoteKey(route.departureId,'alphard')];const hiace=quotes[quoteKey(route.departureId,'hiace')];const stops=route.stops.length?route.stops:trip?.stops??[];return <article key={route.departureId} className="vip-charter-route-card"><img src={route.heroImageUrl||trip?.heroImage||'/images/vip-alphard-hotel.jpg'} alt=""/><div><span>{new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Tokyo',month:'long',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(route.departsAt))}</span><h3>{route.tripTitle}</h3><p>{stops.slice(0,4).join(' · ')||'路线景点以公开行程为准'}</p><div className="vip-charter-prices">{passengers<=4&&<button type="button" onClick={()=>choose(route,'alphard')} disabled={!alphard}><small>阿尔法 1–4人</small><b>{alphard?`${yen(alphard.totalJpy)}／车`:'读取报价中'}</b><span>选择此行程</span></button>}<button type="button" onClick={()=>choose(route,'hiace')} disabled={!hiace}><small>海狮 最多9人</small><b>{hiace?`${yen(hiace.totalJpy)}／车`:'读取报价中'}</b><span>选择此行程</span></button></div></div></article>})}</section>}
    {selected&&activeQuote&&<form id="vip-charter-request" className="vip-charter-request" onSubmit={submit}><header><span>已选择</span><h2>{selected.route.tripTitle} · {selected.vehicle==='alphard'?'阿尔法':'海狮'}</h2></header><div className="vip-charter-breakdown"><div><span>当日每席价格</span><b>{yen(activeQuote.baseSeatPriceJpy)}</b></div><div><span>车型报价系数</span><b>× {activeQuote.pricingFactor}</b></div><div><span>同一接送点接送费</span><b>{yen(activeQuote.pickupFeeJpy)}</b></div><div className="total"><span>整车合计</span><b>{yen(activeQuote.totalJpy)}／车</b></div></div><p className="vip-charter-rule">整车合计不会再乘人数。普通拼团余位不代表包车车辆可用；车辆、地址及最终费用由运营确认后才能付款。</p><div className="vip-charter-form-grid"><label>大阪市内区域<select value={pickupWard} onChange={event=>setPickupWard(event.target.value)}>{osakaWards.map(ward=><option key={ward}>{ward}</option>)}</select></label><label>大阪市内接送地址<input required minLength={5} value={pickupAddress} onChange={event=>setPickupAddress(event.target.value)} placeholder="例：大阪市北区梅田…"/></label><label className="wide">送回地址（与接送点不同则需运营确认）<input value={returnAddress} onChange={event=>setReturnAddress(event.target.value)} placeholder="留空表示同一接送位置"/></label><label className="wide">其他需求<textarea value={specialRequests} onChange={event=>setSpecialRequests(event.target.value)} placeholder="额外停靠、超出既定路线等需求将转运营确认"/></label></div><button className="button full" disabled={submitting}>{submitting?'正在提交…':state.user?'提交包车需求':'登录后提交包车需求'}</button></form>}
    {notice&&<p className="vip-charter-notice" role="status">{notice}</p>}
    {state.user&&requests.length>0&&<section className="vip-charter-history"><header><h2>我的包车需求</h2><small>刷新后仍可查询</small></header>{requests.map(item=><article key={item.requestId}><div><b>{item.serviceDate} · {item.vehicleType==='alphard'?'阿尔法':'海狮'} · {item.passengerCount}人</b><span>{requestStatus[item.status]??item.status}</span></div><p>{item.pickupWard} {item.pickupAddress}</p><strong>{yen(item.totalJpy)}／车</strong><small>需求编号 {item.requestId.slice(0,8)}</small></article>)}</section>}
    <Link className="vip-charter-group-link" to="/app/private-groups">企业、学校或约30人团体？前往团体咨询 →</Link>
  </main>;
}
