import type {RuntimeMode,VehicleCapacityConfig} from '../types';
import type {FleetVehicleType} from '../operations/fleetOptimizer';
const requestedMode=(import.meta.env.VITE_RUNTIME_MODE||import.meta.env.MODE) as string;
export const runtimeMode:RuntimeMode=requestedMode==='demo'?'demo':requestedMode==='development'?'development':'production';
export const isSeedEnabled=runtimeMode!=='production'&&import.meta.env.VITE_ENABLE_SEED_DATA!=='false';
const fleetVehicleTypes=[{type:'alphard-6',label:'Alphard（6客席）',capacity:6,costUnits:30},{type:'hiace-13',label:'Hiace（13客席）',capacity:13,costUnits:40},{type:'coaster-20',label:'Coaster（20客席，待运营确认）',capacity:20,costUnits:55},{type:'bus-55',label:'大型巴士（55客席）',capacity:55,costUnits:100}] satisfies FleetVehicleType[];
export const appConfig={locale:'zh-CN',supportedLocales:['zh-CN'] as const,runtimeMode,isSeedEnabled,fleetVehicleTypes,vehicleCapacities:fleetVehicleTypes.map(({type,label,capacity})=>({type,label,capacity})) satisfies VehicleCapacityConfig[],commerce:{currency:'JPY',seatPrice:null,priceStatus:'待运营发布',inventoryStatus:'以服务端权威库存为准',infantSeatRule:'婴儿是否占用客席及最终费用由运营确认',unconfirmedAssistanceCharge:false},tripRoom:{opens:'出发前一晚（具体时间由运营确认）',locationShareMinutes:[15,30] as const,passengerLocationDefault:false,locationVisibleTo:['driver','guide'] as const,attendance:{confirmDepartureMinutes:60,arrivalCheckinMinutes:30,firstReminderMinutesBefore:10,staffContactMinutesAfter:5}},loadFactorTargetPercent:80,externalCapabilities:{api:false,authentication:false,payment:false,inventory:false,maps:false,gps:false,chat:false,notifications:false,dispatch:false},features:{booking:true,privateGroups:true,rewards:true,tripRoom:true,staffView:true,operationsDispatch:true}} as const;
export const businessRules={firstValidOrderDiscountPercent:5,referrerCreditPercent:5,creditValidityDays:180,creditPerOrderCapYen:1000,ambassadorCommissionPercent:5,loadFactorTargetPercent:appConfig.loadFactorTargetPercent,allocationPrinciple:'sequential-fill' as const,tiers:[{name:'探索者',trips:0},{name:'旅行者',trips:2},{name:'达人',trips:3},{name:'VIP 旅行者',trips:5}] as const};
export function tierFor(completed:number){return [...businessRules.tiers].reverse().find(t=>completed>=t.trips)??businessRules.tiers[0]}
export function nextTier(completed:number){return businessRules.tiers.find(t=>t.trips>completed)}
