import type {RuntimeMode} from '../types';
export const clientEnvironmentContract={VITE_RUNTIME_MODE:'公开：production、development 或 demo',VITE_API_BASE_URL:'公开：正式 API 的 HTTPS 基址',VITE_ENABLE_SEED_DATA:'公开：仅非 production 可使用的种子开关',VITE_SUPABASE_URL:'公开：Supabase 项目 URL',VITE_SUPABASE_PUBLISHABLE_KEY:'公开：publishable/anon key，权限依赖 RLS',VITE_GOOGLE_MAPS_BROWSER_KEY:'公开：必须限制网站来源和 API'} as const;
export const serverEnvironmentContract={SUPABASE_URL:'服务端：Supabase 项目 URL',SUPABASE_SERVICE_ROLE_KEY:'秘密：绕过 RLS，仅服务端',DATABASE_ENCRYPTION_KEY:'秘密：敏感字段加密',SESSION_SIGNING_SECRET:'秘密：会话签名',STRIPE_SECRET_KEY:'秘密：仅 sk_test_ 测试密钥',STRIPE_WEBHOOK_SECRET:'秘密：Stripe Webhook 签名验证',GOOGLE_MAPS_SERVER_KEY:'秘密：服务端地图密钥',NOTIFICATION_PROVIDER:'非秘密：已批准通知 provider 标识',NOTIFICATION_API_KEY:'秘密：通知服务端密钥',NOTIFICATION_WEBHOOK_SECRET:'秘密：通知回调签名验证'} as const;
export type CapabilityName='backend'|'authentication'|'database'|'payment'|'maps'|'realtime'|'notifications';export type CapabilityState={enabled:boolean;reason:string};
export type IntegrationReadiness={ready:boolean;client:{runtimeMode:string|undefined;apiBaseUrl:string|undefined;seedEnabled:string|undefined};capabilities:Record<CapabilityName,CapabilityState>};
const secretPattern=/(SECRET|PRIVATE|PASSWORD|DATABASE_URL|SERVICE_KEY|WEBHOOK_SECRET|API_KEY)/i;
export function safeClientConfig(env:Record<string,string|undefined>){const publicKeys=new Set(Object.keys(clientEnvironmentContract));const unsafe=Object.keys(env).filter(key=>key.startsWith('VITE_')&&(!publicKeys.has(key)||secretPattern.test(key)&&key!=='VITE_SUPABASE_PUBLISHABLE_KEY'&&key!=='VITE_GOOGLE_MAPS_BROWSER_KEY'));if(unsafe.length)throw new Error(`客户端环境变量包含未批准项或疑似服务端秘密：${unsafe.join(', ')}`);return {runtimeMode:env.VITE_RUNTIME_MODE,apiBaseUrl:env.VITE_API_BASE_URL,seedEnabled:env.VITE_ENABLE_SEED_DATA}}
const has=(env:Record<string,string|undefined>,names:string[])=>names.every(name=>Boolean(env[name]?.trim()));
export function validateIntegrationReadiness(input:{mode:RuntimeMode;clientEnv:Record<string,string|undefined>;serverEnv:Record<string,string|undefined>}):IntegrationReadiness{const client=safeClientConfig(input.clientEnv);if(input.mode!=='production'){const localState={enabled:false,reason:'非 production 使用显式本地 provider，未连接真实服务'};return {ready:true,client,capabilities:{backend:localState,authentication:localState,database:localState,payment:localState,maps:localState,realtime:localState,notifications:localState}}}const states:Record<CapabilityName,CapabilityState>={backend:{enabled:Boolean(client.apiBaseUrl?.startsWith('https://')),reason:'需要 VITE_API_BASE_URL（HTTPS）'},database:{enabled:has(input.serverEnv,['SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY','DATABASE_ENCRYPTION_KEY']),reason:'需要 Supabase 服务端连接和字段加密密钥'},authentication:{enabled:has(input.serverEnv,['SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY','SESSION_SIGNING_SECRET']),reason:'需要 Supabase 服务端认证配置'},payment:{enabled:has(input.serverEnv,['STRIPE_SECRET_KEY','STRIPE_WEBHOOK_SECRET'])&&input.serverEnv.STRIPE_SECRET_KEY?.startsWith('sk_test_')===true,reason:'仅接受 Stripe 测试密钥和 Webhook 签名密钥'},maps:{enabled:Boolean(input.clientEnv.VITE_GOOGLE_MAPS_BROWSER_KEY?.trim()),reason:'需要受网站来源和 API 限制的浏览器 Maps key'},realtime:{enabled:has(input.serverEnv,['SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY']),reason:'需要 Supabase 私有 Realtime 服务端鉴权'},notifications:{enabled:has(input.serverEnv,['NOTIFICATION_PROVIDER','NOTIFICATION_API_KEY','NOTIFICATION_WEBHOOK_SECRET']),reason:'需要已批准通知 provider、服务端密钥和回调签名密钥'}};return {ready:Object.values(states).every(state=>state.enabled),client,capabilities:states}}
export interface RealtimeProvider{connected:boolean;subscribePrivateVehicleGroup(input:{accountId:string;vehicleGroupId:string;authorizationToken:string}):Promise<{subscribed:boolean;close():void}>}
export const unavailableRealtimeProvider:RealtimeProvider={connected:false,subscribePrivateVehicleGroup:async()=>({subscribed:false,close(){}})};
