import type {RuntimeMode} from '../types';
export const clientEnvironmentContract={VITE_RUNTIME_MODE:'公开：production、development 或 demo',VITE_API_BASE_URL:'公开：正式 API 的 HTTPS 基址',VITE_ENABLE_SEED_DATA:'公开：仅非 production 可使用的种子开关'} as const;
export const serverEnvironmentContract={DATABASE_URL:'秘密：数据库连接',DATABASE_ENCRYPTION_KEY:'秘密：敏感字段加密',SESSION_SIGNING_SECRET:'秘密：会话签名',PAYMENT_PROVIDER:'非秘密：已批准支付 provider 标识',PAYMENT_SECRET_KEY:'秘密：支付服务端密钥',PAYMENT_WEBHOOK_SECRET:'秘密：支付 Webhook 签名验证',MAPS_PROVIDER:'非秘密：已批准地图 provider 标识',MAPS_SERVER_KEY:'秘密：服务端地图密钥',REALTIME_PROVIDER:'非秘密：已批准 realtime provider 标识',REALTIME_SERVICE_KEY:'秘密：服务端 realtime 管理密钥',NOTIFICATION_PROVIDER:'非秘密：已批准通知 provider 标识',NOTIFICATION_API_KEY:'秘密：通知服务端密钥',NOTIFICATION_WEBHOOK_SECRET:'秘密：通知回调签名验证'} as const;
export type CapabilityName='backend'|'authentication'|'database'|'payment'|'maps'|'realtime'|'notifications';export type CapabilityState={enabled:boolean;reason:string};
export type IntegrationReadiness={ready:boolean;client:{runtimeMode:string|undefined;apiBaseUrl:string|undefined;seedEnabled:string|undefined};capabilities:Record<CapabilityName,CapabilityState>};
const secretPattern=/(SECRET|PRIVATE|PASSWORD|DATABASE_URL|SERVICE_KEY|WEBHOOK_SECRET|API_KEY)/i;
export function safeClientConfig(env:Record<string,string|undefined>){const unsafe=Object.keys(env).filter(key=>key.startsWith('VITE_')&&secretPattern.test(key));if(unsafe.length)throw new Error(`客户端环境变量包含疑似服务端秘密：${unsafe.join(', ')}`);return {runtimeMode:env.VITE_RUNTIME_MODE,apiBaseUrl:env.VITE_API_BASE_URL,seedEnabled:env.VITE_ENABLE_SEED_DATA}}
const has=(env:Record<string,string|undefined>,names:string[])=>names.every(name=>Boolean(env[name]?.trim()));
export function validateIntegrationReadiness(input:{mode:RuntimeMode;clientEnv:Record<string,string|undefined>;serverEnv:Record<string,string|undefined>}):IntegrationReadiness{const client=safeClientConfig(input.clientEnv);if(input.mode!=='production'){const localState={enabled:false,reason:'非 production 使用显式本地 provider，未连接真实服务'};return {ready:true,client,capabilities:{backend:localState,authentication:localState,database:localState,payment:localState,maps:localState,realtime:localState,notifications:localState}}}const states:Record<CapabilityName,CapabilityState>={backend:{enabled:Boolean(client.apiBaseUrl?.startsWith('https://')),reason:'需要 VITE_API_BASE_URL（HTTPS）'},database:{enabled:has(input.serverEnv,['DATABASE_URL','DATABASE_ENCRYPTION_KEY']),reason:'需要数据库连接和字段加密密钥'},authentication:{enabled:has(input.serverEnv,['SESSION_SIGNING_SECRET']),reason:'需要服务端会话签名密钥'},payment:{enabled:has(input.serverEnv,['PAYMENT_PROVIDER','PAYMENT_SECRET_KEY','PAYMENT_WEBHOOK_SECRET']),reason:'需要已批准 provider、服务端密钥和 Webhook 签名密钥'},maps:{enabled:has(input.serverEnv,['MAPS_PROVIDER','MAPS_SERVER_KEY']),reason:'需要已批准地图 provider 和服务端密钥'},realtime:{enabled:has(input.serverEnv,['REALTIME_PROVIDER','REALTIME_SERVICE_KEY']),reason:'需要已批准 realtime provider 和服务端管理密钥'},notifications:{enabled:has(input.serverEnv,['NOTIFICATION_PROVIDER','NOTIFICATION_API_KEY','NOTIFICATION_WEBHOOK_SECRET']),reason:'需要已批准通知 provider、服务端密钥和回调签名密钥'}};return {ready:Object.values(states).every(state=>state.enabled),client,capabilities:states}}
export interface RealtimeProvider{connected:boolean;subscribePrivateVehicleGroup(input:{accountId:string;vehicleGroupId:string;authorizationToken:string}):Promise<{subscribed:boolean;close():void}>}
export const unavailableRealtimeProvider:RealtimeProvider={connected:false,subscribePrivateVehicleGroup:async()=>({subscribed:false,close(){}})};
