import type {SupabaseClient} from '@supabase/supabase-js';

export type VipCharterVehicle='alphard'|'hiace';
export type VipCharterRouteOption={departureId:string;tripId:string;tripSlug:string;tripTitle:string;departsAt:string;baseSeatPriceJpy:number;heroImageUrl:string|null;stops:string[]};
export type VipCharterQuote={departureId:string;tripId:string;serviceDate:string;vehicleType:VipCharterVehicle;baseSeatPriceJpy:number;pricingFactor:number;pickupFeeJpy:number;totalJpy:number};
export type VipCharterRequest=VipCharterQuote&{requestId:string;passengerCount:number;pickupWard:string;pickupAddress:string;returnAddress:string|null;specialRequests:string|null;status:string;createdAt:string;accountId?:string;tripTitle?:string};

const option=(row:Record<string,unknown>):VipCharterRouteOption=>({departureId:String(row.departure_id),tripId:String(row.trip_id),tripSlug:String(row.trip_slug),tripTitle:String(row.trip_title),departsAt:String(row.departs_at),baseSeatPriceJpy:Number(row.base_seat_price_jpy),heroImageUrl:row.hero_image_url?String(row.hero_image_url):null,stops:Array.isArray(row.stops)?row.stops.map(String):[]});
const quote=(row:Record<string,unknown>):VipCharterQuote=>({departureId:String(row.departure_id),tripId:String(row.trip_id),serviceDate:String(row.service_date),vehicleType:String(row.vehicle_type) as VipCharterVehicle,baseSeatPriceJpy:Number(row.base_seat_price_jpy),pricingFactor:Number(row.pricing_factor),pickupFeeJpy:Number(row.pickup_fee_jpy),totalJpy:Number(row.total_jpy)});
const request=(row:Record<string,unknown>):VipCharterRequest=>({...quote(row),requestId:String(row.request_id),accountId:row.account_id?String(row.account_id):undefined,tripTitle:row.trip_title?String(row.trip_title):undefined,passengerCount:Number(row.passenger_count),pickupWard:String(row.pickup_ward),pickupAddress:String(row.pickup_address),returnAddress:row.return_address?String(row.return_address):null,specialRequests:row.special_requests?String(row.special_requests):null,status:String(row.status),createdAt:String(row.created_at)});

export class SupabaseVipCharterRepository{
  constructor(private readonly client:SupabaseClient|null){}
  async listRoutePrices(serviceDate:string){if(!this.client)return {data:[] as VipCharterRouteOption[],error:'包车报价服务未配置'};const {data,error}=await this.client.rpc('list_vip_charter_route_prices',{p_service_date:serviceDate});return {data:((data??[]) as Record<string,unknown>[]).map(option),error:error?.message??null}}
  async getQuote(departureId:string,passengerCount:number,vehicleType:VipCharterVehicle){if(!this.client)return {data:null as VipCharterQuote|null,error:'包车报价服务未配置'};const {data,error}=await this.client.rpc('quote_vip_charter',{p_departure:departureId,p_passenger_count:passengerCount,p_vehicle_type:vehicleType});const row=(data as Record<string,unknown>[]|null)?.[0];return {data:row?quote(row):null,error:error?.message??(!row?'无法生成包车报价':null)}}
  async submit(input:{departureId:string;passengerCount:number;vehicleType:VipCharterVehicle;pickupWard:string;pickupAddress:string;returnAddress:string;specialRequests:string;idempotencyKey:string}){if(!this.client)return {data:null as {requestId:string;status:string;totalJpy:number;createdAt:string}|null,error:'包车需求服务未配置'};const {data,error}=await this.client.rpc('submit_vip_charter_request',{p_departure:input.departureId,p_passenger_count:input.passengerCount,p_vehicle_type:input.vehicleType,p_pickup_ward:input.pickupWard,p_pickup_address:input.pickupAddress,p_return_address:input.returnAddress||null,p_special_requests:input.specialRequests||null,p_idempotency_key:input.idempotencyKey});const row=(data as Record<string,unknown>[]|null)?.[0];return {data:row?{requestId:String(row.request_id),status:String(row.status),totalJpy:Number(row.total_jpy),createdAt:String(row.created_at)}:null,error:error?.message??(!row?'包车需求提交失败':null)}}
  async listOwn(){if(!this.client)return {data:[] as VipCharterRequest[],error:'包车需求服务未配置'};const {data,error}=await this.client.rpc('get_own_vip_charter_requests');return {data:((data??[]) as Record<string,unknown>[]).map(request),error:error?.message??null}}
  async listOperations(){if(!this.client)return {data:[] as VipCharterRequest[],error:'运营数据服务未配置'};const {data,error}=await this.client.rpc('get_operations_vip_charter_requests');return {data:((data??[]) as Record<string,unknown>[]).map(request),error:error?.message??null}}
}
