import type {SupabaseClient} from '@supabase/supabase-js';

export type OperationsVehicleType={type_key:string;label:string;sellable_capacity:number;cost_units:number;active:boolean};
export type OperationsVehicle={id:string;registration_identifier:string;vehicle_type_key:string;external_dispatch_id:string|null;status:'available'|'assigned'|'in_service'|'maintenance'|'inactive'};
export type OperationsDriver={id:string;display_name:string;external_dispatch_id:string|null;languages:string[];status:'available'|'unavailable'|'suspended';driver_vehicle_qualifications:{vehicle_type_key:string}[];driver_availability_windows:{starts_at:string;ends_at:string}[]};
export type OperationsSnapshot={vehicleTypes:OperationsVehicleType[];vehicles:OperationsVehicle[];drivers:OperationsDriver[];dispatchDrafts:number;loadedAt:string};

export class SupabaseOperationsRepository{
  constructor(private readonly client:SupabaseClient|null){}
  get available(){return this.client!==null}
  async loadSnapshot():Promise<{data:OperationsSnapshot|null;error:string|null}>{if(!this.client)return {data:null,error:'运营数据服务未配置'};try{const [types,vehicles,drivers,tasks]=await Promise.all([this.client.from('vehicle_type_configs').select('type_key,label,sellable_capacity,cost_units,active').eq('active',true).order('sellable_capacity'),this.client.from('fleet_vehicles').select('id,registration_identifier,vehicle_type_key,external_dispatch_id,status').order('registration_identifier'),this.client.from('driver_resources').select('id,display_name,external_dispatch_id,languages,status,driver_vehicle_qualifications(vehicle_type_key),driver_availability_windows(starts_at,ends_at)').order('display_name'),this.client.from('dispatch_tasks').select('id',{count:'exact',head:true}).in('status',['draft','confirmed'])]);if(types.error||vehicles.error||drivers.error||tasks.error)return {data:null,error:'运营数据读取失败，请确认021迁移与运营权限'};return {data:{vehicleTypes:(types.data??[]) as OperationsVehicleType[],vehicles:(vehicles.data??[]) as OperationsVehicle[],drivers:(drivers.data??[]) as OperationsDriver[],dispatchDrafts:tasks.count??0,loadedAt:new Date().toISOString()},error:null}}catch{return {data:null,error:'运营数据读取失败'}}}
  async createVehicle(input:{registration:string;vehicleType:string;externalDispatchId:string}){if(!this.client)return false;const {error}=await this.client.rpc('operations_create_vehicle',{p_registration:input.registration,p_vehicle_type:input.vehicleType,p_external_dispatch_id:input.externalDispatchId||null});return !error}
  async createDriver(input:{displayName:string;externalDispatchId:string;vehicleTypes:string[];languages:string[];availableFrom:string;availableUntil:string}){if(!this.client)return false;const {error}=await this.client.rpc('operations_create_driver',{p_display_name:input.displayName,p_external_dispatch_id:input.externalDispatchId||null,p_vehicle_types:input.vehicleTypes,p_languages:input.languages,p_available_from:input.availableFrom,p_available_until:input.availableUntil});return !error}
}
