begin;

create extension if not exists pgcrypto;
create type public.app_role as enum ('passenger','operations','driver','guide');
create type public.order_status as enum ('pending_payment','paid','confirmed','cancelled','refunded','expired');
create type public.hold_status as enum ('held','committed','released','expired');
create type public.payment_status as enum ('created','processing','succeeded','failed','cancelled','refunded');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null default '', role public.app_role not null default 'passenger', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.trips (id uuid primary key default gen_random_uuid(), slug text not null unique, title text not null, status text not null check(status in ('draft','published','archived')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.departures (id uuid primary key default gen_random_uuid(), trip_id uuid not null references public.trips(id), departs_at timestamptz, capacity integer not null check(capacity>0), status text not null check(status in ('draft','open','closed','completed','cancelled')), meeting_name text, meeting_address text, map_lat numeric(9,6), map_lng numeric(9,6), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.orders (id uuid primary key default gen_random_uuid(), account_id uuid not null references public.profiles(id), departure_id uuid not null references public.departures(id), idempotency_key text not null, seat_count integer not null check(seat_count>0), status public.order_status not null default 'pending_payment', currency text not null default 'JPY' check(currency='JPY'), amount integer check(amount is null or amount>=0), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(account_id,idempotency_key));
create table public.passengers (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, display_name text not null, passenger_type text not null check(passenger_type in ('adult','child')), created_at timestamptz not null default now());
create table public.passenger_assistance (order_id uuid primary key references public.orders(id) on delete cascade, encrypted_payload text not null, review_status text not null check(review_status in ('not_requested','reviewing','manual_contact','confirmed','unavailable')), updated_at timestamptz not null default now());
create table public.inventory_locks (id uuid primary key default gen_random_uuid(), departure_id uuid not null references public.departures(id), order_id uuid references public.orders(id), idempotency_key text not null unique, seats integer not null check(seats>0), status public.hold_status not null default 'held', expires_at timestamptz not null, created_at timestamptz not null default now());
create table public.vehicle_assignments (id uuid primary key default gen_random_uuid(), departure_id uuid not null references public.departures(id), sequence integer not null check(sequence>0), vehicle_type text not null, capacity integer not null check(capacity>0), created_at timestamptz not null default now(), unique(departure_id,sequence));
create table public.vehicle_groups (id uuid primary key default gen_random_uuid(), departure_id uuid not null references public.departures(id), vehicle_assignment_id uuid not null unique references public.vehicle_assignments(id), created_at timestamptz not null default now());
create table public.vehicle_group_orders (vehicle_group_id uuid not null references public.vehicle_groups(id) on delete cascade, order_id uuid not null unique references public.orders(id), primary key(vehicle_group_id,order_id));
create table public.staff_assignments (id uuid primary key default gen_random_uuid(), vehicle_group_id uuid not null references public.vehicle_groups(id), staff_id uuid not null references public.profiles(id), role public.app_role not null check(role in ('operations','driver','guide')), unique(vehicle_group_id,staff_id));
create table public.trip_rooms (id uuid primary key default gen_random_uuid(), vehicle_group_id uuid not null unique references public.vehicle_groups(id), opens_at timestamptz, status text not null check(status in ('frozen','open','closed')), created_at timestamptz not null default now());
create table public.trip_room_messages (id uuid primary key default gen_random_uuid(), trip_room_id uuid not null references public.trip_rooms(id) on delete cascade, author_id uuid not null references public.profiles(id), content text not null check(length(content) between 1 and 2000), created_at timestamptz not null default now());
create table public.location_shares (id uuid primary key default gen_random_uuid(), vehicle_group_id uuid not null references public.vehicle_groups(id), subject_id uuid not null references public.profiles(id), scope text not null check(scope='assigned_staff_only'), started_at timestamptz not null, stopped_at timestamptz, expires_at timestamptz not null, encrypted_location text, check(expires_at>started_at));
create table public.boardings (id uuid primary key default gen_random_uuid(), order_id uuid not null unique references public.orders(id), status text not null check(status in ('not_issued','issued','boarded','revoked')), boarded_at timestamptz, updated_at timestamptz not null default now());
create table public.payment_events (id uuid primary key default gen_random_uuid(), provider text not null check(provider='stripe'), provider_event_id text not null unique, order_id uuid references public.orders(id), status public.payment_status not null, event_created_at timestamptz not null, received_at timestamptz not null default now(), payload_digest text not null);

create or replace function public.is_operations() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from profiles where id=auth.uid() and role='operations')$$;
create or replace function public.is_order_owner(target uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from orders where id=target and account_id=auth.uid())$$;
create or replace function public.is_group_staff(target uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from staff_assignments where vehicle_group_id=target and staff_id=auth.uid())$$;

alter table public.profiles enable row level security; alter table public.trips enable row level security; alter table public.departures enable row level security; alter table public.orders enable row level security; alter table public.passengers enable row level security; alter table public.passenger_assistance enable row level security; alter table public.inventory_locks enable row level security; alter table public.vehicle_assignments enable row level security; alter table public.vehicle_groups enable row level security; alter table public.vehicle_group_orders enable row level security; alter table public.staff_assignments enable row level security; alter table public.trip_rooms enable row level security; alter table public.trip_room_messages enable row level security; alter table public.location_shares enable row level security; alter table public.boardings enable row level security; alter table public.payment_events enable row level security;
create policy profiles_self_or_ops on public.profiles for select using(id=auth.uid() or public.is_operations());
create policy published_trips on public.trips for select using(status='published' or public.is_operations());
create policy open_departures on public.departures for select using(status in ('open','closed','completed') or public.is_operations());
create policy orders_owner_or_ops on public.orders for select using(account_id=auth.uid() or public.is_operations());
create policy passengers_owner_or_ops on public.passengers for select using(public.is_order_owner(order_id) or public.is_operations());
create policy assistance_owner_or_ops on public.passenger_assistance for select using(public.is_order_owner(order_id) or public.is_operations());
create policy groups_member_staff_ops on public.vehicle_groups for select using(public.is_operations() or public.is_group_staff(id) or exists(select 1 from vehicle_group_orders vgo join orders o on o.id=vgo.order_id where vgo.vehicle_group_id=id and o.account_id=auth.uid()));
create policy rooms_member_staff_ops on public.trip_rooms for select using(public.is_operations() or public.is_group_staff(vehicle_group_id) or exists(select 1 from vehicle_group_orders vgo join orders o on o.id=vgo.order_id where vgo.vehicle_group_id=trip_rooms.vehicle_group_id and o.account_id=auth.uid()));
create policy messages_room_members on public.trip_room_messages for select using(exists(select 1 from trip_rooms r where r.id=trip_room_id and (public.is_operations() or public.is_group_staff(r.vehicle_group_id) or exists(select 1 from vehicle_group_orders vgo join orders o on o.id=vgo.order_id where vgo.vehicle_group_id=r.vehicle_group_id and o.account_id=auth.uid()))));
create policy locations_subject_or_staff_ops on public.location_shares for select using(subject_id=auth.uid() or public.is_operations() or public.is_group_staff(vehicle_group_id));
create policy inventory_owner_or_ops on public.inventory_locks for select using(public.is_operations() or order_id is not null and public.is_order_owner(order_id));
create policy boarding_owner_or_ops on public.boardings for select using(public.is_order_owner(order_id) or public.is_operations());
create policy payment_owner_or_ops on public.payment_events for select using(order_id is not null and public.is_order_owner(order_id) or public.is_operations());

create or replace function public.reserve_inventory(p_departure uuid,p_account uuid,p_seats integer,p_key text,p_expires timestamptz) returns table(order_id uuid,hold_id uuid) language plpgsql security definer set search_path=public as $$declare d departures%rowtype; used integer; o uuid; h uuid; begin if p_seats<=0 or p_expires<=now() then raise exception 'invalid hold'; end if; select * into d from departures where id=p_departure for update; if not found or d.status<>'open' then raise exception 'departure unavailable'; end if; select coalesce(sum(seats),0) into used from inventory_locks where departure_id=p_departure and (status='committed' or (status='held' and expires_at>now())); if used+p_seats>d.capacity then raise exception 'insufficient inventory'; end if; insert into orders(account_id,departure_id,idempotency_key,seat_count) values(p_account,p_departure,p_key,p_seats) on conflict(account_id,idempotency_key) do update set updated_at=orders.updated_at returning id into o; insert into inventory_locks(departure_id,order_id,idempotency_key,seats,expires_at) values(p_departure,o,p_key,p_seats,p_expires) on conflict(idempotency_key) do update set idempotency_key=excluded.idempotency_key returning id into h; return query select o,h; end$$;
create or replace function public.apply_payment_event(p_event_id text,p_order uuid,p_status public.payment_status,p_created timestamptz,p_digest text) returns boolean language plpgsql security definer set search_path=public as $$declare newest timestamptz; begin insert into payment_events(provider,provider_event_id,order_id,status,event_created_at,payload_digest) values('stripe',p_event_id,p_order,p_status,p_created,p_digest) on conflict(provider_event_id) do nothing; if not found then return false; end if; select max(event_created_at) into newest from payment_events where order_id=p_order and status in ('succeeded','refunded'); if p_status='succeeded' and (newest is null or p_created>=newest) then update orders set status='paid',updated_at=now() where id=p_order and status='pending_payment'; update inventory_locks set status='committed' where order_id=p_order and status='held' and expires_at>now(); elsif p_status='refunded' and (newest is null or p_created>=newest) then update orders set status='refunded',updated_at=now() where id=p_order and status in ('paid','confirmed'); end if; return true; end$$;
create or replace function public.release_expired_inventory() returns integer language plpgsql security definer set search_path=public as $$declare count_released integer; begin update inventory_locks set status='expired' where status='held' and expires_at<=now(); get diagnostics count_released=row_count; update orders o set status='expired',updated_at=now() where status='pending_payment' and exists(select 1 from inventory_locks l where l.order_id=o.id and l.status='expired'); return count_released; end$$;
create or replace function public.cancel_pending_order(p_order uuid,p_account uuid) returns boolean language plpgsql security definer set search_path=public as $$begin update orders set status='cancelled',updated_at=now() where id=p_order and account_id=p_account and status='pending_payment'; if not found then return false; end if; update inventory_locks set status='released' where order_id=p_order and status='held'; return true; end$$;
revoke all on function public.reserve_inventory(uuid,uuid,integer,text,timestamptz) from public;
revoke all on function public.apply_payment_event(text,uuid,public.payment_status,timestamptz,text) from public;
revoke all on function public.release_expired_inventory() from public;
revoke all on function public.cancel_pending_order(uuid,uuid) from public;
commit;
