begin;
create table public.product_merchandising(trip_id uuid primary key references public.trips(id) on delete cascade,featured_rank integer check(featured_rank is null or featured_rank between 1 and 999),campaign_key text,visible_from timestamptz,visible_until timestamptz,travel_from date,travel_until date,locale_readiness jsonb not null default '{}'::jsonb,version integer not null default 1 check(version>0),updated_by uuid references public.profiles(id),updated_at timestamptz not null default now(),check(visible_until is null or visible_from is null or visible_until>visible_from),check(travel_until is null or travel_from is null or travel_until>=travel_from));
alter table public.product_merchandising enable row level security;
revoke all on public.product_merchandising from public,anon,authenticated;grant all on public.product_merchandising to service_role;
create policy operations_merchandising_read on public.product_merchandising for select to authenticated using(public.is_operations());
insert into public.product_merchandising(trip_id,featured_rank,campaign_key,travel_from,travel_until)
select id,case slug when 'kyoto-nara-classic' then 10 when 'amanohashidate-ine' then 20 when 'biwako-shirahige' then 30 when 'arashiyama-train-hozugawa' then 40 when 'sanzenin-kibune-arashiyama-autumn' then 50 else 100+row_number() over(order by slug) end,case when slug='sanzenin-kibune-arashiyama-autumn' then 'autumn-leaves' end,case when slug='sanzenin-kibune-arashiyama-autumn' then make_date(extract(year from now())::int,10,15) end,case when slug='sanzenin-kibune-arashiyama-autumn' then make_date(extract(year from now())::int,12,10) end from public.trips on conflict(trip_id) do nothing;
create or replace function public.get_operations_merchandising() returns table(trip_id uuid,slug text,title text,featured_rank integer,campaign_key text,visible_from timestamptz,visible_until timestamptz,travel_from date,travel_until date,locale_readiness jsonb,version integer,updated_at timestamptz) language sql stable security definer set search_path=public,pg_temp as $$select t.id,t.slug,t.title,m.featured_rank,m.campaign_key,m.visible_from,m.visible_until,m.travel_from,m.travel_until,m.locale_readiness,m.version,m.updated_at from public.trips t left join public.product_merchandising m on m.trip_id=t.id where public.is_operations() order by m.featured_rank nulls last,t.title$$;
create or replace function public.operations_update_merchandising(p_trip uuid,p_expected_version integer,p_featured_rank integer,p_campaign_key text,p_visible_from timestamptz,p_visible_until timestamptz,p_travel_from date,p_travel_until date,p_locale_readiness jsonb) returns integer language plpgsql security definer set search_path=public,pg_temp as $$declare v_version integer;begin if not public.is_operations() then raise exception 'operations only';end if;insert into public.product_merchandising(trip_id,featured_rank,campaign_key,visible_from,visible_until,travel_from,travel_until,locale_readiness,updated_by) values(p_trip,p_featured_rank,nullif(trim(coalesce(p_campaign_key,'')),''),p_visible_from,p_visible_until,p_travel_from,p_travel_until,coalesce(p_locale_readiness,'{}'::jsonb),auth.uid()) on conflict(trip_id) do update set featured_rank=excluded.featured_rank,campaign_key=excluded.campaign_key,visible_from=excluded.visible_from,visible_until=excluded.visible_until,travel_from=excluded.travel_from,travel_until=excluded.travel_until,locale_readiness=excluded.locale_readiness,version=public.product_merchandising.version+1,updated_by=auth.uid(),updated_at=now() where public.product_merchandising.version=p_expected_version returning version into v_version;if v_version is null then raise exception 'merchandising version conflict';end if;return v_version;end$$;
revoke all on function public.get_operations_merchandising(),public.operations_update_merchandising(uuid,integer,integer,text,timestamptz,timestamptz,date,date,jsonb) from public,anon;grant execute on function public.get_operations_merchandising(),public.operations_update_merchandising(uuid,integer,integer,text,timestamptz,timestamptz,date,date,jsonb) to authenticated,service_role;
commit;
