begin;
do $$begin
 if exists(select 1 from public.departures group by trip_id,departs_at having count(*)>1) then raise exception 'duplicate departure business keys must be resolved before upgrade'; end if;
end$$;
create unique index if not exists departures_trip_departure_unique on public.departures(trip_id,departs_at);
create or replace function public.get_operations_editable_departures(p_from timestamptz default now()-interval '1 day',p_to timestamptz default now()+interval '120 days') returns table(id uuid,trip_title text,departs_at timestamptz,seat_price_jpy integer,capacity integer,sales_open_at timestamptz,sales_close_at timestamptz,status text,schedule_version integer,committed_seats bigint) language sql stable security definer set search_path=public,pg_temp as $$
 select d.id,t.title,d.departs_at,d.seat_price_jpy,d.capacity,d.sales_open_at,d.sales_close_at,d.status,d.schedule_version,coalesce(sum(l.seats) filter(where l.status='committed' or (l.status='held' and l.expires_at>now())),0)::bigint from public.departures d join public.trips t on t.id=d.trip_id left join public.inventory_locks l on l.departure_id=d.id where public.is_operations() and d.departs_at between p_from and p_to group by d.id,t.title order by d.departs_at
$$;
create or replace function public.get_operations_driver_statistics(p_from date,p_to date) returns table(driver_id uuid,driver_name text,assigned_runs bigint,completed_runs bigint,open_incidents bigint,last_location_at timestamptz) language sql stable security definer set search_path=public,pg_temp as $$
 select dr.id,dr.display_name,count(distinct dt.id) filter(where d.id is not null),count(distinct dt.id) filter(where d.id is not null and js.status='completed'),count(distinct oi.id) filter(where d.id is not null and oi.resolved_at is null),max(lp.recorded_at) from public.driver_resources dr left join public.dispatch_tasks dt on dt.driver_id=dr.id left join public.vehicle_assignments va on va.id=dt.vehicle_assignment_id left join public.vehicle_groups vg on vg.vehicle_assignment_id=va.id left join public.departures d on d.id=vg.departure_id and (d.departs_at at time zone 'Asia/Tokyo')::date between p_from and p_to left join public.vehicle_group_journey_state js on js.vehicle_group_id=vg.id left join public.operational_incidents oi on oi.vehicle_group_id=vg.id left join lateral(select recorded_at from public.driver_location_points where vehicle_group_id=vg.id order by recorded_at desc limit 1) lp on true where public.is_operations() and dr.status<>'suspended' group by dr.id,dr.display_name order by completed_runs desc,assigned_runs desc,dr.display_name
$$;
revoke all on function public.get_operations_editable_departures(timestamptz,timestamptz),public.get_operations_driver_statistics(date,date) from public,anon;
grant execute on function public.get_operations_editable_departures(timestamptz,timestamptz),public.get_operations_driver_statistics(date,date) to authenticated,service_role;
commit;
