begin;
create table public.guided_tour_plans(id uuid primary key default gen_random_uuid(),route_key text not null unique,title text not null,version integer not null default 1 check(version>0),status text not null default 'draft' check(status in ('draft','active','retired')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.guided_tour_nodes(id uuid primary key default gen_random_uuid(),plan_id uuid not null references public.guided_tour_plans(id) on delete cascade,node_key text not null,area_key text not null,sequence integer not null check(sequence>0),name text not null,instruction jsonb not null default '{}'::jsonb,latitude numeric(9,6) not null,longitude numeric(9,6) not null,trigger_radius_meters integer not null check(trigger_radius_meters between 20 and 500),estimated_minutes integer not null check(estimated_minutes between 1 and 360),node_kind text not null check(node_kind in ('dropoff','walk','landmark','food','admission','pickup')),branch_keys text[] not null default array['default']::text[],verification_status text not null check(verification_status in ('map_checked','field_check_required')),unique(plan_id,node_key),unique(plan_id,sequence));
create table public.vehicle_group_guided_tours(id uuid primary key default gen_random_uuid(),vehicle_group_id uuid not null unique references public.vehicle_groups(id) on delete cascade,plan_id uuid not null references public.guided_tour_plans(id),activated_by uuid not null references public.profiles(id),activated_at timestamptz not null default now());
create table public.guided_tour_progress(id uuid primary key default gen_random_uuid(),assignment_id uuid not null references public.vehicle_group_guided_tours(id) on delete cascade,account_id uuid not null references public.profiles(id) on delete cascade,branch_key text not null default 'meal-first',completed_node_keys text[] not null default '{}',last_acknowledged_node_key text,updated_at timestamptz not null default now(),unique(assignment_id,account_id));
alter table public.guided_tour_plans enable row level security;alter table public.guided_tour_nodes enable row level security;alter table public.vehicle_group_guided_tours enable row level security;alter table public.guided_tour_progress enable row level security;
revoke all on public.guided_tour_plans,public.guided_tour_nodes,public.vehicle_group_guided_tours,public.guided_tour_progress from public,anon,authenticated;grant select on public.guided_tour_plans,public.guided_tour_nodes,public.vehicle_group_guided_tours,public.guided_tour_progress to authenticated;grant all on public.guided_tour_plans,public.guided_tour_nodes,public.vehicle_group_guided_tours,public.guided_tour_progress to service_role;
create policy guided_plans_authenticated_read on public.guided_tour_plans for select to authenticated using(status='active' or public.is_operations());
create policy guided_nodes_authenticated_read on public.guided_tour_nodes for select to authenticated using(exists(select 1 from public.guided_tour_plans p where p.id=plan_id and (p.status='active' or public.is_operations())));
create policy guided_assignments_scope on public.vehicle_group_guided_tours for select to authenticated using(public.is_operations() or public.is_group_staff(vehicle_group_id) or exists(select 1 from public.vehicle_group_orders vgo join public.orders o on o.id=vgo.order_id where vgo.vehicle_group_id=public.vehicle_group_guided_tours.vehicle_group_id and o.account_id=auth.uid() and o.status in ('paid','confirmed')));
create policy guided_progress_owner_staff on public.guided_tour_progress for select to authenticated using(account_id=auth.uid() or public.is_operations() or exists(select 1 from public.vehicle_group_guided_tours a where a.id=assignment_id and public.is_group_staff(a.vehicle_group_id)));
insert into public.guided_tour_plans(route_key,title,version,status) values('kiyomizu-arashiyama','清水寺与岚山 AI 随行',1,'active') on conflict(route_key) do update set title=excluded.title,version=excluded.version,status=excluded.status,updated_at=now();
with p as(select id from public.guided_tour_plans where route_key='kiyomizu-arashiyama'),n(node_key,area_key,sequence,name,zh,lat,lng,radius,minutes,kind,branches,verification) as(values
('kodaiji-dropoff','kiyomizu',1,'高台寺停车场','车辆下车，向二年坂、三年坂方向步行。',35.000420,135.779310,90,5,'dropoff',array['default'],'field_check_required'),('ninenzaka','kiyomizu',2,'二年坂入口','下台阶进入二年坂，请注意脚下。',34.998300,135.780770,65,5,'walk',array['default'],'map_checked'),('starbucks-ninenzaka','kiyomizu',3,'京都二寧坂星巴克','前方右侧为榻榻米风格门店。',34.998190,135.780900,45,10,'food',array['default'],'map_checked'),('sannenzaka','kiyomizu',4,'三年坂','沿三年坂前行，可经过抹茶馆与杉养蜂园。',34.996850,135.781660,60,12,'landmark',array['default'],'map_checked'),('kiyomizu-niomon','kiyomizu',5,'清水寺仁王门','到达入口，请按现场规则购票。',34.994960,135.784570,70,60,'admission',array['default'],'map_checked'),('kiyomizu-pickup','kiyomizu',6,'清水寺返程上车点','出口左转下坡，前往当天指定停车场。',34.993870,135.779890,90,5,'pickup',array['default'],'field_check_required'),('togetsukyo-dropoff','arashiyama',7,'岚山渡月桥河边','选择用餐优先或游玩优先。',35.013600,135.677770,100,10,'dropoff',array['default'],'field_check_required'),('arashiyama-meal','arashiyama',8,'岚山商店街用餐','控制用餐时间，预留后续游览时间。',35.014420,135.677080,100,50,'food',array['meal-first'],'field_check_required'),('arabica-fukuda','arashiyama',9,'河畔咖啡与福田美术馆','繁忙时请评估排队时间。',35.012770,135.676250,80,25,'landmark',array['meal-first','sightseeing-first'],'map_checked'),('tenryuji','arashiyama',10,'天龙寺','注意开放时间和参拜规则。',35.015760,135.673700,90,40,'admission',array['meal-first','sightseeing-first'],'map_checked'),('arashiyama-park','arashiyama',11,'岚山公园','观景后留意返回竹林方向的时间。',35.014780,135.670370,100,20,'landmark',array['meal-first','sightseeing-first'],'map_checked'),('saga-hair-shrine','arashiyama',12,'嵯峨岚山站与御发神社','时间不足时建议直接前往竹林。',35.018680,135.675330,110,25,'landmark',array['meal-first','sightseeing-first'],'field_check_required'),('bamboo-grove','arashiyama',13,'岚山竹林','人多时请跟紧同行人员。',35.017140,135.671310,90,25,'landmark',array['meal-first','sightseeing-first'],'map_checked'),('nonomiya','arashiyama',14,'野宫神社','参拜后向当天上车点移动。',35.017680,135.674010,70,15,'landmark',array['meal-first','sightseeing-first'],'map_checked'),('arashiyama-meal-last','arashiyama',15,'渡月桥周边用餐／接客','游玩优先路线最后返回渡月桥。',35.013600,135.677770,100,45,'food',array['sightseeing-first'],'field_check_required'),('tateishi-pickup','arashiyama',16,'岚山指定上车点','以司机当天实时坐标为准。',35.020020,135.676080,110,5,'pickup',array['meal-first'],'field_check_required'))
insert into public.guided_tour_nodes(plan_id,node_key,area_key,sequence,name,instruction,latitude,longitude,trigger_radius_meters,estimated_minutes,node_kind,branch_keys,verification_status) select p.id,n.node_key,n.area_key,n.sequence,n.name,jsonb_build_object('zh-CN',n.zh),n.lat,n.lng,n.radius,n.minutes,n.kind,n.branches,n.verification from p cross join n on conflict(plan_id,node_key) do update set name=excluded.name,instruction=excluded.instruction,latitude=excluded.latitude,longitude=excluded.longitude,trigger_radius_meters=excluded.trigger_radius_meters,estimated_minutes=excluded.estimated_minutes,node_kind=excluded.node_kind,branch_keys=excluded.branch_keys,verification_status=excluded.verification_status;
alter table public.notification_outbox drop constraint if exists notification_outbox_event_type_check;alter table public.notification_outbox add constraint notification_outbox_event_type_check check(event_type in ('order-confirmed','bank-transfer-pending','meeting-updated','trip-room-opened','departure-reminder','departure-delayed','boarding-completed','checkin-reminder','passenger-contact-escalation','meeting-started','trip-progress','trip-completed','free-time-started'));
alter table public.staff_execution_events drop constraint if exists staff_execution_events_event_type_check;alter table public.staff_execution_events add constraint staff_execution_events_event_type_check check(event_type in ('task_accepted','meeting_started','meeting_updated','stop_arrived','free_time_started','trip_completed','delay_reported','incident_reported','support_requested'));
create or replace function public.start_vehicle_group_free_time(p_vehicle_group uuid,p_stop_name text,p_minutes integer,p_idempotency_key text) returns boolean language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room uuid;v_event uuid;v_content text;v_order record;begin
if auth.uid() is null or not(public.is_operations() or public.is_group_staff(p_vehicle_group)) then raise exception 'assigned staff only';end if;if length(trim(p_stop_name)) not between 2 and 160 or p_minutes not between 5 and 360 or length(trim(p_idempotency_key))<8 then raise exception 'invalid free time';end if;
insert into public.staff_execution_events(vehicle_group_id,actor_id,event_type,detail,idempotency_key) values(p_vehicle_group,auth.uid(),'free_time_started',jsonb_build_object('stopName',trim(p_stop_name),'minutes',p_minutes),p_idempotency_key) on conflict(actor_id,idempotency_key) do update set idempotency_key=excluded.idempotency_key returning id into v_event;
select id into v_room from public.trip_rooms where vehicle_group_id=p_vehicle_group and status='open';if v_room is null then raise exception 'trip room is not open';end if;v_content:=format('%s自由活动开始，建议游玩时间约%s分钟。请以顶部集合时间和地点为准。',trim(p_stop_name),p_minutes);insert into public.trip_room_messages(trip_room_id,author_id,content,important,kind,original_content,template_key) values(v_room,auth.uid(),v_content,true,'text',v_content,'free_time_started');
for v_order in select o.id,o.account_id from public.vehicle_group_orders vgo join public.orders o on o.id=vgo.order_id where vgo.vehicle_group_id=p_vehicle_group and o.status in ('paid','confirmed') loop insert into public.notification_outbox(event_id,event_type,recipient_id,order_id,necessary,payload,status) values('free-time:'||v_event::text||':'||v_order.id::text,'free-time-started',v_order.account_id,v_order.id,true,jsonb_build_object('vehicleGroupId',p_vehicle_group,'stopName',trim(p_stop_name),'minutes',p_minutes,'message',v_content),'pending') on conflict(event_id) do nothing;end loop;return true;end$$;
revoke all on function public.start_vehicle_group_free_time(uuid,text,integer,text) from public,anon;grant execute on function public.start_vehicle_group_free_time(uuid,text,integer,text) to authenticated,service_role;
commit;
