begin;
alter table public.driver_resources add column if not exists operations_note text not null default '' check(length(operations_note)<=500);
create or replace function public.operations_update_driver_resource(p_driver uuid,p_display_name text,p_status text,p_service_role text,p_public_phone text,p_internal_phone text,p_operations_note text)
returns boolean language plpgsql security definer set search_path=public,pg_temp as $$declare v public.driver_resources%rowtype;
begin if not public.is_operations() then raise exception 'operations role required';end if;select * into v from public.driver_resources where id=p_driver for update;if not found then raise exception 'driver not found';end if;if length(trim(coalesce(p_display_name,'')))<1 or p_status not in('available','unavailable','suspended') or p_service_role not in('driver','guide','driver_guide') then raise exception 'invalid driver update';end if;update public.driver_resources set display_name=trim(p_display_name),status=p_status::public.driver_resource_status,service_role=p_service_role,public_phone=nullif(trim(coalesce(p_public_phone,'')),''),private_phone=nullif(trim(coalesce(p_internal_phone,'')),''),operations_note=trim(coalesce(p_operations_note,'')),updated_at=now() where id=p_driver;insert into public.account_audit_events(actor_id,action,target_type,target_id,metadata)values(auth.uid(),'driver_resource_updated','driver_resource',p_driver,jsonb_build_object('priorStatus',v.status,'newStatus',p_status,'serviceRole',p_service_role));return true;end$$;
create or replace function public.operations_update_fleet_vehicle(p_vehicle uuid,p_status text,p_color text,p_photo_url text,p_model_name text,p_inspection_required boolean,p_operations_note text)
returns boolean language plpgsql security definer set search_path=public,pg_temp as $$declare v public.fleet_vehicles%rowtype;
begin if not public.is_operations() then raise exception 'operations role required';end if;select * into v from public.fleet_vehicles where id=p_vehicle for update;if not found then raise exception 'vehicle not found';end if;if p_status not in('available','assigned','in_service','maintenance','inactive') then raise exception 'invalid vehicle status';end if;if p_status='available' and coalesce(p_inspection_required,false) then raise exception 'inspection-required vehicle cannot be available';end if;update public.fleet_vehicles set status=p_status::public.fleet_vehicle_status,public_color=nullif(trim(coalesce(p_color,'')),''),public_photo_url=nullif(trim(coalesce(p_photo_url,'')),''),model_name=nullif(trim(coalesce(p_model_name,'')),''),inspection_required=coalesce(p_inspection_required,false),operations_note=trim(coalesce(p_operations_note,'')),updated_at=now() where id=p_vehicle;insert into public.account_audit_events(actor_id,action,target_type,target_id,metadata)values(auth.uid(),'fleet_vehicle_updated','fleet_vehicle',p_vehicle,jsonb_build_object('priorStatus',v.status,'newStatus',p_status,'inspectionRequired',p_inspection_required));return true;end$$;
revoke all on function public.operations_update_driver_resource(uuid,text,text,text,text,text,text),public.operations_update_fleet_vehicle(uuid,text,text,text,text,boolean,text) from public,anon;
grant execute on function public.operations_update_driver_resource(uuid,text,text,text,text,text,text),public.operations_update_fleet_vehicle(uuid,text,text,text,text,boolean,text) to authenticated,service_role;
commit;
