import {useEffect,useState,type FormEvent} from 'react';
import {Link} from 'react-router-dom';
import {useApp} from '../store';
import type {OperationsEditableDeparture,OperationsProduct} from '../../shared/integrations/supabaseOperations';
const uuid=()=>crypto.randomUUID();
const japanLocalToIso=(value:string)=>new Date(`${value}:00+09:00`).toISOString();
const local=(iso:string)=>new Date(new Date(iso).getTime()+9*60*60*1000).toISOString().slice(0,16);
const values=(form:FormData)=>({tripId:String(form.get('tripId')),start:String(form.get('start')),end:String(form.get('end')),weekdays:String(form.get('weekdays')).split(',').map(Number),departureTime:String(form.get('departureTime')),durationMinutes:Number(form.get('durationMinutes')),price:Number(form.get('price')),capacity:Number(form.get('capacity')),salesOpen:japanLocalToIso(String(form.get('salesOpen'))),closeHours:Number(form.get('closeHours')),meetingName:String(form.get('meetingName')),meetingAddress:String(form.get('meetingAddress')),mapLat:Number(form.get('mapLat')),mapLng:Number(form.get('mapLng'))});
export function DepartureCenter(){
 const {services}=useApp();const [products,setProducts]=useState<OperationsProduct[]>([]);const [departures,setDepartures]=useState<OperationsEditableDeparture[]>([]);const [editing,setEditing]=useState<OperationsEditableDeparture|null>(null);const [preview,setPreview]=useState<Array<Record<string,unknown>>>([]);const [request,setRequest]=useState<Record<string,unknown>|null>(null);const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
 const reloadDepartures=async()=>{if(!services)return;const result=await services.operations.listEditableDepartures();setDepartures(result.data);setEditing(current=>result.data.find(item=>item.id===current?.id)??null);if(result.error)setNotice(result.error)};
 useEffect(()=>{let active=true;if(services)void Promise.all([services.operations.listProducts(),services.operations.listEditableDepartures()]).then(([productResult,departureResult])=>{if(!active)return;setProducts(productResult.data);setDepartures(departureResult.data);setNotice(productResult.error??departureResult.error??'')});return()=>{active=false}},[services]);
 const onPreview=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!services)return;setBusy(true);const input=values(new FormData(event.currentTarget));const result=await services.operations.previewDepartureBatch(input);setBusy(false);setPreview(result.data);setRequest(input);setNotice(result.error?`预览失败：${result.error}`:`预览 ${result.data.length} 个班次；重复项不会再次创建`)};
 const confirm=async()=>{if(!services||!request)return;setBusy(true);const result=await services.operations.createDepartureBatch({...request,operationId:uuid()} as Parameters<typeof services.operations.createDepartureBatch>[0]);setBusy(false);setNotice(result.error?`创建失败：${result.error}`:`创建完成：${JSON.stringify(result.data)}`);if(!result.error)await reloadDepartures()};
 const update=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!services||!editing)return;const form=new FormData(event.currentTarget);setBusy(true);const result=await services.operations.updateDeparture({id:editing.id,expectedVersion:editing.version,price:Number(form.get('editPrice')),capacity:Number(form.get('editCapacity')),salesOpenAt:japanLocalToIso(String(form.get('editSalesOpen'))),salesCloseAt:japanLocalToIso(String(form.get('editSalesClose'))),status:String(form.get('editStatus'))});setBusy(false);setNotice(result.ok?'班次已更新；已下单价格快照保持不变':`更新失败：${result.error}`);if(result.ok)await reloadDepartures()};
 return <main className="operations-page"><header className="operations-hero"><div><span>DEPARTURES & PRICING</span><h1>班次与价格</h1><p>所有时间按日本时间；新建先预览，修改使用版本锁避免覆盖。</p></div><Link className="button secondary" to="/app/operations">返回工作台</Link></header>
 <section className="operations-section"><header><div><span>已有班次</span><h2>价格与截止时间调整</h2></div><small>容量不能低于已锁定席位</small></header><div className="operations-dispatch-list">{departures.map(item=><button type="button" key={item.id} className={editing?.id===item.id?'selected':''} onClick={()=>setEditing(item)}><b>{item.tripTitle}</b><span>{new Date(item.departsAt).toLocaleString('zh-CN',{timeZone:'Asia/Tokyo'})}</span><small>¥{item.price} · {item.committedSeats}/{item.capacity}席 · {item.status} · v{item.version}</small></button>)}</div>{editing&&<form key={`${editing.id}:${editing.version}`} className="operations-controls" onSubmit={update}><label>每席价格（日元）<input name="editPrice" type="number" min="1" defaultValue={editing.price} required/></label><label>销售容量<input name="editCapacity" type="number" min={editing.committedSeats} defaultValue={editing.capacity} required/></label><label>开始销售<input name="editSalesOpen" type="datetime-local" defaultValue={local(editing.salesOpenAt)} required/></label><label>销售截止<input name="editSalesClose" type="datetime-local" defaultValue={local(editing.salesCloseAt)} required/></label><label>状态<select name="editStatus" defaultValue={editing.status}>{['draft','open','closed','cancelled'].map(status=><option key={status}>{status}</option>)}</select></label><button className="button" disabled={busy}>确认更新班次</button></form>}</section>
 <section className="operations-section"><header><div><span>批量建班</span><h2>创建新班次</h2></div></header><form className="operations-controls" onSubmit={onPreview}><label>产品<select name="tripId" required>{products.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>开始日期<input name="start" type="date" required/></label><label>结束日期<input name="end" type="date" required/></label><label>星期（1=周一，7=周日）<input name="weekdays" defaultValue="6,7" required/></label><label>出发时间<input name="departureTime" type="time" defaultValue="09:00" required/></label><label>预计分钟<input name="durationMinutes" type="number" defaultValue="600" min="60" required/></label><label>每席价格（日元）<input name="price" type="number" min="1" required/></label><label>销售容量<input name="capacity" type="number" min="1" required/></label><label>开始销售<input name="salesOpen" type="datetime-local" required/></label><label>出发前几小时截止<input name="closeHours" type="number" defaultValue="24" min="1" required/></label><label>集合地点<input name="meetingName" required/></label><label>集合地址<input name="meetingAddress" required/></label><label>集合纬度<input name="mapLat" type="number" min="-90" max="90" step="0.000001" required/></label><label>集合经度<input name="mapLng" type="number" min="-180" max="180" step="0.000001" required/></label><button className="button" disabled={busy}>生成预览</button></form></section>
 {notice&&<p className="operations-notice">{notice}</p>}{preview.length>0&&<section className="operations-section"><header><div><span>影响预览</span><h2>{preview.length} 个候选班次</h2></div><button className="button" disabled={busy} onClick={()=>void confirm()}>确认创建</button></header><div className="operations-dispatch-list">{preview.map((item,index)=><article key={index}><b>{String(item.serviceDate)}</b><span>¥{String(item.price)} · {String(item.capacity)}席</span><small>{item.duplicate?'已存在，将跳过':'可创建'}</small></article>)}</div></section>}</main>
}
