import {useEffect,useState,type FormEvent} from 'react';
import {Link} from 'react-router-dom';
import {useApp} from '../store';
import type {OperationsProduct} from '../../shared/integrations/supabaseOperations';

export function ProductCenter(){
  const {services}=useApp();const [products,setProducts]=useState<OperationsProduct[]>([]);const [selected,setSelected]=useState<OperationsProduct|null>(null);const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
  const reload=async()=>{if(!services)return;const result=await services.operations.listProducts();setProducts(result.data);setNotice(result.error??'');setSelected(current=>result.data.find(item=>item.id===current?.id)??result.data[0]??null)};
  useEffect(()=>{let active=true;if(services)void services.operations.listProducts().then(result=>{if(!active)return;setProducts(result.data);setNotice(result.error??'');setSelected(result.data[0]??null)});return()=>{active=false}},[services]);
  const save=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!services||!selected)return;const form=new FormData(event.currentTarget);setBusy(true);const gallery=String(form.get('gallery')??'').split('\n').map(v=>v.trim()).filter(Boolean);const result=await services.operations.saveProductDraft({id:selected.id,expectedVersion:selected.catalogVersion,title:String(form.get('title')??''),content:{summary:String(form.get('summary')??''),description:String(form.get('description')??'')},heroImageUrl:String(form.get('hero')??'').trim()||null,gallery});setBusy(false);setNotice(result.ok?'草稿已保存，游客仍看到原公开版本':`保存失败：${result.error}`);if(result.ok)await reload()};
  const publish=async()=>{if(!services||!selected)return;setBusy(true);const result=await services.operations.publishProduct(selected.id,selected.catalogVersion);setBusy(false);setNotice(result.ok?'已发布；游客端重新读取后显示此版本':`发布失败：${result.error}`);if(result.ok)await reload()};
  return <main className="operations-page"><header className="operations-hero"><div><span>PRODUCT CENTER</span><h1>产品管理</h1><p>草稿与公开版本分离；发布后游客端读取同一目录。</p></div><Link className="button secondary" to="/app/operations">返回工作台</Link></header>{notice&&<p className="operations-notice">{notice}</p>}<section className="operations-section"><header><div><span>九条路线</span><h2>产品列表</h2></div><small>公开版本 / 草稿版本 / 数据版本</small></header><div className="operations-dispatch-list">{products.map(item=><button type="button" key={item.id} onClick={()=>setSelected(item)} className={selected?.id===item.id?'selected':''}><b>{item.title}</b><span>{item.slug}</span><small>{item.status} · 公开 v{item.publishedRevision??'—'} · 草稿 v{item.draftRevision??'—'} · 数据 {item.catalogVersion}</small></button>)}</div></section>{selected&&<section className="operations-section"><header><div><span>编辑草稿</span><h2>{selected.title}</h2></div><small>版本 {selected.catalogVersion}；冲突时拒绝覆盖</small></header><form key={`${selected.id}:${selected.catalogVersion}`} className="operations-controls" onSubmit={save}><label>标题<input name="title" defaultValue={selected.title} required/></label><label>摘要<textarea name="summary" defaultValue={String(selected.content.summary??'')} required/></label><label>详细介绍<textarea name="description" defaultValue={String(selected.content.description??'')}/></label><label>主图 URL<input name="hero" defaultValue={selected.heroImageUrl??''}/></label><label>图库（每行一张）<textarea name="gallery" defaultValue={selected.gallery.join('\n')}/></label><div className="operations-task-actions"><button className="button" disabled={busy}>保存草稿</button><Link className="button secondary" to={`/app/trips/${selected.slug}`}>查看当前公开页</Link><button className="button" type="button" disabled={busy||selected.draftRevision==null} onClick={()=>void publish()}>发布草稿</button></div></form></section>}</main>
}
